move-language/move

language/move-vm/runtime/src/interpreter.rs
language/move-vm/runtime/src/loader.rs
language/move-vm/runtime/src/runtime.rs
language/move-vm/runtime/src/session.rs
language/move-vm/transactional-tests/tests/builtins/vector_ops_using_generics.exp
language/move-vm/transactional-tests/tests/builtins/vector_ops_using_generics.mvir

- allow for easy adapter rules, as was similarly intended with the load_function API
- Fix some vector operations
- new test

[move-vm] Add load_script to session API

---

language/evm/hardhat-examples/contracts/ExternalCall/sources/ExternalCall.move
language/evm/hardhat-examples/test/ExternalCall.test.js
language/evm/hardhat-move/package-lock.json
language/evm/move-to-yul/src/external_functions.rs
language/evm/move-to-yul/tests/test-dispatcher/ExternalCall.exp

Resolve #31 
Yes
Hardhat tests

[move-to-yul] Fix issue on allocating memory for external call

---

language/evm/hardhat-examples/contracts/ERC1155ReceiverMock.sol
language/evm/hardhat-examples/contracts/ExternalCall/sources/ExternalCall.move
language/evm/hardhat-examples/test/ExternalCall.test.js

Raises the following issues:
- https://github.com/move-language/move/issues/41
- https://github.com/move-language/move/issues/42
- https://github.com/move-language/move/issues/43
to add more examples
yes
npx hardhat test

[evm] Added test cases to reproduce bugs in external calls

---

language/evm/hardhat-examples/contracts/ExternalCall/sources/ExternalCall.move
language/evm/hardhat-examples/test/ExternalCall.test.js
language/evm/move-to-yul/src/external_functions.rs
language/evm/move-to-yul/tests/test-dispatcher/ExternalCall.exp

Resolve #41  #42 #43 
Yes
hardhat tests

[move-to-yul] Fix bugs

---

language/evm/hardhat-move/src/index.ts

Right now, when you compile Move contracts in hardhat, no results are shown until all build tasks have finished, which may confuse the user. This PR changes it so that the result is printed out once each individual build task finishes, notifying the user of the progress.

[evm][hardhat-move] print out result as soon as each build task finishes

---

language/tools/move-resource-viewer/src/lib.rs
language/tools/move-resource-viewer/src/resolver.rs

mentioned here https://github.com/move-language/move/issues/71
Yes
did joint test with running a local chain and view the transaction info
however, there is no current e2e or unit test with move-resource-viewer. Plan to add more test coverage to this module in following issue https://github.com/move-language/move/issues/78

exclude &signer in view_function_arguments

---

language/testing-infra/transactional-test-runner/src/framework.rs

- A helpful API function that was missing
- Eyes

[transactional-test] Add missing API function

---

language/tools/move-cli/README.md

Previous versions of commands listed in tutorial threw errors

Update sandbox exp-test commands, options

---

language/testing-infra/transactional-test-runner/src/framework.rs
language/testing-infra/transactional-test-runner/src/tasks.rs
language/testing-infra/transactional-test-runner/src/vm_test_harness.rs
language/testing-infra/transactional-test-runner/tests/vm_test_harness/leading_comment.exp
language/testing-infra/transactional-test-runner/tests/vm_test_harness/leading_comment.move

- Support leading comments at the beginning of the test file
- Helpful for copyright information and test descriptions
- Add optional default value for named addresses on miss
- New tests

Leading comment

---

language/evm/hardhat-examples/contracts/ERC1155Tradable/Move.toml
language/evm/hardhat-examples/contracts/ERC1155Tradable/sources/ERC1155Tradable.move
language/evm/hardhat-examples/contracts/ERC721Tradable/Move.toml
language/evm/hardhat-examples/contracts/ERC721Tradable/sources/ERC721Tradable.move
language/evm/hardhat-examples/contracts/ERC721Tradable_Sol.sol
language/evm/hardhat-examples/hardhat.config.js
language/evm/hardhat-examples/scripts/deploy_ERC1155.js
language/evm/hardhat-examples/scripts/deploy_ERC20.js
language/evm/hardhat-examples/scripts/deploy_ERC721.js
language/evm/hardhat-examples/test/ERC721.test.js

- Added ERC721Tradable and ERC1155Tradable which are compatible with Opensea
- Modified and added the scripts to deploy ERC20, ERC721 and ERC1155
To add the ERC721 and ERC1155 contracts which are compatible with Opensea
yes
npx hardhat test

[evm] Added ERC721Tradable and ERC1155Tradable

---

language/tools/move-package/src/lib.rs

fix option `--test` help message

---

language/testing-infra/transactional-test-runner/src/framework.rs
language/testing-infra/transactional-test-runner/src/tasks.rs
language/testing-infra/transactional-test-runner/src/vm_test_harness.rs

- minor fixes for transactional testing
- cargo x check

[transactional-test-runner] Minor fixes

---

language/evm/README.md
language/evm/examples/README.md
language/evm/examples/sources/ERC721.move
language/evm/hardhat-examples/README.md
language/evm/stdlib/README.md

This PR added and updated `README.md` files in the `language/evm` directory and its sub-directories. 
The link of this file will be added in the awesome-move list: https://github.com/MystenLabs/awesome-move/blob/main/README.md#miscellaneous
To add README file for Move-On-EVM
yes

[evm] `README.md` for `language/evm`

---

language/tools/move-cli/tests/build_tests/unbound_address/args.evm.exp
language/tools/move-cli/tests/build_tests/unbound_address/args.exp
language/tools/move-package/src/resolution/resolution_graph.rs
language/tools/move-package/tests/test_sources/resolution/basic_no_deps_address_not_assigned/Move.exp

Fixing an unresolved address issue is easy (requires a small addition to Move.toml), but that may not be obvious to package system novices. Suggest the resolution in the error message.

[package manager] Improve unresolved addresses error message

---

Cargo.lock
language/tools/move-package/Cargo.toml
language/tools/move-package/src/source_package/manifest_parser.rs

trying to fix https://github.com/starcoinorg/starcoin/issues/3400
yes

[fix] fix `HOME environment variable not found` on Windows platform

---

CONTRIBUTING.md

see: https://github.com/move-language/move/pull/133#issuecomment-1126848940
Yes

[doc] update CLA and script in CONTRIBUTING.md

---

README.md

The previous Discord invitation link got expired.
This particular link is unlimited in terms of uses and expiration.
Closes #143.
Yes.
Documentational only, no tests needed.

[README] Updated the Discord invitation link

---

language/move-prover/tests/sources/functional/verify_sort.move
language/move-prover/tests/sources/functional/verify_vector.move

- Added Ying's version of sorting function
- Added the placeholders for 2 way (and 3 way) sorting functions as Jianan's starter project.
To add a Prover test
yes
cargo test

[move-prover] Added a Prover test for verifying a sorting function

---

language/move-prover/README.md
language/move-prover/doc/user/spec-lang.md

fix doc file link
yes
click this link

doc: fix link in [move-prover/README.md] and spec-lang.md

---

language/documentation/spec/vm.md

Just a typo nit
Yes
Nothing to test

Fix minor typo in VM spec doc

---

language/documentation/tutorial/README.md

This removes remaining diem references from the tutorial and ensure everything is working as expected.
Prepare Move 101 for Aptos team
Yes
NA

[tutorial] Cleanup

---

Cargo.lock
Cargo.toml
language/evm/move-ethereum-abi/Cargo.toml
language/evm/move-ethereum-abi/src/abi_move_type.rs
language/evm/move-ethereum-abi/src/abi_signature_type.rs
language/evm/move-ethereum-abi/src/lib.rs
language/evm/move-to-yul/Cargo.toml
language/evm/move-to-yul/src/abi_signature.rs
language/evm/move-to-yul/src/context.rs
language/evm/move-to-yul/src/generator.rs

Initial step to support generating Ethereum ABI for Move
Yes

Ethereum ABI for Move

---

language/documentation/book/src/functions.md
language/documentation/book/src/unit-testing.md

- Updated docs to reflect new `entry` modifier
- docs are good
- eyes

[book] Update script visibility docs

---

language/move-vm/runtime/src/loader.rs
language/move-vm/runtime/src/session.rs

- Expose Loader::abilities
- Not necessary, but helpful
- eyes

[move-vm-runtime] Expose ability function

---

Cargo.lock
Cargo.toml
language/evm/extract-ethereum-abi/Cargo.toml
language/evm/extract-ethereum-abi/src/main.rs
language/evm/move-ethereum-abi/Cargo.toml
language/evm/move-ethereum-abi/src/abi_move_type.rs
language/evm/move-to-yul/src/abi_move_metadata.rs
language/evm/move-to-yul/src/context.rs
language/evm/move-to-yul/src/generator.rs
language/evm/move-to-yul/src/lib.rs

1)  Add a cli to generate metadata from ABIMoveSignature
2) Convert  ABIMoveSignature to ethabi::Contract
Yes

Generate metadata for move-ethereum-ABI

---

language/documentation/book/src/loops.md

fix code snippets in loop.md, such as wrong name, unintended infinite loop
yes
run code snippets

[doc] fix code snippets in loop.md

---

language/move-prover/tests/sources/functional/choice.cvc5_exp
language/move-prover/tests/sources/functional/script_incorrect.cvc5_exp
language/move-prover/tests/sources/functional/trace.cvc5_exp

fix `cargo xtest` failure for cvc5 tests
yes
run `cargo xtest` and should pass

[test] update cvc5 exp

---

language/move-analyzer/editors/code/README.md

Format menu items in Move Analyzer README, make install options parallel

---

language/tools/move-cli/src/base/build.rs
language/tools/move-cli/src/base/coverage.rs
language/tools/move-cli/src/base/disassemble.rs
language/tools/move-cli/src/base/errmap.rs
language/tools/move-cli/src/base/info.rs
language/tools/move-cli/src/base/mod.rs
language/tools/move-cli/src/base/new.rs
language/tools/move-cli/src/base/prove.rs
language/tools/move-cli/src/base/test.rs
language/tools/move-cli/src/lib.rs
language/tools/move-cli/src/sandbox/cli.rs
language/tools/move-cli/src/sandbox/utils/package_context.rs
language/tools/move-cli/tests/build_tests/simple_new/args.exp
language/tools/move-cli/tests/build_tests/simple_new/args.txt

- Fix tabbing and new lines on command
- Fix behavior when no path is specified
- New test

[move-cli] Fix 'new' command

---

language/tools/move-cli/src/base/coverage.rs
language/tools/move-cli/src/base/disassemble.rs
language/tools/move-cli/src/base/errmap.rs
language/tools/move-cli/src/base/new.rs
language/tools/move-cli/src/base/prove.rs
language/tools/move-cli/src/base/test.rs
language/tools/move-cli/src/lib.rs

Oversight when making new CLI command structs

[move-cli] Make command fields pub

---

language/tools/move-cli/src/base/prove.rs

This PR enhances #246 by making it easier to specify prover options for applications outside of core Move. Without this refactoring, the options have to be passed as strings or the entire `run_move_prover` function needs to be copied to customize them. The refactoring enables "outside" prover users to reuse `run_move_prover` by replicating/augmenting code in a much shorter `execute` function only.
Yes

[move-prover] Refactored options creation for better reuse

---

.github/workflows/release_asset.yml

Fixbug for https://github.com/move-language/move/pull/208
Bad case:  https://github.com/yubing744/starcoin-move/runs/7166387417?check_suite_focus=true
YES
I tested it successfully in my own repository 
Release：https://github.com/yubing744/starcoin-move/releases/tag/v0.1.3
Pipeline:  https://github.com/yubing744/starcoin-move/actions/runs/2613095587

[move-analyzer] fixbug for windows bash not found in release_asset.yml

---

language/documentation/tutorial/step_4/BasicCoin/sources/BasicCoin.move
language/documentation/tutorial/step_4_sol/BasicCoin/sources/BasicCoin.move
language/documentation/tutorial/step_5/BasicCoin/sources/BasicCoin.move
language/documentation/tutorial/step_5_sol/BasicCoin/sources/BasicCoin.move
language/documentation/tutorial/step_6/BasicCoin/sources/BasicCoin.move
language/documentation/tutorial/step_7/BasicCoin/sources/BasicCoin.move
language/documentation/tutorial/step_8/BasicCoin/sources/BasicCoin.move
language/documentation/tutorial/step_8_sol/BasicCoin/sources/BasicCoin.move

I was just going through the tutorials and found some errors.
Yes
Only documents are changed. No test plans

[Tutorials]Fix tutorial examples

---

language/evm/README.md

Remove `source` directory in filetree to fix the link resolution
Small readme change to fix link resolution
Yes
N/A, simple readme change

nit: fix import resolution

---

.gitattributes

Change  syntax highlighting to move
Change move syntax highlighting 
Yes

Change move syntax highlighting

---

language/move-prover/bytecode/tests/borrow/function_call.exp
language/move-prover/bytecode/tests/borrow/function_call.move

This PR adds to prover test crate a test crafted by @awelc that reproduces the bug described by issue #270 .

[prover] repro test for borrow analysis bug

---

language/documentation/book/src/vector.md

fix mistyping

---

language/documentation/examples/experimental/basic-coin/sources/BasicCoin.move

Fixed std renaming bug.

---

language/documentation/tutorial/step_5/BasicCoin/sources/BasicCoin.move

Fix comment
Yes
No test needed

fix tutorial step_5 comment

---

language/documentation/tutorial/step_5/BasicCoin/sources/BasicCoin.move
language/documentation/tutorial/step_5_sol/BasicCoin/sources/BasicCoin.move

Fix tests.
Yes
Run `move test` under both `language/documentation/tutorial/step_5/BasicCoin` and `language/documentation/tutorial/step_5_sol/BasicCoin`

fix tutorial tests

---

language/documentation/tutorial/README.md

Fix error in tutorial code. Before this fix I was getting:
```
let addr = signer::address_of(&account);
^^^^^^ Unbound module alias 'signer'
```
YEs
Not applicable

Fix broken test code in readme

---

language/evm/move-to-yul/src/functions.rs
language/move-prover/boogie-backend/src/bytecode_translator.rs
language/move-prover/boogie-backend/src/prelude/prelude.bpl
language/move-prover/bytecode/src/borrow_analysis.rs
language/move-prover/bytecode/src/clean_and_optimize.rs
language/move-prover/bytecode/src/escape_analysis.rs
language/move-prover/bytecode/src/function_data_builder.rs
language/move-prover/bytecode/src/livevar_analysis.rs
language/move-prover/bytecode/src/memory_instrumentation.rs
language/move-prover/bytecode/src/read_write_set_analysis.rs
language/move-prover/bytecode/src/spec_instrumentation.rs
language/move-prover/bytecode/src/stackless_bytecode.rs
language/move-prover/bytecode/src/well_formed_instrumentation.rs
language/move-prover/bytecode/tests/borrow/basic_test.exp
language/move-prover/bytecode/tests/borrow_strong/basic_test.exp
language/move-prover/bytecode/tests/memory_instr/basic_test.exp
language/move-prover/interpreter-testsuite/tests/concrete_check/if_else.exp
language/move-prover/interpreter-testsuite/tests/concrete_check/if_else.move
language/move-prover/interpreter/src/concrete/local_state.rs
language/move-prover/interpreter/src/concrete/player.rs
language/move-prover/interpreter/src/concrete/value.rs
language/move-prover/tests/sources/functional/conditional_write_back.move
language/move-prover/tests/sources/functional/loops_with_memory_ops.cvc5_exp
language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
language/move-prover/tests/sources/functional/macro_verification.exp
language/move-prover/tests/sources/functional/mut_ref.exp

This PR contains a chain of commits that fixes several issues in the memory model:
The best way to review this PR is to review the commits one by one in the following order:
[[move-prover] fix is_parent tests for multiple write-back chains](https://github.com/move-language/move/pull/312/commits/a8c535c4eeba85216dc748a7ff71d7c109db92f9)
[[move-prover] improve the peephole optimization for write-back chains](https://github.com/move-language/move/pull/312/commits/0f651a6753a73c8f92ec5fad082b16952cd50166)
[[move-prover] do not peephole optimize the initial local and global borrows](https://github.com/move-language/move/commit/45b24d5571ca425c5684ee45b08e6849bb8dae81)
[[move-prover] use a special location to mark uninitialized mut refs](https://github.com/move-language/move/commit/075d51565ee91 …

[move-prover] multiple fixes to the memory model

---

language/move-core/types/src/account_address.rs

This allows us to deserialize human readable inputs to allow configs
and other human readable things to be easier to parse
Yes
None

[account-address] Allow fuzzy deserialize with or with 0x

---

language/tools/move-unit-test/src/test_runner.rs

Fixes https://github.com/move-language/move/issues/254
Yes

[move-cli] Filter tests by module_name::test_name

---

language/evm/README.md

People where trying to run the great ERC Move examples in this tree on MoveVM.

[move-on-evm] Clarify in the readme that this is an experimental feature

---

language/documentation/book/src/structs-and-resources.md

Fix broken link in docs
Yes
No test needed

fix broken link

---

language/documentation/book/src/unit-testing.md
language/documentation/book/src/vector.md

[doc] update vector.md vector::index_of

---

language/tools/move-cli/README.md

Make the example in doc work.
Yes
No test needed

[move-cli] Fix toml in cli readme

---

language/documentation/book/src/uses.md

Fix typo of overla(p)

---

language/move-core/types/src/language_storage.rs

chore: fix typo

---

language/tools/move-cli/src/base/test.rs
language/tools/move-unit-test/src/lib.rs

When runing `move test`, if compiling package produces warnings, then test will not run.
But most time, we just want to ignore the warnings, and fix it later after test ok.
I'd like to add a config entry to control the behavior.
yes

[move-cli]: run test ignore compiler warnings

---

.cargo/config

[move core] fix windows stack overflow

---

language/extensions/move-table-extension/src/lib.rs
language/extensions/move-table-extension/tests/move_unit_tests.rs
language/move-vm/test-utils/src/storage.rs

This adds proper gas metering to the table extension and fixes a bug with the return values: `Ok(NativeResult::err)` instead of `Err(..)` should be used in case of user errors.

[table] add proper gas metering and fix return value bug

---

language/move-prover/interpreter/src/concrete/player.rs
language/move-prover/interpreter/src/concrete/value.rs

- This is a follow-up PR for #219 to add function arguments that has an address or a signer field to the touched addresses
Yes.

[move-prover] Update touched addresses to include function arguments

---

README.md

Top level README doesn't have instructions for setup.
Yes
None

Link to language/documentation/tutorial/README.md

---

language/documentation/spec/vm.md

Minor typo in move-vm spec doc
`exiting` module &rarr;  `existing` module

Fix : typo in docs

---

language/extensions/move-table-extension/src/lib.rs
language/tools/move-unit-test/src/extensions.rs

it was overlooked that txn_hash is still 16 bytes and not crypto safe.

[table] use 32 bytes txn hash

---

language/move-compiler/src/naming/ast.rs

Restore more deleted on #421
https://github.com/move-language/move/pull/421/files#diff-3fd60c650fcfb3d1deac9894443f0397d7394d2a9774a6ac2a9f7b02ead46aefL1033
Yes

Restore more deleted on #421

---

language/move-prover/boogie-backend/src/boogie_wrapper.rs

Boogies does not always give an augmented execution trace. Handle such
cases gracefully instead of giving out a mysterious error.
Graceful error handling
Yes
CI

[move-prover] extract plain trace from boogie error reports

---

language/documentation/book/src/signer.md
language/documentation/book/translations/move-book-zh/src/signer.md

Update contents of signer in move-book and move-book-zh.

[move-book and move-book-zh] update signer

---

language/documentation/book/src/vector.md
language/documentation/book/translations/move-book-zh/src/vector.md

Update contents of vector in book and move-book-zh.

[book and move-book-zh] update vector

---

language/documentation/book/src/modules-and-scripts.md
language/documentation/book/translations/move-book-zh/src/modules-and-scripts.md

- Update contents in book
- Uupdate contents in move-book-zh

[book and move-book-zh] update modules and scripts

---

language/documentation/book/src/global-storage-structure.md
language/documentation/book/translations/move-book-zh/src/global-storage-structure.md

Update the contents of the global storage structure in move-book-zh and fix a small typo in book.

[move-book-zh] update global storage structure

---

language/documentation/book/src/coding-conventions.md
language/documentation/book/translations/move-book-zh/src/coding-conventions.md

Update the contents of move coding conventions in move-book and move-book-zh.

[book and move-book-zh] update move coding conventions

---

language/move-vm/runtime/src/loader.rs

The vm used the fact that a native function resolved also to identify whether a function is native or not. This decouples this decision to make the lazy binding produce the expected error.
Yes

[vm] Fix issue with lazy_natives feature

---

language/tools/move-cli/src/sandbox/commands/publish.rs
language/tools/move-cli/tests/sandbox_tests/cyclic_multi_module_publish/args.exp
language/tools/move-cli/tests/sandbox_tests/verify_native_functions_in_multi_module_publish/Move.toml
language/tools/move-cli/tests/sandbox_tests/verify_native_functions_in_multi_module_publish/args.exp
language/tools/move-cli/tests/sandbox_tests/verify_native_functions_in_multi_module_publish/args.txt
language/tools/move-cli/tests/sandbox_tests/verify_native_functions_in_multi_module_publish/sources/example.move
language/tools/move-cli/tests/sandbox_tests/verify_native_functions_in_multi_module_publish/sources/example_another.move

explain the error generated when publish multiple modules in bundle mode

explain error when publishing in bundle mode

---

CONTRIBUTING.md
GRAVEYARD.md

Explain how feature requests should be created and how they progress, add graveyard of features that were not accepted.

[docs] Explain feature request process in CONTRIBUTING.md

---

.github/workflows/ci-post-land.yml
.github/workflows/ci-pre-land.yml
CODEOWNERS
x.toml

Adds CODEOWNERS in the new Aptos release branch

[aptos branch] Add CODEOWNERS

---

language/documentation/book/src/structs-and-resources.md

Fix typo publis to public

---

language/move-bytecode-verifier/src/stack_usage_verifier.rs

[serializer] Fixing issues in serialization

---

language/documentation/book/src/signer.md
language/documentation/book/src/vector.md
language/documentation/book/translations/move-book-zh/src/SUMMARY.md
language/documentation/book/translations/move-book-zh/src/address.md
language/documentation/book/translations/move-book-zh/src/coding-conventions.md
language/documentation/book/translations/move-book-zh/src/global-storage-structure.md
language/documentation/book/translations/move-book-zh/src/modules-and-scripts.md
language/documentation/book/translations/move-book-zh/src/references.md
language/documentation/book/translations/move-book-zh/src/signer.md
language/documentation/book/translations/move-book-zh/src/vector.md

Update summary file of move-book-zh and fix some typos.
Yes

[move-book and move-book-zh] update summary and remove english contents that has been proof

---

language/move-binary-format/src/compatibility.rs

Until now, when a struct was removed, this only counted as a `struct_and_function_linkage` compatibility issue. However, it is also a `struct_layout` issue because it opens the door to first remove a struct, then re-add it with a different layout.
Yes
Existing

[compatibility] Make struct removal violate layout compatibility

---

language/move-binary-format/src/compatibility.rs
language/move-vm/runtime/src/runtime.rs
language/move-vm/runtime/src/session.rs
language/move-vm/transactional-tests/tests/module_publishing/republish_module_cyclic_dependencies_fn.exp
language/move-vm/transactional-tests/tests/module_publishing/republish_module_cyclic_dependencies_fn.mvir
language/move-vm/transactional-tests/tests/module_publishing/republish_module_cyclic_dependencies_friend.exp
language/move-vm/transactional-tests/tests/module_publishing/republish_module_cyclic_dependencies_friend.mvir
language/move-vm/transactional-tests/tests/module_publishing/republish_module_cyclic_dependencies_struct.exp
language/move-vm/transactional-tests/tests/module_publishing/republish_module_cyclic_dependencies_struct.mvir
language/move-vm/transactional-tests/tests/module_publishing/republish_module_incompatible_layout_struct.exp
language/move-vm/transactional-tests/tests/module_publishing/republish_module_incompatible_layout_struct.mvir
language/move-vm/transactional-tests/tests/module_publishing/republish_module_skip_compatible_linking.exp
language/move-vm/transactional-tests/tests/module_publishing/republish_module_skip_compatible_linking.mvir
language/move-vm/transactional-tests/tests/module_publishing/republish_module_skip_compatible_linking_hack_struct.exp
language/move-vm/transactional-tests/tests/module_publishing/republish_module_skip_compatible_linking_hack_struct.mvir
language/testing-infra/transactional-test-runner/src/vm_test_harness.rs

1. Add CompatibilityConfig to session API to support custom compat config
2. Add compact relative flags to transactional test `publish` command
3. Add more compact relative tests.
yes

[vm & test] Add CompatibilityConfig to session API to support custom compat config and add more compatible tests

---

language/move-binary-format/src/check_bounds.rs
language/move-vm/transactional-tests/tests/module_publishing/republish_module_skip_compatible_linking_hack_struct.exp

[verifier] Minor hardening against arithmetic overflow

---

language/documentation/book/src/abilities.md

[language/docs]: Fix a bug in in book/ability.

---

language/documentation/tutorial/README.md
language/documentation/tutorial/step_4_sol/BasicCoin/sources/BasicCoin.move

These are some fixes I identified while working through the tutorial, updating command names, compiler output, etc.
Yes.

Minor tutorial fixes

---

language/documentation/book/src/variables.md
language/documentation/book/translations/move-book-zh/src/variables.md

Update variables chapter in move-book-zh and move-book.

[move-book and move-book-zh] update variables

---

language/move-stdlib/docs/bit_vector.md
language/move-stdlib/sources/bit_vector.move

- Fix the mistake in spec
Fix the mistake in spec
yes
cargo test

[Prover] fix the spec of `bit_vector::unset`

---

language/move-binary-format/src/compatibility.rs
language/move-binary-format/src/proptest_types/functions.rs
language/move-bytecode-verifier/src/instruction_consistency.rs

Verifies range of an instruction, as well as corrects an outdated comment.

[vm] Fixes

---

language/extensions/async/move-async-vm/tests/sources/AccountStateMachine.move
language/extensions/async/move-async-vm/tests/sources/Basic.move
language/move-core/types/src/value.rs
language/move-prover/interpreter-testsuite/tests/concrete_check/destroy.move
language/move-prover/interpreter-testsuite/tests/concrete_check/pack_unpack.move
language/move-vm/runtime/src/interpreter.rs
language/move-vm/runtime/src/loader.rs
language/move-vm/runtime/src/move_vm.rs
language/move-vm/runtime/src/runtime.rs
language/move-vm/transactional-tests/tests/entry_points/generic_return_values.move
language/move-vm/types/src/loaded_data/runtime_types.rs
language/move-vm/types/src/values/values_impl.rs

This is a duplicate of #493 . The intention is we will first land this version on Aptos branch while we discuss what would be the right runtime checks to add for main branch.
Yes
`cargo test`

[move-vm] Add strict/paranoid runtime verification

---

language/move-binary-format/src/file_format.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/code_unit_tests.rs

[vm] update outdated comments and add a new test case

---

language/move-core/types/src/vm_status.rs

Trying to add a hard limit on size of items going to persistent storage, and there is no proper status code for that.

add new runtime status code

---

language/move-compiler/src/naming/fake_natives.rs

Fixing a bug in resolving builtins

[compiler] Fix for #544

---

language/documentation/book/src/functions.md
language/documentation/book/translations/move-book-zh/src/abilities.md
language/documentation/book/translations/move-book-zh/src/bool.md
language/documentation/book/translations/move-book-zh/src/functions.md
language/documentation/book/translations/move-book-zh/src/integers.md
language/documentation/book/translations/move-book-zh/src/introduction.md
language/documentation/book/translations/move-book-zh/src/move-tutorial.md
language/documentation/book/translations/move-book-zh/src/references.md
language/documentation/book/translations/move-book-zh/src/tuples.md

This PR works to close out: #465 
Yes

Fix conflict [move-book and move-book-zh] Fix zh translation #465

---

language/move-binary-format/src/compatibility.rs
language/move-binary-format/src/unit_tests/compatibility_tests.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/control_flow_tests.rs
language/move-bytecode-verifier/src/verifier.rs
language/move-vm/integration-tests/src/tests/nested_loop_tests.rs
language/move-vm/runtime/src/runtime.rs
language/move-vm/transactional-tests/tests/module_publishing/republish_module_incompatible_friend_fn_skip_check_friend_linking.exp
language/move-vm/transactional-tests/tests/module_publishing/republish_module_incompatible_friend_fn_skip_check_friend_linking.mvir
language/testing-infra/transactional-test-runner/src/vm_test_harness.rs
language/tools/move-cli/src/sandbox/utils/mod.rs

1. `treat_friend_as_private` as CompatibilityConfig and rename it to `check_friend_linking` as @sblackshear suggestion, because it only affect the module publish Compat verify.
2. Add `--skip-check-friend-linking` flag to the transactional test `publish` command.
3. Add tests for `--skip-check-friend-linking`
Yes
CI

[vm & test] Migrate the treat_friend_as_private to CompatibilityConfig and add tests

---

language/move-compiler/src/naming/fake_natives.rs

Picks #544
The phase in the compiler which maps calls to vector functions to opcodes only catches cases like `std::vector::fun`. If a user has `0x1::vector::fun` (which he should be free to do) no resolution to opcodes happens, and the legacy native functions in the library are called. Those functions, however, should be deactivated as they represent a further surface of concern of security and gas metering.
This PR lets the vector functions resolve to opcodes if either (a) the symbolic address name is `std` (b) or the address resolves to `0x1`.

[compiler] Cherrypick: Resolve 0x1::vector functions to opcodes

---

language/documentation/book/src/integers.md
language/move-compiler/tests/move_check/parser/num_literal_underscore.move
language/move-compiler/tests/move_check/parser/num_literal_underscore_trailing.move

Docs to illustrate new feature, plus some tests
Yes
Standard tests

add documentation for number literal underscores

---

language/tools/move-cli/src/base/disassemble.rs
language/tools/move-cli/tests/build_tests/disassemble_script/Move.toml
language/tools/move-cli/tests/build_tests/disassemble_script/args.exp
language/tools/move-cli/tests/build_tests/disassemble_script/args.txt
language/tools/move-cli/tests/build_tests/disassemble_script/sources/me.move
language/tools/move-package/src/compilation/compiled_package.rs

Fixes https://github.com/move-language/move/issues/492
Yes

Fix disassembler to work with scripts

---

language/move-bytecode-verifier/src/instantiation_loops.rs

[bug fix] Fixed bug with natives in instantiation loop checker (#573)

---

Cargo.lock
Cargo.toml
language/documentation/examples/diem-framework/crates/cli/Cargo.toml
language/documentation/examples/diem-framework/crates/crypto/Cargo.toml
language/extensions/async/move-async-vm/Cargo.toml
language/extensions/move-table-extension/Cargo.toml
language/move-compiler/Cargo.toml
language/move-core/types/Cargo.toml
language/move-ir-compiler/Cargo.toml
language/move-ir-compiler/move-bytecode-source-map/Cargo.toml
language/move-prover/move-abigen/Cargo.toml
language/move-prover/move-errmapgen/Cargo.toml
language/move-vm/types/Cargo.toml
language/tools/move-cli/Cargo.toml
language/tools/move-coverage/Cargo.toml
language/tools/move-explain/Cargo.toml
language/tools/move-package/Cargo.toml
language/tools/move-resource-viewer/Cargo.toml

And use a workspace dep to enforce the same version everywhere.

[deps] update bcs to 1.4

---

language/move-borrow-graph/src/graph.rs
language/move-borrow-graph/src/references.rs
language/move-borrow-graph/src/shared.rs
language/move-bytecode-verifier/src/reference_safety/abstract_state.rs
language/move-bytecode-verifier/src/regression_tests/mod.rs
language/move-bytecode-verifier/src/regression_tests/reference_analysis.rs

[vm] Improve borrow graph updates efficiency

---

language/move-borrow-graph/src/graph.rs
language/move-borrow-graph/src/references.rs
language/move-borrow-graph/src/shared.rs
language/move-bytecode-verifier/src/reference_safety/abstract_state.rs
language/move-bytecode-verifier/src/regression_tests/mod.rs
language/move-bytecode-verifier/src/regression_tests/reference_analysis.rs
language/move-stdlib/docs/fixed_point32.md
language/move-stdlib/sources/fixed_point32.move

[vm] Cherry picking #584 and #582

---

language/move-model/src/builder/module_builder.rs
language/move-prover/tests/sources/functional/loop_inv.move

Solve #473 
Yes
A new test is added 
cargo test

[move-prover] Check existence of spec_id in fun_spec_info

---

Cargo.lock
Cargo.toml
devtools/x-lint/src/runner.rs
language/move-binary-format/Cargo.toml
language/move-binary-format/src/check_bounds.rs
language/move-binary-format/src/file_format.rs
language/move-bytecode-verifier/fuzz/.gitignore
language/move-bytecode-verifier/fuzz/Cargo.toml
language/move-bytecode-verifier/fuzz/README.md
language/move-bytecode-verifier/fuzz/fuzz_targets/code_unit.rs
language/move-bytecode-verifier/fuzz/fuzz_targets/compiled_module.rs
language/move-bytecode-verifier/fuzz/fuzz_targets/mixed.rs
language/move-bytecode-verifier/src/regression_tests/reference_analysis.rs
language/move-bytecode-verifier/transactional-tests/tests/check_bounds/128_params_and_128_locals.exp
language/move-bytecode-verifier/transactional-tests/tests/check_bounds/128_params_and_128_locals.mvir
language/move-bytecode-verifier/transactional-tests/tests/check_bounds/1_param_and_255_locals.exp
language/move-bytecode-verifier/transactional-tests/tests/check_bounds/1_param_and_255_locals.mvir
language/move-core/types/Cargo.toml
language/move-core/types/src/account_address.rs
language/move-core/types/src/identifier.rs
language/move-core/types/src/metadata.rs
language/move-core/types/src/vm_status.rs
x.toml

Cherry-picks a few PRs from the aptos branch, specifically the one which adds the fuzzing logic. Also aligns the regression tests for the bytecode verifier.

[cherry-pick] Fuzzing setup & other smaller things

---

language/move-analyzer/editors/code/README.md

Fix a typo in move-analyzer/editors/code.
Yes

[move-analyzer] fix a typo

---

language/move-vm/runtime/src/loader.rs
language/move-vm/runtime/src/move_vm.rs

Adds a public function to discover this from the VM.

[vm] Allow to determine whether the loader cache is invalid

---

language/move-stdlib/nursery/sources/debug.move
language/move-stdlib/src/natives/debug.rs
language/move-stdlib/src/natives/mod.rs

Cherry-picking #603, as instructed by @wrwg.

Cherry picking #603

---

language/move-command-line-common/src/parser.rs
language/move-command-line-common/src/values.rs
language/move-prover/bytecode/src/spec_instrumentation.rs
language/move-prover/move-docgen/src/docgen.rs
language/testing-infra/transactional-test-runner/src/framework.rs

Cherry-picks the most recent PRs which are around tools only. I need the docgen PR to fix an issue with the landing page of the Aptos documentation set (basically that modules from dependent packages are shown, which shouldn't)
#618 (docgen)
#585 (transactional test framework)
#604 (prover)

[aptos] Cherry picks

---

language/move-binary-format/src/compatibility.rs
language/move-binary-format/src/unit_tests/compatibility_tests.rs
language/move-vm/runtime/src/runtime.rs
language/move-vm/runtime/src/session.rs
language/move-vm/transactional-tests/tests/module_publishing/republish_module_incompatible_friend_fn_skip_check_friend_linking_remove.exp
language/move-vm/transactional-tests/tests/module_publishing/republish_module_incompatible_friend_fn_skip_check_friend_linking_remove.mvir
language/move-vm/transactional-tests/tests/module_publishing/republish_module_skip_compatible_linking.mvir
language/move-vm/transactional-tests/tests/module_publishing/republish_module_skip_compatible_linking_hack_struct.mvir
language/testing-infra/transactional-test-runner/src/vm_test_harness.rs
language/tools/move-cli/src/sandbox/utils/mod.rs

Refactoring the `Compatibility` to making the API more reasonable.
* Add `friend_linking` field to `Compatibility` and remove `check_friend_linking` argument for `check` fn.
* `Compatibility::check` to throw Error based on self config.  
Yes
CI

[move-vm] Refactor compatibility

---

language/move-prover/boogie-backend/src/spec_translator.rs
language/move-prover/tests/sources/functional/axiom_generic.move

close #632 
Yes
cargo test, a new test axiom_generic.move is added to validate the fix.

[move-prover] Fix for issue 632 

---

language/documentation/tutorial/README.md

"It should look something like this" implies that the test output shown will include the global state
I have.
The changes in this PR only concern the Move Tutorial.

[move-tutorial] Add global state to test output

---

language/move-binary-format/src/proptest_types/signature.rs
language/move-bytecode-verifier/src/dependencies.rs
language/move-bytecode-verifier/transactional-tests/tests/dependencies/call_integers_valid.exp
language/move-bytecode-verifier/transactional-tests/tests/dependencies/call_integers_valid.move

- Fix missing case in dependency verifier for equality on signature tokens (from different contexts)
- Fix prop test case
- fixing bug in dependency verifier
- new test

[linker][new integer types] Fix missing case in dependency verifier

---

language/tools/move-package/src/resolution/resolution_graph.rs

Tag based git dependencies can't really be updated easily after the initial download, so these will not be updated.  Tags are usually used as releases, and in general shouldn't change after the fact.  This becomes tricky in general in comparison to a branch based flow.  Additionally, added an updating message and cleaned up some duplicate outputs.
Resolves: https://github.com/move-language/move/issues/608
Yes
I tested this manually with a package that wasn't working correctly with this https://github.com/pontem-network/liquidswap
Now, it doesn't crash, it continues on.
Additionally, I tested with a branch based lookup without issue as well as revision based.

[move-package] Don't update tag based git dependencies

---

language/evm/move-to-yul/src/functions.rs
language/move-model/src/ast.rs
language/move-model/src/builder/exp_translator.rs
language/move-prover/boogie-backend/src/boogie_helpers.rs
language/move-prover/boogie-backend/src/bytecode_translator.rs
language/move-prover/boogie-backend/src/spec_translator.rs
language/move-prover/bytecode/src/stackless_bytecode.rs
language/move-prover/bytecode/src/stackless_bytecode_generator.rs
language/move-prover/interpreter/src/concrete/evaluator.rs
language/move-prover/interpreter/src/concrete/player.rs
language/move-prover/tests/sources/functional/consts.exp
language/move-prover/tests/sources/functional/consts.move
language/move-prover/tools/spec-flatten/src/ast_print.rs

Try to resolve #653 in a general way as suggested in #411. Since it is a little bit urgent, this PR is quite rough and a lot things are left unimplemented. Any comments and suggestions are welcomed. 
Yes
cargo test

[move-prover] Add support for multiple types in vectors

---

language/tools/move-bytecode-utils/src/module_cache.rs

Helpful for instrumenting validators.
Yes
```
cargo nextest
```

[EASY][Bytecode] Expose size of Module Cache

---

language/tools/move-package/src/resolution/resolution_graph.rs

tl;dr: Tag based git dependencies don't work when building successive times.
Tag based git dependencies can't really be updated easily after the initial download, so these will not be updated.  Tags are usually used as releases, and in general shouldn't change after the fact.  This becomes tricky in general in comparison to a branch based flow.  Additionally, added an updating message and cleaned up some duplicate outputs.
Yes
Tested via Move CLI
See #662 for more details

[move-package] Cherry-pick: Don't update tag based git dependencies (#662)

---

language/move-vm/transactional-tests/tests/builtins/move_to_and_from_resource_with_primitive_fields.exp
language/move-vm/transactional-tests/tests/builtins/move_to_and_from_resource_with_primitive_fields.move
language/move-vm/types/src/values/values_impl.rs

- Fixed missing serialization case
- Added tests

[move-vm][value-impl] Fix serialization case for vecu16, u32, u256

---

language/move-prover/bytecode/src/borrow_analysis.rs
language/move-prover/bytecode/src/compositional_analysis.rs
language/move-prover/bytecode/src/function_target_pipeline.rs
language/move-prover/doc/user/spec-lang.md
language/move-prover/tests/sources/functional/recursive_move_fun.move

Cherry-picking #661 on adding error message for handling mutually recursive functions and #592 on fixing the prover doc.
Yes
cargo test

[Move-prover] Cherry-picking two minor fixes on the prover

---

Cargo.lock
language/move-core/types/src/language_storage.rs
language/move-core/types/src/value.rs
language/move-stdlib/Cargo.toml
language/move-stdlib/nursery/sources/debug.move
language/move-stdlib/src/natives/debug.rs
language/move-vm/runtime/src/loader.rs
language/move-vm/runtime/src/native_functions.rs
language/move-vm/runtime/src/session.rs
language/move-vm/types/src/loaded_data/runtime_types.rs
language/move-vm/types/src/values/values_impl.rs
language/tools/move-cli/tests/sandbox_tests/print_values/args.exp
language/tools/move-cli/tests/sandbox_tests/print_values/args.txt
language/tools/move-cli/tests/sandbox_tests/print_values/scripts/print_values.move
language/tools/move-cli/tests/sandbox_tests/print_values/sources/M.move

Edited the commits to remove support for u16/u32/u256.

Cherry-picking `std::debug` pretty-printing and annotated `MoveTypeLayout`'s

---

language/documentation/book/src/integers.md

Correct type enumeration typo

---

language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/limit_tests.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
language/move-bytecode-verifier/src/code_unit_verifier.rs
language/move-bytecode-verifier/src/limits.rs
language/move-bytecode-verifier/src/stack_usage_verifier.rs
language/move-bytecode-verifier/src/verifier.rs
language/move-core/types/src/vm_status.rs
language/move-vm/runtime/src/loader.rs

- bound stack during stack balance analysis
- avoid quadratic behavior in name definition mao
- bound type nodes

[vm] Some reliability fixes

---

language/documentation/book/src/introduction.md

Remove dead link to defunct project

---

language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/limit_tests.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/mod.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/vec_pack_tests.rs
language/move-bytecode-verifier/src/stack_usage_verifier.rs
language/move-bytecode-verifier/src/verifier.rs
language/move-core/types/src/vm_status.rs
language/move-vm/integration-tests/src/tests/loader_tests.rs
language/move-vm/runtime/src/loader.rs

- bound the number of allowed dependencies in a module (default 256)
- bound the number of effective stack pushs (default 10,000)

[vm] Cherry-picking multiple fixes for reliability

---

language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/limit_tests.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/mod.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/vec_pack_tests.rs
language/move-bytecode-verifier/src/stack_usage_verifier.rs
language/move-bytecode-verifier/src/verifier.rs
language/move-core/types/src/vm_status.rs
language/move-vm/integration-tests/src/tests/loader_tests.rs
language/move-vm/runtime/src/loader.rs

* add limits to push on stack
* Define limit in the depth of dependencies in a module
Co-authored-by: Teng Zhang <rahxephon89@163.com>
Co-authored-by: Dario Russi <dario@aptoslabs.com>

[vm] Cherry-picking multiple fixes for reliability to main (cherry-pick of #718)

---

language/evm/move-to-yul/src/evm_transformation.rs
language/move-prover/bytecode/src/borrow_analysis.rs
language/move-prover/bytecode/src/clean_and_optimize.rs
language/move-prover/bytecode/src/compositional_analysis.rs
language/move-prover/bytecode/src/data_invariant_instrumentation.rs
language/move-prover/bytecode/src/debug_instrumentation.rs
language/move-prover/bytecode/src/eliminate_imm_refs.rs
language/move-prover/bytecode/src/escape_analysis.rs
language/move-prover/bytecode/src/function_target_pipeline.rs
language/move-prover/bytecode/src/global_invariant_analysis.rs
language/move-prover/bytecode/src/global_invariant_instrumentation.rs
language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
language/move-prover/bytecode/src/inconsistency_check.rs
language/move-prover/bytecode/src/livevar_analysis.rs
language/move-prover/bytecode/src/loop_analysis.rs
language/move-prover/bytecode/src/memory_instrumentation.rs
language/move-prover/bytecode/src/mut_ref_instrumentation.rs
language/move-prover/bytecode/src/mutation_tester.rs
language/move-prover/bytecode/src/packed_types_analysis.rs
language/move-prover/bytecode/src/reaching_def_analysis.rs
language/move-prover/bytecode/src/read_write_set_analysis.rs
language/move-prover/bytecode/src/spec_instrumentation.rs
language/move-prover/bytecode/src/usage_analysis.rs
language/move-prover/bytecode/src/verification_analysis.rs
language/move-prover/bytecode/src/verification_analysis_v2.rs
language/move-prover/bytecode/src/well_formed_instrumentation.rs
language/move-prover/tests/sources/functional/recursive_move_funs_multi_hop.move

This PR is based on #720 and #698. Review of this PR should start from the 3rd commit.
The core change is highlighted below. The rest are API fixes due to this core change.
Fix #667 
Yes
- CI
- The test case in #667 is added

[move-prover] prepare stackless bytecode passes for inter-procedure absint

---

language/move-prover/bytecode/src/borrow_analysis.rs

*(This is the last PR in the stack, the parent PR is #724
Only the last commit belongs to this PR)*
The key idea is to define a join function for the `BorrowAnnotation`
struct. The interprecedual absint for borrow analysis is following:
For all functions in a recursive call group (an SCC in the call graph):
- initially all function have a `BorrowAnnotation::default()` info
- for each function visited, produce a summary of `BorrowAnnotation`
and *join* it with the existing summary (or the `default()` one.)
- if `JoinResult::Unchanged` --> mark this annotation as reaching a
fixedpoint state
- if `JoinResult::Changed` --> mark this annotation as not yet
reaching a fixedpoint.
The borrow analysis will stop when the borrow annotation summary for
all functions in the SCC are marked as reached …

[move-prover] convert borrow analysis with inter-procedural absint

---

language/documentation/book/src/generics.md
language/documentation/book/translations/move-book-zh/src/generics.md

Update generics chapter in move-book and move-book-zh.
Yes

[move-book and move-book-zh] update generics

---

language/move-binary-format/src/normalized.rs

Cherry pick the fix in the normalized.rs from #567 
yes

[move-binary-format] Fix panic in normalized.rs

---

Cargo.lock
language/move-binary-format/src/deserializer.rs
language/move-bytecode-verifier/Cargo.toml
language/move-bytecode-verifier/bytecode-verifier-tests/Cargo.toml
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/catch_unwind.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/mod.rs
language/move-bytecode-verifier/src/verifier.rs
language/move-core/types/src/lib.rs
language/move-core/types/src/state.rs

Commandered the #747. Added testing via failpoint injection.
Yes
With a new test.

[language] Add catch_unwind panic handling

---

language/move-bytecode-verifier/src/verifier.rs
language/move-vm/integration-tests/Cargo.toml
language/move-vm/integration-tests/src/tests/instantiation_tests.rs
language/move-vm/integration-tests/src/tests/mod.rs

Test performance of `Resolver` and `Interpreter` instantiation API.
Value will be tuned according to limits and other implementation details
Yes
This is it

Test for instantiation operation

---

language/move-bytecode-verifier/src/reference_safety/abstract_state.rs
language/move-bytecode-verifier/transactional-tests/tests/reference_safety/borrow_in_loop.exp
language/move-bytecode-verifier/transactional-tests/tests/reference_safety/borrow_in_loop.mvir
language/move-vm/transactional-tests/tests/references/borrow_in_loop.exp
language/move-vm/transactional-tests/tests/references/borrow_in_loop.mvir

Cherry-picking https://github.com/move-language/move/pull/794

Cherry-pick #794 onto aptos-main

---

Cargo.lock
language/move-vm/integration-tests/Cargo.toml
language/move-vm/integration-tests/src/tests/invariant_violation_tests.rs
language/move-vm/integration-tests/src/tests/leak_tests.rs
language/move-vm/integration-tests/src/tests/mod.rs
language/move-vm/runtime/src/interpreter.rs
language/move-vm/types/src/values/values_impl.rs

Cherry pick with some minor changes on format

Cherry-pick onto aptos-main

---

Cargo.lock
language/move-vm/integration-tests/Cargo.toml
language/move-vm/integration-tests/src/tests/invariant_violation_tests.rs
language/move-vm/integration-tests/src/tests/leak_tests.rs
language/move-vm/integration-tests/src/tests/mod.rs
language/move-vm/runtime/src/interpreter.rs
language/move-vm/types/src/values/values_impl.rs

Cherry pick with some minor changes on format

Cherry-pick onto aptos-v1.2.0

---

Cargo.lock
language/move-vm/integration-tests/Cargo.toml
language/move-vm/integration-tests/src/tests/invariant_violation_tests.rs
language/move-vm/integration-tests/src/tests/leak_tests.rs
language/move-vm/integration-tests/src/tests/mod.rs
language/move-vm/runtime/src/interpreter.rs
language/move-vm/types/src/values/values_impl.rs

Cherry pick with some minor changes on format

Cherry-pick onto main

---

Cargo.lock
language/move-binary-format/src/deserializer.rs
language/move-bytecode-verifier/Cargo.toml
language/move-bytecode-verifier/bytecode-verifier-tests/Cargo.toml
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/catch_unwind.rs
language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/mod.rs
language/move-bytecode-verifier/src/verifier.rs
language/move-core/types/src/lib.rs
language/move-core/types/src/state.rs

Co-authored-by: Robert <me@robertchen.cc>
Cherrypicking #747 to aptos-v1.2.0 branch
Yes
See #747

[language] add catch_unwind panic handling (#802)

---

.github/workflows/ci-post-land.yml
.github/workflows/ci-pre-land.yml

Change pre/post for sui branch
yes
testing and verifying after checkin

Allow pre/post workflow to work on sui-move

---

language/move-compiler/src/hlir/translate.rs
language/move-compiler/src/inlining/translate.rs
language/move-compiler/src/inlining/visitor.rs
language/move-compiler/transactional-tests/tests/inlining/multi_param.exp
language/move-compiler/transactional-tests/tests/inlining/multi_param.move

Also add some tests to ensure certain scenarios work.

[inline functions] Fixing a crash caused by wrong scoping in bindings

---

CODEOWNERS

Propose reviewers via codeowners
yes
this is it

Try codeowners in branch

---

language/move-core/types/src/vm_status.rs

Need to limit number of events emitted and return proper error when hit.
See [Sui](https://github.com/MystenLabs/sui/pull/7804/files#diff-a57d208a61286bc8bbc11132d71355b98dab14b3ed4cb045588f0eb9d6e5a182R165) PR
Yes
N/A

add event count limit status code

---

language/move-prover/bytecode/src/mono_analysis.rs

In mono analysis, an implicit assumption is that all types used in the function body will appear either in parameters, locals, return tyupes, or spec exprs.
While this is true and in a rigourous implemention, should hold, it might be hit by a cornor case where an imcomplete (and potentially) inconsistent modeling of borrow natives are in place.
An example is shown in the `dynamic_field::borrow_mut` model:
```move
module sui::dynamic_field {
struct Field<Name: copy + drop + store, Value: store> has key {
id: UID,
name: Name.
value: Value,
}
public fun borrow_mut<Name: copy + drop + store, Value: store>(
object: &mut UID,
name: Name,
): &mut Value {
let object_addr = object::uid_to_address(object);
let hash = hash_type_and_key(object_addr, name);
let field = …
```

[move-prover] collect types in write-back chain for mono analysis

---

CODEOWNERS

Add Rijnard

---

language/move-prover/boogie-backend/src/bytecode_translator.rs
language/move-prover/bytecode/src/number_operation_analysis.rs
language/move-prover/tests/sources/functional/bitwise_features.move

Cherry-pick #878 onto aptos-main

[Move-prover] Cherry-pick #878

---

language/tools/move-package/src/resolution/mod.rs

Another occasion where the previous implementation recursively traversed the transitive dependency graph -- the new approach discovers the graph and then iterates through its nodes to download them.
The second step is currently technically unnecessary, but becomes relevant in the presence of externally resolved dependencies where third-party resolvers can introduce sub-graphs into the `DependencyGraph` without having to explore them locally.
```
move/language/tools/move-package$ cargo nextest
```
- #741 
- #745 
- #753 
- #754 
- #759 
- #760 
- #854 
- #855 
- #856 
- #857 
- #858 
See also: #788 for main.

sui-move: [12/x][move-package/lock] Use DependencyGraph in download_dependency_repos

---

language/move-model/src/pragmas.rs
language/move-prover/boogie-backend/src/lib.rs
language/move-prover/boogie-backend/src/prelude/native.bpl
language/move-prover/boogie-backend/src/prelude/table-array-theory.bpl
language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
language/move-prover/tests/sources/functional/verify_custom_table.exp
language/move-prover/tests/sources/functional/verify_custom_table.move
language/move-stdlib/docs/fixed_point32.md
language/move-stdlib/sources/fixed_point32.move

This is to cherry-pick two commits landed in main from PR #899.

[cherry-pick][prover] table intrinsic

---

language/tools/move-unit-test/Cargo.toml

Make debugger feature an option for the unit test crate.
Yes
Manually run the test by setting the `MOVE_VM_TRACE`  env variable to make sure tracing is indeed enabled

[move-unit-test] Enable debugger for unit test

---

language/move-prover/boogie-backend/src/bytecode_translator.rs
language/move-prover/tests/sources/functional/bitwise_features.move

[Cherry-pick][Move-prover] Bug fix & add new specs to the prover test

---

Cargo.lock
language/move-compiler/src/command_line/compiler.rs
language/move-compiler/src/interface_generator.rs
language/move-prover/boogie-backend/Cargo.toml
language/move-prover/boogie-backend/src/bytecode_translator.rs
language/tools/move-cli/tests/build_tests/build_with_bytecode/B/Move.toml
language/tools/move-cli/tests/build_tests/build_with_bytecode/B/sources/Bar.move
language/tools/move-cli/tests/build_tests/build_with_bytecode/C/Move.toml
language/tools/move-cli/tests/build_tests/build_with_bytecode/C/sources/Foo.move
language/tools/move-cli/tests/build_tests/build_with_bytecode/Move.toml
language/tools/move-cli/tests/build_tests/build_with_bytecode/args.exp
language/tools/move-cli/tests/build_tests/build_with_bytecode/args.txt
language/tools/move-cli/tests/build_tests/build_with_bytecode/sources/A.move
language/tools/move-package/src/compilation/build_plan.rs
language/tools/move-package/src/compilation/compiled_package.rs
language/tools/move-package/src/compilation/model_builder.rs
language/tools/move-package/src/resolution/resolution_graph.rs

Cherry-pick #865 onto `main`
Yes

[Cherry-pick][Move-package] Enable bytecode as dependencies

---

language/move-prover/boogie-backend/src/lib.rs

Close the issue [here](https://github.com/aptos-labs/aptos-core/issues/6723).

[Move-prover] Fix duplicated table function instances in boogie

---

language/move-prover/boogie-backend/src/lib.rs

[Move-prover][Cherry-pick] Fix duplicated table function instances in boogie

---

language/extensions/move-table-extension/src/lib.rs

[table] clean up unused enum

---

language/extensions/move-table-extension/src/lib.rs

cherry-picking https://github.com/move-language/move/pull/925
Y
n/a

[cherry-pick][table] clean up unused enum

---

language/move-prover/boogie-backend/src/bytecode_translator.rs
language/move-prover/boogie-backend/src/lib.rs
language/move-prover/bytecode/src/number_operation_analysis.rs
language/move-prover/tests/sources/functional/bitwise_features.move

This PR is a consolidation of recent fixes on the prover side, including:
- #878: add support for insert
- #905: bug fixes related for bitvec ops
- #924: fix a bug on type instantiation on boogie side

[cherry-pick] various small fixes for prover

---

language/move-stdlib/docs/option.md
language/move-stdlib/sources/option.move

Revise the spec for `borrow_mut` in `option.move`.

[Move-prover] Revise spec for option.move

---

language/move-stdlib/docs/option.md
language/move-stdlib/sources/option.move

[Move-prover][Cherry-pick] Revise spec for option.move

---

language/extensions/move-table-extension/src/lib.rs
language/move-core/types/src/gas_algebra.rs
language/move-core/types/src/vm_status.rs
language/move-stdlib/src/natives/bcs.rs
language/move-stdlib/src/natives/event.rs
language/move-stdlib/src/natives/hash.rs
language/move-stdlib/src/natives/signer.rs
language/move-stdlib/src/natives/string.rs
language/move-stdlib/src/natives/type_name.rs
language/move-stdlib/src/natives/unit_test.rs
language/move-stdlib/src/natives/vector.rs
language/move-vm/runtime/src/interpreter.rs
language/move-vm/runtime/src/native_functions.rs
language/move-vm/test-utils/src/gas_schedule.rs
language/move-vm/types/src/gas.rs

This PR sets the budget for native function and breaks down charging to ensure the native functions don't do work which the client cannot afford.
Yes
N/A

Charge native inline within budget

---

language/move-core/types/src/vm_status.rs

These new status codes will be used as part of multisig transaction prologue: https://github.com/aptos-labs/aptos-core/pull/5894

Multisig error codes

---

language/move-binary-format/src/errors.rs
language/move-core/types/src/unit_tests/vm_status_test.rs
language/move-core/types/src/vm_status.rs
language/tools/move-cli/src/sandbox/utils/mod.rs

Reverts move-language/move#948

Rollforward "[vm errors] Propagate status message to adapters"

---

language/move-vm/runtime/src/native_functions.rs

give necessary information for charging effectively for exists_at

---

language/documentation/book/src/generics.md

Replace HTML link in Move Book Generics file with Markdown

---

language/documentation/book/src/standard-library.md

Fix misspelling of encountered in Move Book standard library file

---

language/move-binary-format/src/errors.rs
language/move-core/types/src/unit_tests/vm_status_test.rs
language/move-core/types/src/vm_status.rs
language/tools/move-cli/src/sandbox/utils/mod.rs

Rolls forward #936 which needed to be rolled back.

[vm errors] Propagate status message 2nd try

---

language/extensions/move-table-extension/src/lib.rs
language/move-stdlib/src/natives/bcs.rs
language/move-stdlib/src/natives/event.rs
language/move-stdlib/src/natives/hash.rs
language/move-stdlib/src/natives/signer.rs
language/move-stdlib/src/natives/string.rs
language/move-stdlib/src/natives/type_name.rs
language/move-stdlib/src/natives/unit_test.rs
language/move-stdlib/src/natives/vector.rs
language/move-vm/runtime/src/native_functions.rs

Simplifies the macro and number of variables used
Yes
Existing tests

simplify natives charging function

---

language/move-vm/integration-tests/src/tests/loader_tests.rs
language/move-vm/runtime/src/loader.rs

...not during `publish`.  During `publish` we can end up verifying a to-be-published module's dependencies without them being loaded if they exist in the same bundle that is currently being published.
In that case, we don't want to mark the module as having its dependencies verified because that will prevent us from traversing (and actually loading into the compiled module cache) the dependencies when we are loading the module itself.
This manifests as a `MISSING_DEPENDENCY` error from the loader.
New tests for the loader, exercising the bundle publish flow:
```
$ cargo nextest -- loader_tests::publish_bundle
```

[BUGFIX][loader] Only add module to verified_dependencies on load

---

language/move-vm/runtime/src/loader.rs

Consolidate rollback and searching through structs and functions for the module currently being loaded, in preparation for supporting canonicalizing structs in the loader.
Existing tests -- these are all behaviour preserving refactorings.

[loader] Clean-ups

---

language/move-vm/runtime/src/loader.rs

Turns out that we already double insert into the loader: when two requests to load a module come in at the same time, both will find the loaded and compiled module caches empty, so both will start the process of verifying the module and insert it.  The last write wins, and the older write's `binaries` entry leaks.
Removing the invariant violation check, and accepting that we will sometimes leak entries as the alternative is to hold the lock for longer in the critical path, which will be too detrimental for performance.
```
$ cargo nextest
```
+ Run the Sui-specific stress-test benchmark that uncovered this issue.

[loader] Remove double-insertion invariant violation

---

language/testing-infra/transactional-test-runner/src/framework.rs
language/testing-infra/transactional-test-runner/src/vm_test_harness.rs
language/testing-infra/transactional-test-runner/tests/vm_test_harness/multiple_modules.exp
language/testing-infra/transactional-test-runner/tests/vm_test_harness/multiple_modules.move

- This probably should have been done a while ago...
- Will be used for PT testing of publish and upgrade
- One new tests, existing tests are not broken

[transactional tests] Support multi module publishing

---

language/move-prover/tests/sources/functional/nested_loop_inv.move

Added a nested loop invariant example as a test case
demo a nested loop inv
yes
cargo test

[Prover] Added a nested loop invariant example

---

language/move-core/types/src/parser.rs

Updates struct tag parsing to be a bit more general

Update to struct tag parsing

---

Cargo.lock
language/move-binary-format/serializer-tests/Cargo.toml
language/move-binary-format/serializer-tests/tests/serializer_tests.rs
language/move-binary-format/src/check_bounds.rs
language/move-binary-format/src/file_format.rs
language/move-binary-format/src/unit_tests/binary_tests.rs
language/move-bytecode-verifier/src/regression_tests/reference_analysis.rs
language/move-vm/integration-tests/src/compiler.rs
language/move-vm/integration-tests/src/tests/mod.rs
language/move-vm/integration-tests/src/tests/regression_tests.rs
language/move-vm/runtime/src/config.rs
language/move-vm/runtime/src/interpreter.rs
language/move-vm/runtime/src/loader.rs
language/move-vm/runtime/src/runtime.rs
language/move-vm/types/src/values/value_tests.rs
language/move-vm/types/src/values/values_impl.rs

Cherry-picking the recent hotfixes

Cherry-picking the recent hotfixes

---

Cargo.lock
language/move-binary-format/Cargo.toml
language/move-binary-format/src/control_flow_graph.rs
language/move-bytecode-verifier/src/absint.rs
language/move-bytecode-verifier/transactional-tests/tests/control_flow/block_traversal_order_alias.exp
language/move-bytecode-verifier/transactional-tests/tests/control_flow/block_traversal_order_alias.mvir
language/move-bytecode-verifier/transactional-tests/tests/control_flow/block_traversal_order_hot_potato.exp
language/move-bytecode-verifier/transactional-tests/tests/control_flow/block_traversal_order_hot_potato.mvir

Cherry-picking the most recent fix

[bytecote verifier] fix the abstract interpreter bypass bug
