- language/move-core/types/src/account_address.rs
- language/tools/move-package/tests/test_sources/parsing/invalid_non_hex_address/Move.exp
- language/tools/move-package/tests/test_sources/parsing/invalid_non_hex_address/Move.toml
Accepts 0x as an input, and will print the output as a 0x for AccountAddress.
This removes confusion on whether it's in a different encoding, and keeps
it simple.
Addresses should start with a `0x` as I have been described by Todd how a hex literal must have `0x` in front of it.  Otherwise, we're being inconsistent and having `0x` in code, but no `0x` outside of it for the same representation.
Updated version from: https://github.com/diem/move/pull/199
> [account-address] Input and output with a 0x for hex output

- language/evm/hardhat-examples/contracts/ERC721ReceiverMock.sol
- language/evm/hardhat-examples/contracts/ExternalCall/Move.toml
- language/evm/hardhat-examples/contracts/ExternalCall/sources/ExternalCall.move
- language/evm/hardhat-examples/contracts/Native.sol
- language/evm/hardhat-examples/contracts/Native/sources/Native.move
- language/evm/hardhat-examples/package-lock.json
- language/evm/hardhat-examples/test/ExternalCall.test.js
- language/evm/hardhat-examples/test/Native.test.js
- language/evm/move-to-yul/src/native_functions.rs
- language/evm/stdlib/sources/Evm.move
This commit:
- implements the `isContract` function by implementing the `Evm::extcodesize` native function.
- adds minimal test cases to reproduce the following two bugs in handling external calls
- https://github.com/move-language/move/issues/30
- https://github.com/move-language/move/issues/31
To implement `isContract`, and add test cases for external calls
yes
npx hardhat test
> [evm] Implements `isContract`, and more test cases for external calls

- language/extensions/move-table-extension/sources/Table.move
- language/extensions/move-table-extension/src/lib.rs
- language/extensions/move-table-extension/tests/TableTests.move
- language/move-vm/test-utils/src/storage.rs
1. manage the size from Move, instead of the extention. This way, the storage doesn't need to store a metadata item for the table.
2. fix issues with items created and removed in the same session before hitting storage.
y
unitests in Move
> [table] adjustments

- language/evm/hardhat-move/src/index.ts
- language/tools/move-cli/tests/build_tests/include_exclude_stdlib/args.evm.exp
- language/tools/move-package/src/compilation/build_plan.rs
This fixes the issue that `move package build` does not print out compiler errors (#29 ). This fix also includes the hardhat plugin.
Before
```
COMPILING EvmStdlib, ExternalCall, MoveStdlib to Yul
Error: exiting with Move build errors
```
After
```
COMPILING EvmStdlib, ExternalCall, MoveStdlib to Yul
ERROR Failed to compile Move into Yul
error: unexpected token
┌─ ./sources/ExternalCall.move:58:2
│
58 │  xx
│  ^^ Invalid code unit. Expected 'address', 'module', or 'script'. Got 'xx'
Error: exiting with Move build errors
```
resolves #29
> [evm] fix the issue that move package build does not print out compiler errors

- .github/workflows/ci-test.yml
- devtools/x/src/lint/license.rs
- scripts/check_pr.sh
Running on head commit increases the chance that CI run passes standalone but fails once the changes are merged.
We had already the first case where head commit lead to a broken test state after merge (fixed in #21). 
Also removes checking out all branches because that seems to be not needed in the Move repo.
> [ci] Run CI on merge commit instead of head commit

- language/tools/move-cli/README.md
- language/tools/move-cli/src/package/cli.rs
This is a pure DevEx change.
Move CLI is the main tool for the most developers starting with Move, and so is the standard library. While writing a Move tutorial I discovered that developers need to manually install (first they have to find - already a challenge) Standard library so they can work with Signers or Vectors or a Debug. 
Another reason to add both `[addresses]` and `[dependencies]` sections to the default manifest is to showcase its features given the lack of easily-accessible documentation. 
This PR does not introduce new logic nor does it change anything except the `Move.toml` template.
> [move-cli] Include stdlib in Move.toml

- language/tools/move-disassembler/src/disassembler.rs
Fixed the bug mentioned in #46.
Basically, `struct_type_info()` shouldn't use the source map of the struct. Instead, it should use the source map of the enclosing function.
For example,
```rust
address 0x1 {
module Foo {
struct S<A: copy + store + drop, B: copy + store + drop> has key, drop { fa: A, fb: B }
fun foo<X: copy+drop+store, Y: copy+drop+store>(x: X, y: Y): S<Y, X> {
S { fa: y, fb: x }  // PackGeneric instruction has signature [1,0]
}
}
}
```
Here the [1 and 0] actually refer to [Y and X], not [B and A].
Current implementation will generate `PackGeneric[0](S<B, A>)`, which is wrong.
This PR fix this and now the disassembled instruction will be `PackGeneric[0](S<Y, X>)`.
This is also the reason of the out-of-bound error mentioned in #46, where the enclosing function contains more …
> Fix the bug that move-disassemble using wrong type_param_context

- .github/workflows/ci-test.yml
- language/evm/hardhat-examples/contracts/ERC1155Mock/Move.toml
- language/evm/hardhat-examples/contracts/ERC1155Mock/sources/ERC1155Mock.move
- language/evm/hardhat-examples/contracts/ERC1155Mock_Sol.sol
- language/evm/hardhat-examples/contracts/ERC721Mock/Move.toml
- language/evm/hardhat-examples/contracts/ERC721Mock/sources/ERC721Mock.move
- language/evm/hardhat-examples/contracts/ERC721Mock_Sol.sol
- language/evm/hardhat-examples/contracts/ERC721ReceiverMock.sol
- language/evm/hardhat-examples/test/ERC1155.behavior.js
- language/evm/hardhat-examples/test/ERC1155.test.js
- language/evm/hardhat-examples/test/ERC1155_Sol.test.js
- language/evm/hardhat-examples/test/ERC721.behavior.js
- language/evm/hardhat-examples/test/ERC721.test.js
- language/evm/hardhat-examples/test/ERC721_Sol.test.js
- language/evm/hardhat-examples/test/SupportsInterface.behavior.js
- Added the Move contracts ERC721Mock and ERC1155Mock
- Added the Solidity contracts ERC721Mock_Sol and ERC1155Mock_Sol
- Checked that they all passed the OpenZeppelin testsuite
To add NFT contracts in Move
yes
npx hardhat test
> [evm] Added ERC721 and ERC1155 Move contracts to the hardhat project

- .github/workflows/ci-test.yml
- language/tools/move-cli/Cargo.toml
- language/tools/move-package/Cargo.toml
- language/tools/move-package/src/compilation/build_plan.rs
- language/tools/move-package/src/lib.rs
- language/tools/move-unit-test/Cargo.toml
- language/tools/move-unit-test/src/test_reporter.rs
- x.toml
This makes the EVM features non-default so that one doesn't have to install the ethereum toolchain if one doesn't need it. A few CI tests are added to ensure these features don'e get broken.
This also renames the `evm-arch` feature to `evm-backend`, just to make it consistent with what we use in other crates.
> [evm] make evm features non-default

- Cargo.lock
- Cargo.toml
- language/move-core/types/src/value.rs
- language/tools/move-resource-viewer/Cargo.toml
- language/tools/move-resource-viewer/src/lib.rs
- language/tools/move-resource-viewer/src/resolver.rs
Expose MoveTypeLayout from the MoveValueAnnotaor. This can be got elsewhere, but the callsite I'm focusing on has this annotator, and it'll be nice if the cache inside can be leveraged.
Y
https://github.com/aptos-labs/aptos-core/pull/568 introduced unit tests to utilize this.
> MoveValueAnnotator: get_type_layout_*

- language/move-core/types/src/value.rs
Get a `Runtime` flavor of the same type, which can be serialized into
the runtime representation.
Y
used here to serialize a struct from json to bcs runtime representation:
https://github.com/aptos-labs/aptos-core/pull/568/commits/c7a8e7a198e5c56a904886d79103bf0156da951a
> MoveValue::undecorate

- language/move-compiler/src/command_line/compiler.rs
- language/move-compiler/src/expansion/translate.rs
- language/testing-infra/transactional-test-runner/src/framework.rs
- language/testing-infra/transactional-test-runner/src/vm_test_harness.rs
- Used source files instead of interface files for source language tests
- Very marginal perf improvement for transactional tests
- Package manager was recently changed to use source files instead of interface files. This change wasn't reflected in the transactional test runner (will still need to be done for the CLI too)
- Ran em
> [transactional-tests] Use source files properly

- language/move-analyzer/editors/code/README.md
- language/move-analyzer/editors/code/package-lock.json
- language/move-analyzer/editors/code/package.json
This gets updates the descriptions of move-analyzer and bumps the version number to 0.0.6. More specifically, this removes the references to Diem and updates the links. Once this gets committed I'll make a push to the vscode marketplace.
> [move-analyzer] update descriptions

- Cargo.lock
- language/move-binary-format/Cargo.toml
- language/move-core/types/Cargo.toml
- language/tools/read-write-set/types/Cargo.toml
Bump the version for `move-core-types` to 0.0.4. The reason is following: all crates in the old `diem` repo still has a dependency on `move-core-types` at 0.0.3. We need to bump the version in the crate in order to not get a conflict dependency.
Yes
`cargo check`
> [move-core-types] Upgrade the version of move-core-types to 0.0.4

- language/move-core/types/src/account_address.rs
- language/tools/move-package/src/source_package/manifest_parser.rs
Error message is non-descriptive.
Yes
Tests pass
> [move-core-types] [move-package] Make manifest address parsing error more descriptive

- Cargo.lock
- language/move-binary-format/Cargo.toml
- language/move-binary-format/src/access.rs
- language/move-binary-format/src/file_format.rs
- language/move-binary-format/src/lib.rs
- language/move-binary-format/src/proptest_types/functions.rs
- language/move-binary-format/src/serializer.rs
- language/move-borrow-graph/Cargo.toml
- language/move-borrow-graph/src/graph.rs
- language/move-bytecode-verifier/Cargo.toml
- language/move-bytecode-verifier/src/locals_safety/abstract_state.rs
- language/move-bytecode-verifier/src/locals_safety/mod.rs
- language/move-bytecode-verifier/src/reference_safety/abstract_state.rs
- language/move-bytecode-verifier/src/reference_safety/mod.rs
- language/move-bytecode-verifier/src/type_safety.rs
- language/move-core/types/Cargo.toml
- language/move-core/types/src/gas_schedule.rs
- language/move-vm/runtime/Cargo.toml
- language/move-vm/runtime/src/lib.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/types/Cargo.toml
- language/move-vm/types/src/gas_schedule.rs
- language/testing-infra/test-generation/Cargo.toml
- language/testing-infra/test-generation/src/abstract_state.rs
- language/testing-infra/test-generation/src/borrow_graph.rs
- language/testing-infra/test-generation/src/bytecode_generator.rs
- language/testing-infra/test-generation/src/control_flow_graph.rs
- language/testing-infra/test-generation/src/lib.rs
- mirai is not being run. Replaced the annotations with the corresponding assert/debug_assert
- The mirai-only annotations are now debug_asserts, because why not
> [chore] Replace mirai annotations with normal asserts

- language/move-core/types/src/language_storage.rs
- language/move-core/types/src/unit_tests/language_storage_test.rs
Add an alias to StructTag for compatibility with old serialized json.
When the TypeTag add serde(rename = "u8"), this break the compatibility with old version, so add a alias = "U8" for compatibility.
I try to fix this in https://github.com/diem/move/pull/106, but I find it fixed by https://github.com/diem/move/pull/127, so I closed my PR.
```
#[serde(rename(serialize = "u8", deserialize = "U8"))]
U8,
```
But I find it was changed back to lowercase in https://github.com/diem/move/pull/153.
I think the right approach to keep compatibility is to add the `alias` other than adding the `deserialize`.
@areshand please help to review this.
Yes
(Share your test plan here. If you changed code, please provide us with clear …
> [type] Add alias to StructTag for compatibility with old serialized json

- language/move-vm/runtime/src/native_functions.rs
I want to be able to obtain type information at run time from a Type.
> [runtime] add type_to_type_tag support for native functions

- language/move-compiler/src/cfgir/constant_fold.rs
- language/move-compiler/tests/move_check/folding/non_constant_empty_vec.move
- language/move-compiler/transactional-tests/tests/constants/non_constant_empty_vec.exp
- language/move-compiler/transactional-tests/tests/constants/non_constant_empty_vec.move
- language/move-vm/runtime/src/runtime.rs
- language/move-vm/transactional-tests/tests/entry_points/generic_return_values.exp
- language/move-vm/transactional-tests/tests/entry_points/generic_return_values.move
- Fixed the compiler making empty vectors constants even if they had an invalid type for constants
- Fixed the vm runtime not substituting type arguments
- Fixing a bug @lxfind found
- Sorry for lumping in the VM fix in this PR too, but it is relatively small 
- new tests
> [move-compiler] Fix empty vector constants. [move-vm] Fix function return types

- devtools/x/src/main.rs
- language/evm/move-to-yul/Cargo.toml
- language/evm/move-to-yul/src/options.rs
- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-compiler/Cargo.toml
- language/move-compiler/src/bin/move-build.rs
- language/move-compiler/src/bin/move-check.rs
- language/move-ir-compiler/Cargo.toml
- language/move-ir-compiler/src/main.rs
- language/move-prover/tools/spec-flatten/Cargo.toml
- language/move-prover/tools/spec-flatten/src/lib.rs
- language/testing-infra/test-generation/Cargo.toml
- language/testing-infra/test-generation/src/config.rs
- language/tools/move-bytecode-viewer/Cargo.toml
- language/tools/move-bytecode-viewer/src/lib.rs
- language/tools/move-cli/src/lib.rs
- language/tools/move-coverage/src/bin/coverage-summaries.rs
- language/tools/move-coverage/src/bin/move-trace-conversion.rs
- language/tools/move-coverage/src/bin/source-coverage.rs
- language/tools/move-disassembler/Cargo.toml
- language/tools/move-disassembler/src/main.rs
- language/tools/move-explain/Cargo.toml
- language/tools/move-explain/src/main.rs
- language/tools/move-package/Cargo.toml
- language/tools/move-package/src/lib.rs
- language/tools/move-unit-test/Cargo.toml
- language/tools/move-unit-test/src/lib.rs
I wanted to provide `--version` switches for some of the tools. However, I noticed that almost none of the tools implemented that switch. Also, "clap" usage was inconsistent across the tools. So, ended up updating Cargo.toml for each of the tools, and simplified the "clap" usage for these tools.
When Move returns to versioned releases, the tools are now ready to communicate that information to the user :+1: 
The main commit:
```
[language] Idiomatic "clap" usage in CLI tools
Following the "clap" documentation on basic "clap" usage (fetching
the information from Cargo.toml). Now "clap" usage is (mostly)
consistent across the tools, the only exceptions being
move-compiler's move-check tool, and move-coverage's
coverage-summaries, move-trace-conversion and source-coverage. These
tools do not …
```
> Idiomatic "clap" usage (implements --version switch for tools)

- language/tools/move-cli/src/sandbox/commands/test.rs
- language/tools/move-cli/tests/build_tests/rebuild_after_adding_new_source/Move.toml
- language/tools/move-cli/tests/build_tests/rebuild_after_adding_new_source/args.evm.exp
- language/tools/move-cli/tests/build_tests/rebuild_after_adding_new_source/args.evm.txt
- language/tools/move-cli/tests/build_tests/rebuild_after_adding_new_source/sources/Foo.move
- language/tools/move-cli/tests/build_tests/rebuild_after_deleting_output_artifact/Move.toml
- language/tools/move-cli/tests/build_tests/rebuild_after_deleting_output_artifact/args.evm.exp
- language/tools/move-cli/tests/build_tests/rebuild_after_deleting_output_artifact/args.evm.txt
- language/tools/move-cli/tests/build_tests/rebuild_after_deleting_output_artifact/sources/Foo.move
- language/tools/move-cli/tests/build_tests/rebuild_after_touching_manifest/Move.toml
- language/tools/move-cli/tests/build_tests/rebuild_after_touching_manifest/args.evm.exp
- language/tools/move-cli/tests/build_tests/rebuild_after_touching_manifest/args.evm.txt
- language/tools/move-cli/tests/build_tests/rebuild_after_touching_manifest/sources/Foo.move
- language/tools/move-cli/tests/build_tests/rebuild_after_touching_source/Move.toml
- language/tools/move-cli/tests/build_tests/rebuild_after_touching_source/args.evm.exp
- language/tools/move-cli/tests/build_tests/rebuild_after_touching_source/args.evm.txt
- language/tools/move-cli/tests/build_tests/rebuild_after_touching_source/sources/Foo.move
- language/tools/move-cli/tests/build_tests/rebuild_no_modification/Move.toml
- language/tools/move-cli/tests/build_tests/rebuild_no_modification/args.evm.exp
- language/tools/move-cli/tests/build_tests/rebuild_no_modification/args.evm.txt
- language/tools/move-cli/tests/build_tests/rebuild_no_modification/sources/Foo.move
- language/tools/move-package/src/compilation/build_plan.rs
- language/tools/move-package/src/lib.rs
This implements some basic caching mechanism for `move package build --arch ethereum`. Recompilation will only be triggered when any of the following conditions is met:
1. Any of the sources has been modified, or more precisely, has a modification time later than those of the outputs
2. Any expected output file is missing
Tests have been added to ensure the conditions above are coded correctly. To support these new tests, this PR also extends `move-cli` so that it recognizes external commands in `args.txt`:
```
> touch Move.toml
```
It should be noted that this is a rather primitive design, which we may want to revisit in the future. Some possible improvements I can think of:
1. Fingerprints/hashes/build_info.json
a. https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/fi …
> [move package] rebuild only if sources have been modified or outputs are missing or outdated

- language/tools/move-package/src/compilation/build_plan.rs
With this change, `move package build --arch ethereum` now removes the `build/evm` directory before generating the new artifacts. Fixes https://github.com/move-language/move/issues/47.
> [evm][move package] remove build dir before starting a new build

- language/tools/move-cli/src/package/cli.rs
- language/tools/move-package/src/lib.rs
Previously, the `--arch ethereum` option is only present when feature `evm-backend` is enabled, which ended up causing some confusion. This PR makes the option always available, but return an error if `evm-backend` isn't enabled when  invoked.
> [evm][move package] make `--arch ethereum` present in all builds, but return an error if feature `evm-backend` isn't enabled

- language/move-compiler/src/expansion/aliases.rs
- language/move-compiler/src/expansion/translate.rs
- language/move-compiler/tests/move_check/naming/friend_decl_self.exp
This is a fix for a problem described in https://github.com/move-language/move/issues/84. In short, we want to preserve locations of identifiers that are aliases to modules or module-level definitions. It fixes the problem more generally (e.g., also for `Pack` and other AST nodes).
Yes
> [compiler] Added support for preserving locations of aliased identifiers

- language/move-prover/tests/sources/functional/nonlinear_arithm.exp
- language/move-prover/tests/sources/functional/nonlinear_arithm.move
The u128 `nonlinear_arithemtics` tests failed for me non-deterministically on a smaller MacBook Air (16G of memory). Disabling those tests to avoid flakes.
> [move-prover] Disable prover test which fails on smaller machines.

- language/documentation/spec/vm.md
Copying over the existing VM spec from the old repo. This makes no attempt to update it with changes since it was originally written (e.g. new bytecode instructions), but it is useful to have here nonetheless.
> [doc] add VM spec

- language/extensions/async/move-async-vm/src/natives.rs
- language/move-compiler/src/diagnostics/codes.rs
- language/move-compiler/src/naming/fake_natives.rs
- language/move-compiler/src/naming/mod.rs
- language/move-compiler/src/naming/translate.rs
- language/move-compiler/src/shared/mod.rs
- language/move-compiler/src/to_bytecode/translate.rs
- language/move-compiler/src/unit_test/filter_test_members.rs
- language/move-model/src/model.rs
- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/stackless_bytecode_generator.rs
- language/move-stdlib/docs/ASCII.md
- language/move-stdlib/docs/BitVector.md
- language/move-stdlib/nursery/docs/Compare.md
- language/move-stdlib/sources/Vector.move
- language/move-stdlib/src/natives/mod.rs
- language/move-vm/runtime/src/native_functions.rs
- language/tools/move-cli/tests/sandbox_tests/explain_stdlib_abort/args.exp
- language/tools/move-cli/tests/sandbox_tests/print_stack_trace/args.exp
- language/tools/move-unit-test/tests/test_sources/native_abort.exp
- Add annotation for native functions that are bytecode instructions
- Add compiler support for swapping those annotated functions to known bytecode instructions
- Used source files instead of interface files for source language tests
- Stopped interface files from shadowing fully compiled deps
- The native bytecode operations have been there for a while, but have been unused 
- Existing tests, just swapping out behavior
> [move-compiler][move-stdlib] Switch to vector bytecode instructions     

- language/extensions/move-table-extension/tests/move_unit_tests.rs
- language/move-stdlib/tests/VectorTests.move
- language/move-stdlib/tests/move_unit_test.rs
- language/tools/move-cli/src/package/cli.rs
Our logic to embed Move unit tests in a Rust test was systematically broken. When a Move unit test fails, the Rust test still succeeds. This lead to failing Move tests slipping through CI.
This PR fixes the unit testing logic. As a result, some unit tests which where already failing at main had to be temporarily disabled. See also issue #124.
> [unit-tests] Make failing Move unit tests fail embedding Rust tests

- language/move-stdlib/tests/VectorTests.move
- language/tools/move-unit-test/src/test_runner.rs
- language/tools/move-unit-test/tests/test_sources/native_abort.exp
- Fixed vector tests failing, re-enabled tests
- The tests exited with VECTOR_OPERATION_ERROR instead of ABORTED
- We should be able to specify the difference in the future
#124
- re-enabled tests
> [move-stdlib] Fix vector tests

- .github/PULL_REQUEST_TEMPLATE.md
Anchor "#pull-requests" does not exist anymore in CONTRIBUTING.md.
Changed the link in the PR Template  to point to "#developer-workflow"
which does exists, and contains basically the same stuff
"#pull-requests" used to contain.
The ["Developer Workflow"](https://github.com/move-language/move/blob/8625c747b35050f42cd30e94984d88b602ca004a/CONTRIBUTING.md#developer-workflow) chapter contains the same stuff ["Pull Requests"](https://github.com/move-language/move/blob/5e034dde19a5320d7e2bdc9da25114e816b4454d/CONTRIBUTING.md#pull-requests) chapter used to contain.
Yes :wink: 
Documentational: no testing needed (checked the link with a browser, though).
> [github] Fixed the link anchor to CONTRIBUTING.md

- language/extensions/async/move-async-vm/src/async_vm.rs
Add an api for async move vm to allow an extension.
Yes
`cargo check`
> [async-move] Allow passing extensions to async move vm.

- language/move-ir-compiler/transactional-tests/tests/bytecode-generation/declarations/function.exp
- language/move-ir-compiler/transactional-tests/tests/bytecode-generation/expressions/borrow.exp
- language/move-ir-compiler/transactional-tests/tests/bytecode-generation/expressions/borrow_mut.exp
- language/move-ir-compiler/transactional-tests/tests/bytecode-generation/expressions/builtins/borrow_global.exp
- language/move-ir-compiler/transactional-tests/tests/bytecode-generation/expressions/builtins/borrow_global_mut.exp
- language/move-ir-compiler/transactional-tests/tests/bytecode-generation/expressions/builtins/move_to.exp
- language/tools/move-cli/tests/sandbox_tests/module_publish_view/args.exp
- language/tools/move-cli/tests/sandbox_tests/package_basics/args.exp
- language/tools/move-disassembler/src/disassembler.rs
The function disassembler was looking at the local types, but it should have been looking at the parameter types. Fixed the bug, previously wrong expected value tests show that the fix works. Also added assertion to ensure that a source/bytecode function signature mismatch can't cause the same problem.
> [disassembler] fix bug in function signature disassembly

- language/extensions/move-table-extension/sources/Table.move
- language/extensions/move-table-extension/src/lib.rs
- language/extensions/move-table-extension/tests/TableTests.move
According to https://github.com/move-language/move/issues/95, Move lacks of lifetime support so we have to find a way to work around this. Otherwise, there is no way to implement clean APIs for many struct built on top of `Table` such as `IterableTable`.
This PR add trait bounds (copy + drop) to the `key`
Yes
cargo test
> [table-extenstion] Add trait bounds (copy + drop) to Table key

- language/move-compiler/src/expansion/translate.rs
- language/move-compiler/src/parser/syntax.rs
- language/move-compiler/tests/move_check/expansion/restricted_module_alias_names.exp
- language/move-compiler/tests/move_check/expansion/restricted_module_alias_names.move
- language/move-compiler/tests/move_check/expansion/restricted_module_names.exp
- language/move-compiler/tests/move_check/expansion/restricted_module_names.move
- old rule overly protective. 
- updated tests
> [move-compiler] Allow 'vector' as a module name

- .github/workflows/ci-test.yml
- language/documentation/examples/diem-framework/move-packages/DPN/sources/DiemAccount.move
- language/documentation/examples/diem-framework/prove_all.sh
- Added a script to prove all packages in `diem-framework`
- Updated the CI test script to prove the Diem Framework in CI
- Disabled the verification of `epilogue` and `epilogue_common` due to timeout
to enable the prover in CI
yes
> [move-prover] enable the Diem Framework proving in CI

- language/move-ir-compiler/move-ir-to-bytecode/syntax/src/lexer.rs
- language/move-ir-compiler/move-ir-to-bytecode/syntax/src/syntax.rs
- language/move-ir-compiler/transactional-tests/tests/parsing/keywords.mvir
- primitive type names are no longer tokens. They use the name token like other identifiers
- internal change
> [move-ir] De-tokenize primitive types

- README.md
- docker/move-cli/Dockerfile
Added Dockerfile for Move command-line interface for getting started
easier. This Dockerfile is based on the CI image found in docker/.
Also added building instructions to README.
Providing an easier way to get started with Move.
This Dockerfile can later be used with automated packaging solutions, such as Docker Hub.
Yes (going to fix the link anchor :laughing: ).
```
docker build -t move/cli -f docker/move-cli/Dockerfile .
cd ./language/documentation/tutorial/step_1/BasicCoin
docker run -v `pwd`:/project move/cli package build
```
> [docker] Added Dockerfile for the Move CLI

- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-analyzer/src/context.rs
- language/move-analyzer/src/symbols.rs
- language/move-analyzer/src/vfs.rs
This is a refinement for the recently added (https://github.com/move-language/move/pull/147) symbolication support in the language server. The purpose of the original PR (https://github.com/move-language/move/pull/147) was to introduce (and test) the symbolication algorithm itself.
The goal of this PR is to move the needle in terms of user experience - in the original PR, symbolication was triggered only once at the language server start. In this PR we trigger symbolication asynchronously (in a separate thread) each time a file is saved so that the most recent information about symbols is available to the IDE.
One reason to use only a single symbolicator thread is to throttle the number of times symbolication (which is relatively expensive) is triggered. At this point it's not a big issue …
> [language server] Async symbolication on file saves

- docker/move-cli/Dockerfile
- scripts/dev_setup.sh
Although most of the development setups have Git installed (since development happens in a Git repository), this assumption does not hold for all the cases: for example in the case of Docker's `ADD .` where local files are copied into a container without Git.
However, Git is required by the Move CLI (when using packages with Git dependencies), although this is undocumented.
Hence, the development setup script should have an option for installing it (although it's disabled by default).
Summary: **This PR adds -g switch to dev_setup.sh for installing Git.**
Yes.
```
docker build -t move/cli -f docker/move-cli/Dockerfile .
```
> [scripts] Git installation in dev_setup.sh

- Cargo.lock
- language/move-analyzer/Cargo.toml
- language/move-analyzer/editors/code/package-lock.json
- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-analyzer/src/completion.rs
- language/move-analyzer/src/diagnostics.rs
- language/move-analyzer/src/lib.rs
- language/move-analyzer/src/symbols.rs
- language/move-analyzer/src/utils.rs
- language/move-analyzer/src/vfs.rs
- language/move-compiler/src/diagnostics/mod.rs
This another refinement of recently added support for more advanced language server features (https://github.com/move-language/move/pull/147). This PR adds support for passing compiler diagnostics from the language server to the IDE (so that it is more clear why advanced features may not work or work in a limited fashion when the compilation fails).
This PR also fixes an ongoing problem with auto-completion where the loop where lexing problems could lead to a loop collecting identifiers from a file to run forever. 
Finally, supporting lexer diagnostics, particularly in the limited way they were supported, does not make much sense now that we have compiler diagnostics so the lexer ones have been removed.
Yes
> [language server] Added support for displaying compiler diagnostics

- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-analyzer/src/symbols.rs
One more refinement of recently added support for more advanced language server features (https://github.com/move-language/move/pull/147). This PR is about passing "fatal" compilation errors (i.e., those that do not result in generating diagnostics for the source code) back to IDE so that it's more explicit why more advanced features (i.e., those relying on successful compilation) may not work as expected.
Enabled advanced functionality in the server to simplify deployment, but it's not meant for wider consumption yet as it requires the extension to be re-published for the new functionality to work.
Yes
> [language server] Added support for passing compilation errors back to the IDE

- language/move-vm/types/src/gas_schedule.rs
This is the default gas schedule, having the assert there is harmful
since it causes issues for testing larger transaction sizes.
> [gas_schedule] remove legacy assert

- .github/workflows/ci-test.yml
For now, testing the Move CLI Docker image by building it and the BasicCoin Move module.
We should add more detailed tests later, for testing various parts of Move CLI.
The Dockerfile for the Move CLI was added here: 6941dce2f ("[docker] Added Dockerfile for the Move CLI", 2022-05-12)
(Style note: intentionally used double quotes for the `run` command. `run` is utilized throughout the file with, and without quotes. To me it seems that double quotes are used with complicated commands with multiple arguments, so using double quotes in this case as well.)
Yes.
Tested in this test PR: https://github.com/villesundell/move/pull/1 (The last test in the list, all checks passed).
> [github] Naive CI test for the CLI Docker image

- language/move-stdlib/docs/Option.md
- language/move-stdlib/sources/Option.move
- language/move-stdlib/tests/OptionTests.move
This is a useful thing to do in some cases, and is very painful to implement outside of the `Option` module.
> [stdlib] add function to convert option to vector

- language/move-command-line-common/src/testing.rs
- language/move-compiler/tests/move_check_testsuite.rs
- language/testing-infra/transactional-test-runner/src/framework.rs
- language/tools/move-cli/src/sandbox/commands/test.rs
- language/tools/move-package/tests/test_runner.rs
- language/tools/move-unit-test/tests/move_unit_test_testsuite.rs
- Added help message for all tests but the prover
- The provers test logic is a bit more custom
- And I think it already has a message
- @bmwill was rightfully confused 
- We have had some confusion on new contributors too 
Example
```
running 1 tests
test move_check_testsuite::parser/function_visibility_script.move ... FAILED
Error: Expected success. Unexpected diagnostics:
error[E01002]: unexpected token
┌─ tests/move_check/parser/function_visibility_script.move:4:23
│
4 │     public ( script ) fuun h() {}
│                       ^^^^
│                       │
│                       Unexpected 'fuun'
│                       Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'
Run with `env UB=1` (or `env UPDATE_BASELINE=1`) to save the current output as the …
```
> [quick fix] Add help for updated expected output files

- language/move-binary-format/src/compatibility.rs
- language/move-binary-format/src/normalized.rs
- language/move-binary-format/src/unit_tests/compatibility_tests.rs
- language/move-binary-format/src/unit_tests/mod.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/dependencies_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/mod.rs
- language/move-bytecode-verifier/src/dependencies.rs
- language/move-compiler/src/interface_generator.rs
- language/move-vm/transactional-tests/tests/module_publishing/republish_module_compatible_add_entry.exp
- language/move-vm/transactional-tests/tests/module_publishing/republish_module_compatible_add_entry.mvir
- language/move-vm/transactional-tests/tests/module_publishing/republish_module_incompatible_entry_removed.exp
- language/move-vm/transactional-tests/tests/module_publishing/republish_module_incompatible_entry_removed.mvir
- Fix issues where rules were removed for V4
- Preserving these is a pain, but makes upgrades easier
- The changes in #182 made it so you could get inconsistent results on V4 versions of the file format. Where the old software would say no, and the new software would say yes. 
- Bit of a pain, had to manually construct V4 modules
> [move-vm] Fix compatibility issues for new entry modifier

- language/extensions/async/move-async-vm/src/async_vm.rs
- language/extensions/async/move-async-vm/tests/testsuite.rs
Return the native context in async move's api for better composibility. The goal here is to integrate table extension to async move and the current api is not capable of doing that as native context gets consumed.
Yes
`cargo test`
> [async-move] Return extension context in async move execution api.

- language/move-binary-format/src/control_flow_graph.rs
Fix the signature of `next_block` and add documentation.
The `next_block` method returns the block id of the next block to traverse. The current return type however is `CodeOffset`, which is rather confusing.
Yes.
Since `pub type BlockId = CodeOffset;`, this change won't affect execution.
> [move-lang] Fix ControlFlowGraph trait

- language/move-analyzer/editors/code/.vscodeignore
- language/move-analyzer/editors/code/package.json
Currently published version of the extension doesn't really integrate with the language server as its current distribution is missing all JavaScript files that are responsible for handling LSP (Language Server Protocol):
```shell
unzip -l move.move-analyzer-0.0.6.vsix 
Archive:  move.move-analyzer-0.0.6.vsix
Length      Date    Time    Name
---------  ---------- -----   ----
2129  04-22-2022 22:58   extension.vsixmanifest
296  04-22-2022 22:58   [Content_Types].xml
970  04-01-2022 18:53   extension/language-configuration.json
20704  04-01-2022 18:53   extension/move.tmLanguage.json
137022  04-22-2022 14:53   extension/package-lock.json
4104  04-22-2022 15:23   extension/package.json
4583  04-22-2022 22:58   extension/README.md
---------                     -------
169808 …
```
> [Move] Added JavaScript files to the VSCode extension to integrate with the language server

- language/move-analyzer/src/symbols.rs
- language/move-analyzer/tests/symbols/sources/M4.move
Symbolication support for the language server incorrectly assumed that each module is stored in a separate file. This PR fixes this problem.
Yes
> [Move] Fixed symbolication of modules stored in the same file

- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-analyzer/src/symbols.rs
- language/move-analyzer/tests/symbols/sources/M1.move
- language/move-analyzer/tests/symbols/sources/M3.move
- language/move-compiler/src/naming/ast.rs
This is another refinement for the recently added (https://github.com/move-language/move/pull/147) symbolication support in the language server. This PR adds the type-on-hover functionality.
The basic idea is to store type information with the symbolication data and be able to use it when request for a type of a given identifier is issued.
We cannot use `Type` for this exclusively as it does not directly represent function signatures, so we special-case the latter. The debugging print for `Type` wasn't producing the best output for displaying info in the IDE so we implemented the `Display` trait for `Type_` to handle this.
Yes
> [Move analyzer] Added type-on-hover

- language/move-analyzer/src/symbols.rs
In the original implementation of diagnostics passing from the language server to the IDE, warnings were passed only if there were also errors in the code, but not by themselves. This PR fixes that.
Yes
> [Move] Pass warnging diagnostics from the language server to the IDE

- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-analyzer/src/symbols.rs
- language/move-analyzer/tests/symbols/sources/M1.move
This is another refinement for the recently added (https://github.com/move-language/move/pull/147) symbolication support in the language server. This PR adds the goto-type-def functionality.
The basic idea is to figure out which struct definition corresponds to a given module_id/struct_name pair and include this data with the symbols information for future retrieval. The data needed to find the right data was already being computed - this PR simply takes advantage of its existence.
Yes
> [Move] Added support for go-to-type-def

- language/documentation/examples/experimental/verify-sort/Move.toml
- language/documentation/examples/experimental/verify-sort/sources/loop.move
Added and proved a BubbleSort variant. Two properties verified: 1) the output vector is well sorted, and 2) the output vector is a permutation of the input vector. A trigger assertion is used to instantiate $\exists p:$ permutation.
To add an example of verifying a sorting algorithm. This example involves a complicated loop invariant and a trigger assertion.
Yes.
```move package prove```
> [move-prover] add example of verifying a sorting algorithm

- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-analyzer/src/symbols.rs
- language/move-analyzer/src/vfs.rs
This is another language server enhancement, this time related to supporting multi-root workspaces. This PR not only adds support for opening multiple directories within a workspace but also adds support for manifest file searching in case a single Move source file is open. 
The implementation is fairly straightforward - instead of replacing existing symbolication information, augment it with additional symbols coming from additional files/directories being opened.
This PR also implements discovery of manifest files in case a Move source file is opened rather than a package directory. Previously, if the former has happened, the new features would not be available as the language server did not know where to find Move.toml file needed for compilation.
Yes
> [Move] Added Move analyzer's support for multi-root workspaces

- language/move-analyzer/src/diagnostics.rs
This PR augments compiler diagnostics passed to the IDE with additional information. Previously we were only passing the main error message as it seemed like a good idea to keep the information displayed on-hover brief. However, in the case of some error messages, the main message is not quite enough to fully understand what's going on, hence adding additional info.
Yes
> [Move analyzer] Added support for more verbose compiler diagnostics

- language/move-analyzer/src/symbols.rs
A missing manifest message should be more meaningful to allow developers to act on it more easily. 
Yes
> [Move analyzer] Added a more meaningful missing manifest message

- language/tools/move-cli/src/package/cli.rs
If we want to re-use any of the code used in core Move for creating package directory structure, we need to do a bit of refactoring.
On the one hand, perhaps it's an overkill as this code does not do much, but I still don't like the idea of doing copypasta from core Move to other Move flavors to support this.
On the other hand, perhaps this could be more generalized (e.g., have vectors of dependency/address info). I'd think we can get there when/if we have to, but it's obviously subjective.
Yes
> [CLI] Parameterized new package creation for better reuse

- Cargo.lock
- language/tools/move-unit-test/Cargo.toml
- language/tools/move-unit-test/src/extensions.rs
- language/tools/move-unit-test/src/lib.rs
Until now, extensions leveraged by the Move UT infra had to live in the Move repo.
This PR adds a hook which can be used as in `move_unit_tests::extensions::set_extension_hook(fun)`,
where `fun` is populating a `NativeContextExtensions` for the according custom environment. How
to use this is documented in the code at `extensions.rs` and also in an integrated unit test.
> [unit-test] Allow extensions used for unit testing to live outside of Move repo

- language/documentation/book/book.toml
Added book.toml for better integration with our GitHub repository.
The GitHub edit button hopefully encourages people to contribute.
Also added structured metadata such as name, description, language and author information.
GitHub edit button was missing.
Yes.
```
cd ./language/documentation/book
mdbook serve --open
```
> [book] Added book.toml for better GitHub integration

- language/move-prover/boogie-backend/src/lib.rs
- language/move-prover/boogie-backend/src/options.rs
- language/move-prover/boogie-backend/src/prelude/prelude.bpl
This PR adds one more field to `BoogieOptions` so that users of move prover are able to supply Boogie implementations of their own custom Move native functions.
Yes
> add custom native options to move prover backend

- language/move-prover/boogie-backend/src/lib.rs
- language/move-prover/boogie-backend/src/options.rs
This PR updates boogie backend options so that we use bytes instead of file path in CustomNativeOptions.
> [move prover] use bytes instead of file path in CustomNativeOptions

- language/move-analyzer/Cargo.toml
- language/move-compiler/Cargo.toml
Max length of the address in core Move is 16 bytes but this is not true for other Move applications where this length can be as long as 32 bytes. This PR modifies Move analyzer (and Move analyzer only) to use longer max length to avoid compilation errors for Move uses outside of Move core. 
The max length is by default set to 32 bytes, but build-time options (via Cargo features) have been provided to either set it to core Move default (by resetting the default features of the Move analyzer) or by choosing 20 (or 32) bytes via selecting a specific Cargo feature.
EDIT:
It seems like defaulting to 32. bytes is not going to work without a more major restructuring of core Move code (as the feature the propagates to tests etc.), and this does not seem worthwhile at this point. A simpler option …
> [Move analyzer] Changed the max address length limit

- language/tools/move-cli/src/sandbox/cli.rs
- language/tools/move-cli/src/sandbox/commands/publish.rs
- language/tools/move-cli/tests/sandbox_tests/cyclic_multi_module_publish/args.exp
- language/tools/move-cli/tests/sandbox_tests/cyclic_multi_module_publish/args.txt
- language/tools/move-cli/tests/sandbox_tests/multi_module_publish/args.exp
- language/tools/move-cli/tests/sandbox_tests/multi_module_publish/args.txt
This PR contains two changes to the `move-cli sandbox publish` interface:
**Commit 1**: [move-cli] add --with-deps option to the publish command
The default scenario is to publish the modules within the package only,
excluding the modules compiled from its dependency packages. This
`--with-deps` flag, when set, will allow modules in the deps packages
to be published as well, together with the package root modules.
**Commit 2**: [move-cli] allow multi-module publishing in Move CLI with --bundle
The current default mode of publishing in Move CLI is sequential,
i.e., one-module-at-a-time. This means that modules that are cyclic
dependent cannot be published all at once (e.g., the DPN in the
documentation/examples directory).
To show this issue, run:
```
cd …
```
> [move-cli] sandbox publishing with multiple modules and optionally, all modules in a package

- language/move-analyzer/editors/code/README.md
- language/move-analyzer/editors/code/package.json
This PR modifies installation instructions for the language server to be published in VSCode Marketplace to accommodate different Move flavors (a followup to the recent PR enabling this: #260)
Yes
> [Move analyzer] Update language server installation instructions

- language/move-prover/tests/README.md
This PR updates the README in `move-prover/tests` folder:
- Removes the "Code coverage" section since it was referring to code coverage in diem repo
- Updates the tests that get run when we do `cargo test`
> [doc] remove broken link and update readme

- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-analyzer/src/symbols.rs
The goal of this PR is to enable unit tests that require symbolication information to be available to the IDE client right away, that is right after a connection with the language server is successfully established. Otherwise, we either need to use hard-coded delays (which is arguably not the prettiest nor most reliable approach) or create a more elaborate synchronization mechanism (which is otherwise unnecessary and may affect server responsiveness). 
Yes
> [Move analyzer] Added support for computing first symbol info synchronously

- language/extensions/move-table-extension/Move.toml
- language/extensions/move-table-extension/README.md
- language/extensions/move-table-extension/sources/Table.move
- language/extensions/move-table-extension/sources/Table.spec.move
- language/extensions/move-table-extension/src/lib.rs
- language/extensions/move-table-extension/tests/table_tests.move
- language/move-model/src/well_known.rs
- language/move-prover/boogie-backend/src/prelude/native.bpl
- language/move-prover/tests/sources/functional/verify_table.move
- language/move-prover/tests/testsuite.rs
This PR "lowercased" the `move-table-extension` package, and updated Prover accordingly.
To make the `move-table-extension` package lowercase
yes
cargo test
> [Prover] Make the `move-table-extension` package lowercase

- language/extensions/move-table-extension/sources/Table.move
- language/extensions/move-table-extension/src/lib.rs
- language/move-vm/test-utils/src/storage.rs
- language/tools/move-unit-test/src/extensions.rs
Getting this information requires deep understanding of changesets to otherwise get the typeinfo for the key and value. And doing so expensive. This is relatively cheap and can be used by the node to support lookup and decoding of types in storage.
> [table] add information about the table types when adding new tables

- language/move-vm/types/src/values/values_impl.rs
This adds a missing cast from `Value` to `Vec<Value>` so that native functions can access the elements of non-specialized vectors.
> [move-vm] allow casting from Value to Vec<Value>

- language/move-prover/bytecode/src/stackless_bytecode_generator.rs
- language/move-prover/bytecode/tests/from_move/vector_instructions.exp
- language/move-prover/bytecode/tests/from_move/vector_instructions.move
This PR fixes a bug in stackless bytecode generation of vector bytecode instructions. 
Previously, `VecPack` is translated to:
```rust
let temp = vector::new();
for element in operands {
vector::push_back(temp, element);
}
``` 
This is buggy because `vector::new()` returns a new vector object but `vector::push_back` takes in a mutable reference to a vector. This PR adds that missing `borrow_mut`:
```rust
let temp = vector::new();
let mut_ref = &mut temp;
for element in operands {
vector::push_back(mut_ref, element);
}
``` 
Same reasoning applies to `VecUnpack`.
> [stackless bytecode] fix a bug in VecPack and VecUnpack

- language/move-vm/runtime/src/session.rs
Until now this have been hidden inside the session and only accessible from within native functions. This makes them also accessible outside so we can work with them on session level (e.g. for lazy code loading).
> [vm] Allow access to native extensions via the session.

- language/tools/move-cli/src/base/prove.rs
Now that `move_cli::base::run_move_prover` is used by multiple chain-specific CLIs as a library function, logging setup should be moved out of the function. Since each chain-specific CLI may use different logging scheme. This PR doesn't change how the core Move CLI behaves.
> [cli] refactor logging setup out of run_move_prover

- Cargo.lock
- language/move-analyzer/Cargo.toml
- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-analyzer/src/completion.rs
- language/move-analyzer/src/symbols.rs
- language/move-analyzer/src/vfs.rs
This PR adds additional support for the Move analyzer to correctly build and run on Windows. In particular the "standard" version of path canonicalization produces non-standard output on Windows (so called UNC format).
Yes
> [Move analyzer] Added support for building and running on Windows

- language/move-vm/runtime/src/runtime.rs
- language/move-vm/runtime/src/session.rs
By default module publishing checks for downwards compatibility of a module when it is re-published. This PR adds a new entry point which allows to relax this check if desired.
> [vm] Allow module publishing skipping compatability checks.

- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/tests/sources/functional/aborts_if_with_code.exp
- language/move-prover/tests/sources/functional/global_invariants.exp
- language/move-prover/tests/sources/functional/invariants.exp
- language/move-prover/tests/sources/functional/is_txn_signer.exp
- language/move-prover/tests/sources/functional/loops.exp
- language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
- language/move-prover/tests/sources/functional/macro_verification.exp
- language/move-prover/tests/sources/functional/trace.exp
The Move prover does not print the correct line number in some error traces. Consider the example below.
```
public fun test_loop(x: u64) {
if (x != 0) {
x = 1;
}
else {
x = 2;
};
spec {
assert x == 1;
};
}
```
The following error trace is given.
```
error: unknown assertion failed
┌─ ./sources/loop.move:9:9
│
9 │         assert x == 1;
│         ^^^^^^^^^^^^^^
│
=     at ./sources/loop.move:1: test_loop
=         x = 0
=     at ./sources/loop.move:2: test_loop
=         x = 2
=     at ./sources/loop.move:8: test_loop
=     at ./sources/loop.move:9: test_loop
```
However, the assignment `x = 2` occurs at Line 6 rather than Line 2. This pull request will insert `at ./sources/loop.move:6: test_loop` above `x = 2`.
Yes
cargo test --release
> [move-prover] Add missing location line in error trace

- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/tests/borrow/function_call.exp
This commit fixes issue #270 where the edge ordering are reversed in a
hyper-edge when that hyper-edge is inlined to construct a borrow graph.
In Move Prover, hyper-edges are used to summarize the borrow-relation
between function arguments and function return values:
In the example in #270, given
```move
fun inner(has_vector: &mut HasVector): &mut HasAnotherVector {
vector::borrow_mut(&mut has_vector.v, 7)
}
```
The `inner` function will yield a hyper-edge:
```
return_ref --borrows_from--> { arg: has_vector, edge: Hyper(.v/[]) }
```
Now, this hyper-edge will be further used to derive the borrow-relation
for the `mid` function:
```
fun mid(has_vector: &mut HasVector): &mut HasAnotherVector {
inner(has_vector)
}
```
The expected summary for `mid` is
```
return_ref --borrows_from--> { arg: …
```
> [move-prover] fix hyper-edge constructor in borrow analysis

- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/memory_instrumentation.rs
- language/move-prover/tests/sources/functional/conditional_write_back.move
- language/move-prover/tests/sources/functional/invariants.exp
The current memory model in Move Prover has a flaw in writing back
dying references, as identified in issue https://github.com/move-language/move/issues/299.
The gist of the flaw is this:
we can only write-back a reference on code paths where it is guaranteed
to be defined. Otherwise in the prover's point of view, the write-back
may cause arbitrary value to be written back to the parent `Mutation`
value and cause unexpected verification failures.
As a side note, this is also visible in the concrete executor of the
spec + move (i.e., the stackless VM).
The solution, as implemented in this commit, is to ravamp the way
write-backs are done.
In summary, the solution is to write-back the dying references according
to DFS paths instead of BFS layers.
Taking the example in …
> [move-prover] write-back following the whole ancestor tree

- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-analyzer/src/symbols.rs
This is a follow-up to https://github.com/move-language/move/pull/292 - this PR moves initial symbolication run to be executed by a thread with increased stack size to have all symbolicator runs (both the initial one and the following ones) work correctly on Windows.
Yes
> [Move analyzer] Increased stack size of initial symbolication run

- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/tests/borrow/basic_test.exp
- language/move-prover/bytecode/tests/borrow_strong/basic_test.exp
- language/move-prover/bytecode/tests/memory_instr/basic_test.exp
- language/move-prover/tests/sources/functional/loops_with_memory_ops.cvc5_exp
- language/move-prover/tests/sources/functional/loops_with_memory_ops.move
- language/move-prover/tests/sources/functional/mut_ref_arg_return.move
Prover panic-ed when trying to verify this simple program:
```move
fun one_of_two(cond: bool, r1: &mut u64, r2: &mut u64): &mut u64 {
if (cond) {r1} else {r2}
}
fun test1(cond: bool, v1: u64, v2: u64) {
let r = one_of_two(cond, &mut v1, &mut v2);
*r = 0;
spec {
assert cond ==> v1 == 0;
assert !cond ==> v2 == 0;
}
}
```
A further analysis found that the borrow summary for function `one_of_two` is not
properly constructed, with the return result not borrowing from neither `r1` or `r2`
(which it should be a direct borrow of `r1` or `r2`).
After some digging in the bytecode, it seems that we are using `r := r1` and `r = r2` 
for the assignment, which is considered as a `Store` assignment and is treated
the same way as a `Move` assignment. This seems correct in terms borrow semantics
but there …
> [move-prover] treat store as copy in borrow analysis

- language/move-stdlib/src/natives/mod.rs
I forgot to make the fields of `GasParameter` public in the previous PR, so it ended up being inhabitable. This gets it fixed.
> [stdlib] make fields of GasParameters public

- language/move-prover/interpreter-testsuite/tests/concrete_check/choice.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/choice.move
- language/move-prover/interpreter-testsuite/tests/concrete_check/quantifier.move
- language/move-prover/interpreter/src/concrete/evaluator.rs
- language/move-prover/interpreter/src/concrete/local_state.rs
- language/move-prover/interpreter/src/concrete/player.rs
- Complete the evaluator for the `choose` and `choose min` operators. All the values in the range that satisfy the predicate are extracted and the value in the last position of the vector is returned deterministically for the `choose` operator.
- Update the evaluator for assume expression to return `EvalResult` to distinguish `None` results from choice operators and other assertions. Move `skip_specs` from the function context to the local state to enable the `let` binding. If the choice operators return `None`, skip the following specs to log the error message.
- When no value satisfies the predicate for the choice operators, log the error message and abort the execution.
Yes.
(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that …
> [move-prover] Add evaluation logic for choice operators

- language/tools/move-cli/src/base/docgen.rs
- language/tools/move-cli/src/base/mod.rs
- language/tools/move-cli/src/lib.rs
- language/tools/move-cli/tests/build_tests/simple_build_with_docs/args.exp
- language/tools/move-cli/tests/build_tests/simple_build_with_docs/args.txt
- language/tools/move-cli/tests/build_tests/simple_build_with_docs/sources/Foo.move
- language/tools/move-cli/tests/build_tests/simple_build_with_docs/template.md
Move Prover's `--docgen` switch is not currently exposed to the user, so added a top level command `docgen` to do the trick.
Move Prover is also mentioned in the description, so the user knows they must have a working Move Prover setup in order to use this feature.
Also added a smoketest for the `docgen` command so it would not break because of a regression. A non-existent subcommand `smoketest` is intentionally used so the output has as little variable output as possible.
Move Prover's `--docgen` switch is not currently exposed to the user, so added a top level command `docgen` to do the trick.
Yes.
In addition to the smoke test (`cargo test -p move-cli`) you can test the actual documentation generation by running:
```
cargo build -p move-cli
./target/debug/move --path …
```
> [move-cli] Added "docgen" command

- language/move-core/types/src/account_address.rs
- language/move-core/types/src/language_storage.rs
FromStr helps a lot of other tools properly parse types without having to go find the functions related.  Since these already exist, it should make it easier.
Also, allow AccountAddress to load with 0x in front.  I'm not going to try to deal with the output path in this PR.
Yes
The current unit tests
> Use standard traits for FromStr

- language/move-prover/bytecode/src/eliminate_imm_refs.rs
- language/move-prover/bytecode/tests/eliminate_imm_refs/basic_test.exp
- language/move-prover/bytecode/tests/eliminate_imm_refs/basic_test.move
- language/move-prover/bytecode/tests/livevar/basic_test.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/destroy.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/destroy.move
The `destroy($t1)` bytecode is not removed in the immutable borrow
pass, which it should be, otherwise we will observe an `destroy($t1)`
where `$t1` is not a reference type.
This does not cause any issue with the symbolic reasoning as `destroy`
is essentially translated into a no-op. Instead, it is caught by the
concrete executor.
Improve the stackless bytecode
Yes
CI, with new test cases
> [move-prover] remove the destroy instruction for imm borrow removal

- language/move-analyzer/editors/code/src/context.ts
- language/move-analyzer/editors/code/src/main.ts
Annoying to write doc strings
Yes
Ran the extension locally
> [move-analyzer] Improve support for Move doc comments

- language/move-prover/interpreter-testsuite/tests/concrete_check/property/mono.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/property/mono.move
- language/move-prover/interpreter-testsuite/tests/concrete_check/return_mut_ref.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/return_mut_ref.move
- language/move-prover/interpreter/src/concrete/local_state.rs
- language/move-prover/interpreter/src/concrete/player.rs
- language/move-prover/interpreter/src/shared/variant.rs
The first commit fixes two bugs to re-enable the failing test:
- collect pointers for write-backs even when the local slot is destroyed
- fix the indexing of the borrow edge in the write-back process.
The second commit picks the `baseline` version for callee with ghost type params
- This is a temporary solution until we have a better way to multiplex the
spec evaluation against multiple universially quantified types.
As title
Yes
CI, with the re-enabled test.
> [move-prover][interpreter] two bug fixes to re-enable disabled tests

- Cargo.lock
- language/move-analyzer/Cargo.toml
- language/move-analyzer/src/bin/move-analyzer.rs
While `move-analyzer --version` reports `1.0.0`, the package itself is at version `0.0.0`. This is because version information is hardcoded to the `clap()` usage, and the `Cargo.toml` package manifest is out-of-date.
Updated `Cargo.toml` information: dropping Diem mentions and setting a proper version. `Clap()` usage was also changed to idiomatic one as per 9225b84aa ("Idiomatic "clap" usage (implements --version switch for tools) (#81)", 2022-05-02)
(Also tried to replace the author, but changing it doesn't pass the linter, so need to have another PR for changing the linting rule and all the mentions in every `Cargo.toml`, since that would be logically a different kind of change)
There is a discrepancy between the package version, and version reported by `move-analyzer --version`. This …
> [Move analyzer] Updated package info & clap usage

- language/move-prover/boogie-backend/src/boogie_wrapper.rs
- language/move-prover/boogie-backend/src/options.rs
- language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
- scripts/dev_setup.sh
- Updated the Z3 version to the latest one.
- Updated the Boogie version to latest one that is compatible with Prover.
- Incompatibility issue filed in the Boogie repo: https://github.com/boogie-org/boogie/issues/609
- Fixed a few bugs in `boogie_wrapper`.
To bump up the version number of Prover's deps.
yes
cargo test -p move-prover
> [move-prover] Bump up the version number of the Prover dependencies

- language/move-prover/interpreter-testsuite/tests/concrete_check_testsuite.rs
- language/tools/move-cli/src/base/test.rs
- language/tools/move-unit-test/src/lib.rs
- language/tools/move-unit-test/tests/move_unit_test_testsuite.rs
This PR makes instruction execution bound an option in the CLI options and increments the default value since 5000 is too low.
cargo test
> make instruction execution bound an option and increment default value

- language/tools/move-cli/src/base/new.rs
Other platforms attempting to re-use the `new` CLI command implementation may need to add additional custom content to the generated Move.toml files which was previously not possible.
Yes
> [cli] Added the ability to add custom content to generated Move.toml files

- language/move-prover/boogie-backend/src/boogie_wrapper.rs
- language/move-prover/boogie-backend/src/options.rs
- scripts/dev_setup.sh
- Bumped up the boogie version to the latest one (2.15.7)
- Updated `boogie_wrapper` to ignore the state information that Boogie produces as output ("*** STATE ... *** 
-  END_STATE")
- `boogie_wrapper` parses the model after cutting out the state info block. Otherwise, parsing would not be correctly done, and warning messages are generated.
To bump up the boogie version
yes
cargo test
> [Move Prover] Bump up the boogie version to 2.15.7

- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/tests/borrow/basic_test.exp
- language/move-prover/bytecode/tests/borrow/function_call.exp
- language/move-prover/bytecode/tests/borrow/hyper_edge.exp
- language/move-prover/bytecode/tests/borrow_strong/basic_test.exp
- language/move-prover/bytecode/tests/borrow_strong/mut_ref.exp
- language/move-prover/tests/sources/regression/moved_local_with_refs.move
If a local is first mutably borrowed and later moved in a loop, the
reference will have two parents (and hence, write-back edges):
- one to the original local and
- the other to the LHS of the moved local.
This can be shown in the following code:
```move
loop {
let s = S { x : 100  };
let r = &mut s;
if (r.x >= limit) {
r.x = limit;
}
t = move(s);
}
```
The borrow analysis will conclude that the reference `r` has two
parents, `s` and `t`.
This bug can only happen in loops due to the fact that the borrow
analysis is essentially an abstract interpretation pass and the
join operator for the `BorrowInfo` is a set union. Although for any
single pass on the loop body, `r` can either point to `s` or `t`. After
the join, `r` points to both `s` and `t`, which is incorrect.
This commit fixes this …
> [move-prover] do not remap moved nodes in borrow analysis

- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/move_vm.rs
- language/move-vm/runtime/src/runtime.rs
This is a hack to workaround well-known issues with the VMs code loader cache. This cache is not designed to support module upgrade or deletion. This leads to situations where the cache does not reflect the state of storage:
1. On module upgrade, the upgraded module is in storage, but the old one still in the cache.
2. On an abandoned code publishing transaction, the cache may contain a module which was never committed to storage by the adapter.
The solution is to add a flag to `Loader` marking it as 'invalidated'. For scenario (1), the VM sets the flag itself. For scenario (2), a public API allows the adapter to set the flag.
If the cache invalidated, it can (and must) still be used until the end of the session. This is because during session execution, data might have been extracted …
> [vm] Invalidate and flush code loader cache

- language/move-prover/interpreter-testsuite/tests/concrete_check/choice.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/choice.move
- Add unit test for address type domain for choice operators.
Yes.
> [move-prover][interpreter] Add unit test for choice operator

- language/documentation/examples/experimental/coin-swap/sources/CoinSwap.move
The example coin-swap has compilation error
Issue is the usage of error in move std
Yes, I have read it and have run `cargo x lint && cargo xfmt && cargo xclippy --all-targets`
I only updated the error lib usage according to move std lib document
> fix example coin-swap error lib usage

- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/move_vm.rs
- language/move-vm/runtime/src/runtime.rs
If a VM is used to execute multiple sessions, the adapter is not cabable to see which modules have been loaded by a given transaction, because modules are cached internaly by the VM, and no call back to the adapters data store happens.
This PR adds a small change which allows the adapter to read out this information, roughly as follows:
```
let vm = MoveVM::new();
let session = vm.new_session();
<<work with this session>>
let cache_hits = vm.get_and_clear_module_cache_hits();
let used_modules = cache_hits + modules_read_from_storage()
// next session starts with 0 cache hits
let session = vm.new_session();
...
```
> [vm] Add ability for adapter to observe module loader cache hits

- language/move-prover/boogie-backend/src/prelude/native.bpl
- Added some missing native function mock-ups in Prover's prelude
- Need to revisit the new `guid` and `counter` functions because Prover has abstracted those out in verification.
To add native functions in Prelude
yes
cargo test
> [Move Prover] Added some missing native functions in Prover's prelude

- language/move-prover/boogie-backend/src/bytecode_translator.rs
The type arguments should be the type arguments for the struct, not the
current function.
Fix [this issue](https://github.com/aptos-labs/aptos-core/issues/2581)
Yes
CI
> [move-prover] fix field type instantiation in borrow edge

- language/move-analyzer/editors/code/src/commands/lsp_command.ts
- language/move-analyzer/editors/code/src/main.ts
- language/move-analyzer/editors/code/tests/lsp-demo/sources/Completions.move
- language/move-analyzer/editors/code/tests/lsp.test.ts
- language/move-analyzer/src/bin/move-analyzer.rs
- language/move-analyzer/src/completion.rs
- language/move-analyzer/src/symbols.rs
- language/move-compiler/src/parser/keywords.rs
The current move-analyzer has limited code completion support, this PR adds primitive types and function name completion.
Note: the `IdentType` in `FunctionIdentTypeMap` is not used in this PR. However, it will be used for function signature help in a future PR.
Yes
- Open the extension in debug mode
- There should be a code completion suggestion for primitive types if you start typing a prefix of any primitive types (e.g. u64, bool etc.)
- There should be a code completion suggestion for any function name prefix inside the same file
- Add more intellisense support. (e.g. show function signature help, module method completion, auto imports etc.) Each of these …
> [move-analyzer] basic function name completion

- docker/move-cli/Dockerfile
Adds a build step that replaces CRLF chars with LF chars in all script files, fixes a build issue I was having in WSL.
Build was failing in WSL. [(issue)](https://github.com/move-language/move/issues/363)
Yes, I have.
Build failed in WSL before change, succeeds after change.
> [Build/WSL] Remove line-ending carriage returns in script files

- Cargo.lock
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/code_unit_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/control_flow_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/negative_stack_size_tests.rs
- language/move-bytecode-verifier/src/code_unit_verifier.rs
- language/move-bytecode-verifier/src/control_flow.rs
- language/move-bytecode-verifier/src/lib.rs
- language/move-bytecode-verifier/src/verifier.rs
- language/move-core/types/src/vm_status.rs
- language/move-vm/integration-tests/Cargo.toml
- language/move-vm/integration-tests/src/tests/mod.rs
- language/move-vm/integration-tests/src/tests/nested_loop_tests.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/move_vm.rs
- language/move-vm/runtime/src/runtime.rs
This allows the bytecode verifier to limit the depth of nested loops. To enable this check, you'll need to pass in a `VerifierConfig` via the new entry points (`xxx_with_config`). The old entry points are kept to maintain backward compatibility, but they delegate to the new entry points under the hood.
New verifier unit tests & move vm integration tests have been added to ensure this check can be activated properly
> [verifier] add option to limit nested loop depth

- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/move_vm.rs
This adds an API to allow the adapter to access module metadata. Metadata can be accessed depending on whether the code is in the cache or not. No guarantees for the availability of metadata are to be expected. Once we have the code loader owned by the adapter, we can remove this API from the VM and let the adapter directly call into the loader.
Better debugging support
Yes
NA
> [vm] Allow to access module metadata

- language/extensions/async/move-async-vm/src/async_vm.rs
- language/extensions/async/move-async-vm/tests/sources/AccountStateMachine.exp
- language/extensions/async/move-async-vm/tests/sources/Basic.exp
- language/extensions/async/move-async-vm/tests/testsuite.rs
- language/extensions/move-table-extension/src/lib.rs
- language/move-core/types/src/effects.rs
- language/move-prover/interpreter/src/concrete/value.rs
- language/move-prover/interpreter/src/shared/bridge.rs
- language/move-vm/integration-tests/src/tests/bad_storage_tests.rs
- language/move-vm/runtime/src/data_cache.rs
- language/move-vm/runtime/src/runtime.rs
- language/move-vm/test-utils/src/storage.rs
- language/move-vm/types/src/data_store.rs
- language/move-vm/types/src/values/values_impl.rs
- language/testing-infra/test-generation/src/lib.rs
- language/tools/move-cli/src/sandbox/commands/publish.rs
- language/tools/move-cli/src/sandbox/utils/mod.rs
- language/tools/move-unit-test/src/test_runner.rs
This makes a few improvements to the `ChangeSet`:
1. `Option<Vec<u8>>` gets replaced by `enum Op { New(..), Modify(..), Delete }`. This means the `ChangeSet` now differentiates writing a new entry from modifying an existing one.
2. Some old APIs with ambiguous semantics (e.g. publish_xxx) gets replaced by new ones (add_xxx). The `ChangeSet` now functions more like a delta rather than some sort of ad-hoc storage.
This change benefits tools like move-cli by providing the information they need (new vs modify). It also makes it possible to charge gas based on the number of new entries created.
> [move-core] better ChangeSet impl

- language/move-compiler/src/parser/syntax.rs
- language/move-compiler/src/typing/core.rs
- language/move-compiler/tests/move_check/parser/break_with_value.exp
- language/move-compiler/tests/move_check/parser/break_with_value.move
- language/move-compiler/tests/move_check/parser/control_exp_as_term.exp
- language/move-compiler/tests/move_check/parser/control_exp_as_term.move
- language/move-compiler/tests/move_check/parser/control_exp_associativity.move
- language/move-compiler/tests/move_check/parser/control_exp_associativity_else_after_if_block.exp
- language/move-compiler/tests/move_check/parser/control_exp_associativity_else_after_if_block.move
- language/move-compiler/tests/move_check/parser/control_exp_associativity_field_access.move
- language/move-compiler/tests/move_check/parser/control_exp_associativity_typing_invalid.exp
- language/move-compiler/tests/move_check/parser/control_exp_associativity_typing_invalid.move
- language/move-compiler/tests/move_check/parser/control_exp_associativity_unreachable_code.exp
- language/move-compiler/tests/move_check/parser/control_exp_associativity_unreachable_code.move
- language/move-compiler/tests/move_check/parser/return_in_binop.exp
- language/move-compiler/tests/move_check/parser/return_in_binop.move
- language/move-compiler/tests/move_check/typing/binary_add_invalid.exp
- language/move-compiler/tests/move_check/typing/binary_bit_and_invalid.exp
- language/move-compiler/tests/move_check/typing/binary_bit_or_invalid.exp
- language/move-compiler/tests/move_check/typing/binary_bit_xor_invalid.exp
- language/move-compiler/tests/move_check/typing/binary_div_invalid.exp
- language/move-compiler/tests/move_check/typing/binary_mod_invalid.exp
- language/move-compiler/tests/move_check/typing/binary_mul_invalid.exp
- language/move-compiler/tests/move_check/typing/binary_sub_invalid.exp
- language/move-compiler/transactional-tests/tests/parser/control_exp_associativity.exp
- language/move-compiler/transactional-tests/tests/parser/control_exp_associativity.move
- language/move-compiler/transactional-tests/tests/parser/return_not_binary.exp
- language/move-compiler/transactional-tests/tests/parser/return_not_binary.move
- Made control expressions terms to fix cases where they did not behave like other expressions
- Allowed blocks to switch their associativity
- Before this PR, control expressions (`if`, `else`, `loop`, `while`, `return`, and `abort`) were always right associative. 
- After this PR, control expressions only consume the next block if there is one. Otherwise, they continue their right associative behavior. 
- It is a bit funky to describe, but I think the examples make sense
- and it mostly matches the behavior with if/else and begin/end in OCaml (and similar constructs in other ML languages)
- Fixed some issues with return's value not being parsed correctly
- Fixing an issue @awelc found. `if (cond) { s1 } else { s2 }.f` looks like it should be parsed as `(if (cond) s1 else s2).f` but it …
> [move-lang] Make control expressions terms. Fix their associativity.

- Cargo.lock
- language/tools/move-package/Cargo.toml
- language/tools/move-package/src/package_lock.rs
This is to address #346.
The same package lock file is used for different users (e.g.
`/tmp/move_package_lock.lock`), this is problematic on hosts shared by
many users. This add the username to the end of the package lock file
(e.g. `/tmp/move_package_Lock_username.lock`).
Yes.
> [move-cli] add username to package lock file.

- language/documentation/book/src/references.md
In the  Move Book 
Chapter References [freeze inference](https://move-language.github.io/move/references.html#freeze-inference).
here may want to say the compile will automatic add a `freeze` action between 
`&x ` and `&mut x`
so change the former
`let y: &mut u64 = &mut x;`
to 
`let y: &u64 = &mut x;`
> [book] modify example for freeze of reference

- language/extensions/async/move-async-vm/src/async_vm.rs
- language/extensions/move-table-extension/src/lib.rs
- language/move-vm/runtime/src/data_cache.rs
- language/move-vm/runtime/src/interpreter.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/test-utils/src/gas_schedule.rs
- language/move-vm/test-utils/src/storage.rs
- language/move-vm/types/src/data_store.rs
- language/move-vm/types/src/gas.rs
- language/move-vm/types/src/lib.rs
- language/move-vm/types/src/values/values_impl.rs
- language/move-vm/types/src/views.rs
This extends the `GasMeter` trait with callbacks for various operations, allowing precise control. As a byproduct, this also adds two traits `TypeView` and `ValueView` which are used to expose certain info to the gas meter in a lazy fashion.
The changes are (hopefully) implemented in a backward-compatible manner, meaning that one should be able to maintain the old gas semantics if implementing the callbacks in a certain way. (See the current `GasStatus` impl for an example.)
**Note: this depends on https://github.com/move-language/move/pull/383, and please be aware that the first commit belongs to that PR.**
> [gas] add gas meter callbacks

- language/move-stdlib/src/natives/bcs.rs
- language/move-stdlib/src/natives/event.rs
- language/move-stdlib/src/natives/hash.rs
- language/move-stdlib/src/natives/mod.rs
- language/move-stdlib/src/natives/signer.rs
- language/move-stdlib/src/natives/string.rs
- language/move-stdlib/src/natives/vector.rs
- language/move-vm/runtime/src/interpreter.rs
- language/move-vm/types/src/gas.rs
- language/move-vm/types/src/values/value_tests.rs
- language/move-vm/types/src/values/values_impl.rs
- language/move-vm/types/src/views.rs
This packs a few fixes and improves to various components:
1. `GasMeter::charge_read_ref` now correctly receives a view into the value being referenced instead of the reference value itself
2. `ValueView` now provides a `visit` function that would allow you to traverse the value recursively. 
a. This is used to provide a new implementation of abstract memory size calculation
b. The old `size()` functions are still kept, but they are used only in tests to check that the results produced by both implementations match.
c. The plan is to (1) remove the `size()` functions once the new impl gets used in the wild for some time, (2) encourage clients to implement their own abstract memory size if they still need it and (3) remove the view-based abstract memory size impl
3. Some move-stdlib gas …
> [gas] minor fixes and improvements to gas meter callbacks, views and move-stdlib

- Cargo.lock
- language/move-analyzer/Cargo.toml
- language/move-analyzer/src/completion.rs
- language/move-analyzer/src/symbols.rs
Recently added support for displaying function documentation in the on-hover text box exposed a mild problem - function documentation often refers to parameter names which were previously not displayed as part of the function's signature (only the types were). This PR fixes this problem:
This PR also includes a refactoring/fix where one of the maps used to obtain symbols information was removed in favor of the information being encoded elsewhere. An additional reason for this change was that the map was not quite implemented correctly (particularly considering upcoming changes using it: #381) as we can have multiple functions with the same name in the same (multi-module) file.
The function type used to be computed based on the signature (for definitions) or based on the call site info …
> [move-analyzer] Added support for displaying paramter names on hover

- Cargo.lock
- language/extensions/move-table-extension/Cargo.toml
- language/extensions/move-table-extension/sources/Table.move
- language/extensions/move-table-extension/src/lib.rs
- language/extensions/move-table-extension/tests/move_unit_tests.rs
u128 is not enough to avoid collision, increase the handle to u256 represented by two u128. the layout is compatible to [u8;32] in bcs.
> [Table] use u256 instead of u128 for table handle to increase security

- Cargo.lock
- language/extensions/move-table-extension/Cargo.toml
- language/extensions/move-table-extension/sources/Table.move
- language/extensions/move-table-extension/src/lib.rs
- language/extensions/move-table-extension/tests/move_unit_tests.rs
Use u128 imposes huge usability problem for clients since the json returns back the Object {low: xxx, high: yyy} for the handle instead of 32 bytes.
Use address can mitigate the problem until we have u256 impl.
> [table] use address for handle instead of two u128

- Cargo.lock
- language/tools/move-cli/Cargo.toml
- language/tools/move-package/Cargo.toml
reqwest 1.10 depends on older version of hyper which has a vuln https://rustsec.org/advisories/RUSTSEC-2021-0079
Yes
Normal tests
> Upgrade `reqwest` package

- language/move-core/types/src/account_address.rs
I tried my best to make the printing of account address consistent across the system, but it became too complicated.
I'm at least making the account address display as lowercase like serialization, hex literal, and everything else.
Yes
I added new tests, but let's see how CI likes the change
> [address] Account address output consistent

- language/move-vm/runtime/src/loader.rs
This PR fixes a potential deadlock bug in move-vm/runtime.
fn `transitive_dep_closure` is a recursive function, which
1. Acquires a parking_lot read-lock
2. Calls the fn itself transitively
3. The callee acquires the read-lock again!
Due to the write priority of parking_lot, when another thread tries to acquire write-lock in between step 1 and 3,
a deadlock will happen.
My fix is to limit the read-lock scope by assigning those after the read-lock to `deps`.
This way the read-lock will be dropped after the `let deps = ...` statement and will not cause deadlock.
Another possible fix involves adding `&ModuleCache` as a parameter of `transitive_dep_closure`,
and uses one read-lock before calling this fn to protect it and all the recursive callees.
Yes.
I detected this bug via my static …
> [move-vm] Fix a potential deadlock bug in transitive_dep_closure

- Cargo.lock
- language/tools/move-cli/Cargo.toml
- language/tools/move-cli/src/base/docgen.rs
- language/tools/move-cli/tests/build_tests/simple_build_with_docs/args.exp
- language/tools/move-cli/tests/build_tests/simple_build_with_docs/args.txt
A rudimentary version of the "docgen" command was implemented in 55a40d583 ("[move-cli] Added "docgen" command (#291)", 2022-07-28). However, the implementation was relying on the Move Prover, only exposing one Docgen switch to the user.
This implementation is using the actual Dogen, giving us a possibility to expose all the Docgen switches to the user. The enable/disable logic is modeled against current default settings for Docgen. This is also an indirect way to communicate the default settings to the user.
Addressing the actual Docgen as move_docgen::Docgen, because both, this subcommand and the Move Docgen are entitled to that name: this subcommand because of the Move CLI coding convention, and the actual Move prover because it's the most descriptive short name.
Removed --quiet, since …
> [move-cli] A proper "docgen" implementation

- language/evm/move-to-yul/src/functions.rs
- language/move-model/src/ast.rs
- language/move-model/src/builder/exp_translator.rs
- language/move-model/src/builder/module_builder.rs
- language/move-prover/boogie-backend/src/boogie_helpers.rs
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/bytecode/src/stackless_bytecode.rs
- language/move-prover/bytecode/src/stackless_bytecode_generator.rs
- language/move-prover/interpreter/src/concrete/evaluator.rs
- language/move-prover/interpreter/src/concrete/player.rs
- language/move-prover/tests/sources/functional/consts.exp
- language/move-prover/tests/sources/functional/consts.move
- language/move-prover/tools/spec-flatten/src/ast_print.rs
- Extended the move-model with `AddressArray` to support constant vectors of addresses
- They can be defined in `const A:vector<address> = [...]` at the module level and in `let A = vector<address>[...]` in a function body. This commit supports both cases.
- Added some test cases
To support constant vector of address
Yes
cargo test
> [Move Prover] Support constant vector of addresses

- language/move-stdlib/docs/fixed_point32.md
- language/move-stdlib/sources/fixed_point32.move
- language/move-stdlib/tests/fixedpoint32_tests.move
I added more helper functions to `fixed_point32`, namely:
- min
- max
- create_from_u64
- floor
- ceil
- round
Addressed: #393 
Yes.
- 100% Test coverage
- Move spec added
> [stdlib] Added more helper function for fixed_point32

- language/move-stdlib/docs/vector.md
- language/move-stdlib/sources/vector.move
> [move-stdlib] fix vector docs

- language/move-compiler/src/command_line/compiler.rs
- language/move-compiler/src/command_line/mod.rs
- language/move-compiler/src/lib.rs
- language/move-compiler/src/parser/filter.rs
- language/move-compiler/src/parser/mod.rs
- language/move-compiler/src/shared/mod.rs
- language/move-compiler/src/unit_test/filter_test_members.rs
- language/move-compiler/src/verification/ast_filter.rs
- language/move-compiler/src/verification/mod.rs
- language/move-compiler/tests/move_check/verification/cross_module_invalid.exp
- language/move-compiler/tests/move_check/verification/cross_module_invalid.move
- language/move-compiler/tests/move_check/verification/cross_module_valid.move
- language/move-compiler/tests/move_check/verification/double_annotation.move
- language/move-compiler/tests/move_check/verification/double_annotation.verification.exp
- language/move-compiler/tests/move_check/verification/single_module_invalid.exp
- language/move-compiler/tests/move_check/verification/single_module_invalid.move
- language/move-compiler/tests/move_check/verification/single_module_valid.move
- language/move-compiler/tests/move_check_testsuite.rs
- language/move-model/src/lib.rs
As title suggests, this is an implementation of the `#[verify_only]`
annotation that can be used in a way that is similar to `#[test_only]`.
The semantics of `#[verify_only]` is the following:
Any AST element (in both source of in the library definitions)
annotated with the `#[verify_only]` attribute will be removed
after parsing, unless the `verify` flag is set when invoking
the compiler.
`#[verify_only]` has no interaction with unit-testing related
attributes such as `#[test]`, `#[test_only]` or `#[abort]`,
`#[expect_failure]` etc. A function that is marked `#[verify_only]` has
no knowledge of that a `#[test_only]` function might exist, unless both
`verify` and `testing` flags are set when invoking the compiler.
A large portion of this PR is in fact an refactoring of the `#[test_only]` …
> [move-compiler] implement the `#[verify_only]` attribute

- language/move-prover/boogie-backend/src/options.rs
- language/move-prover/bytecode/src/options.rs
- language/move-prover/bytecode/src/pipeline_factory.rs
Adds two new options to the Move prover:
- `prover.skip_loop_analysis`, which skips the `LoopAnalysisProcessor` in the proving pipeline
- `backend.loop_unroll`, which is an integer that specifies the `-loopUnroll` argument to Boogie
This allows simple, low iteration count loops to be proven without requiring specifying invariants.
Yes
Ran this on my own code
> Support loop unrolling in Move prover backend

- language/move-compiler/src/shared/mod.rs
- language/move-model/src/lib.rs
When constructing address aliases for the move model, use the
`NamedAddressMap` produced by the compiler instead of a handwritten one.
This allows move-model (and hence move-prover) to work even when source
and deps paths are supplied in directory format (instead of via the
package system).
Code consistency and maintainance
Yes
CI
> [move-model] re-use the address map produced by move compiler

- language/move-stdlib/src/natives/mod.rs
As discussed during one of the recent community meetings, it would be convenient to allow developers (temporarily) keep their debug printing code around in published modules while debugging their code on chain.
The intention is to keep be able to link with the `debug` module but have its (native) functions do something useful (that is actually print some info) only when testing. This is why the code of the debug native functions is gated on the "testing" feature. Unfortunately, inclusion of the `debug` module (or rather its native methods) is also gated on the "testing" feature which will throw an error during native function verification (as the Move-level functions will not have their Rust equivalents that are currently compiled away outside testing). This PR removes this restriction. …
> [move-test] Inclusion of debug module no longer gated by the testing feature

- language/move-model/src/well_known.rs
- language/move-prover/boogie-backend/src/boogie_helpers.rs
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/tests/sources/functional/type_reflection.move
This commit introduces preliminary support on verifying code that uses reflection to obtain type information at runtime.
We use a hyperthetical (and intrinsic) call
`fun extension::type_info::type_name<T>(): String` that returns the type name of `T`.
Being a pure function, this reflection function can be called from the spec context as well.
In handling reflection, the high-level idea is:
- if `T` is statically known when `type_name<T>` is called, replace this call with a constant
- if `T` is unknown, full or partially, when this call is invoked, replace the `type_name` for `T` with a fresh variable `var #T_name: Vec int`, in particular:
- if `T` is fully unknown, `type_name<T>` will be `#T_name`
- if `T` is partially unknown (e.g., `type_name<vector<T>>`), then the `type_name` call will …
> [move-prover] preliminary support for type reflection

- language/move-model/src/well_known.rs
- language/move-prover/boogie-backend/src/boogie_helpers.rs
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/bytecode/src/mono_analysis.rs
- language/move-prover/tests/sources/functional/type_reflection.exp
- language/move-prover/tests/sources/functional/type_reflection.move
The `type_of` primitive is another type reflection feature supported by the move prover:
At its core, the `type_of` function returns information about a user-defined struct type:
```move
struct TypeInfo has copy, drop, store {
account_address: address,
module_name: vector<u8>,
struct_name: vector<u8>,
}
public native fun type_of<T>: TypeInfo;
```
This is similar to the `type_name` feature with the following complication:
- `type_of<T>` will panic if `T` is not a user-defined struct type. `type_of<vector<bool>>` will cause the Move VM to abort. This needs to be captured by the prover as well. On the other hand, `type_name` will never panic and will always return a canonical representation of the passed in type tag.
- `type_of<T>` does not care about the type arguments of the struct type. …
> [move-prover] model `type_of` which returns the struct tag triple

- language/documentation/examples/diem-framework/move-packages/DPN/sources/CRSN.move
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/bytecode/src/function_data_builder.rs
- language/move-prover/bytecode/src/loop_analysis.rs
- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/bytecode/tests/mono_analysis/test.exp
- language/move-prover/bytecode/tests/spec_instrumentation/generics.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/loop.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/loop.move
- language/move-prover/interpreter/src/concrete/player.rs
- language/move-prover/tests/sources/functional/loop_with_two_back_edges.move
- language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
- language/move-prover/tests/sources/functional/macro_verification.exp
The `havoc` operator has been modeled as:
```
() := havoc($i);
```
i.e., 0 output and 1 input.
This commit switches the src and dest pair into
```
$i := havoc();
```
This is in fact closer to the semantic of `havoc`: it re-assigns the target with an arbitrary value. therefore, the target should be on the receiving end.
This has important effect on our program analysis passes, especially reaching definition analysis and live-var analysis.
Fix #466
Yes
CI
> [move-prover] switch src/dst pair for the havoc operator

- language/extensions/move-table-extension/sources/Table.spec.move
- language/move-model/src/builder/model_builder.rs
- language/move-model/src/builder/module_builder.rs
- language/move-model/src/intrinsics.rs
- language/move-model/src/lib.rs
- language/move-model/src/model.rs
- language/move-model/src/pragmas.rs
- language/move-model/src/well_known.rs
- language/move-model/tests/sources/intrinsic_decl_err.exp
- language/move-model/tests/sources/intrinsic_decl_err.move
- language/move-model/tests/sources/intrinsic_decl_ok.exp
- language/move-model/tests/sources/intrinsic_decl_ok.move
- language/move-model/tests/sources/pragmas_err.exp
- language/move-model/tests/sources/pragmas_err.move
- language/move-prover/boogie-backend/src/boogie_helpers.rs
- language/move-prover/boogie-backend/src/boogie_wrapper.rs
- language/move-prover/boogie-backend/src/lib.rs
- language/move-prover/boogie-backend/src/prelude/native.bpl
- language/move-prover/boogie-backend/src/prelude/prelude.bpl
- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/clean_and_optimize.rs
- language/move-prover/bytecode/src/function_target.rs
- language/move-prover/bytecode/src/mono_analysis.rs
- language/move-prover/tests/sources/functional/verify_custom_table.exp
- language/move-prover/tests/sources/functional/verify_custom_table.move
This PR allows intrinsic types and functions to be declared in struct spec block.
This feature is best highlighted in the following code:
```move
module 0x42::M {
struct MyTable1<phantom K, phantom V> {}
native fun new<K, V>(): MyTable1<K, V>;
native fun destroy_empty<K, V>(t: MyTable1<K, V>);
native fun borrow_mut<K, V>(t: &mut MyTable1<K, V>, k: K): &mut V;
native fun length<K, V>(t: &MyTable1<K, V>): u64;
spec native fun spec_len<K, V>(t: MyTable1<K, V>): num;
spec native fun spec_set<K, V>(t: MyTable1<K, V>, k: K, v: V): MyTable1<K, V>;
spec native fun spec_get<K, V>(t: MyTable1<K, V>, k: K): V;
spec MyTable1 {
pragma intrinsic = map,
map_new = new,
map_destroy_empty = destroy_empty,
map_borrow_mut = borrow_mut,
map_len = length,
map_spec_len = spec_len,
map_spec_get = spec_get, …
```
> [move-model] intrinsic declarations in struct spec

- language/move-binary-format/src/deserializer.rs
- language/move-binary-format/src/unit_tests/signature_token_tests.rs
This fixes a bug in the binary format deserializer regarding the handling of SignatureToken. The current implementation accepts a struct instantiation with arity 0 and will wrongfully apply the type constructor to the next argument.
```
[
SerializedType::STRUCT_INST as u8,
0x0, /* struct handle idx */
0x0, /* arity */
SerializedType::BOOL as u8,
]
```
This gets it fixed by checking the arity and adds a few tests to ensure this case is covered.
> [binary format] fix signature token deserialization bug

- x.toml
There's a warning that says that this field has been renamed.  This fixes it.
Yes
```
cargo x clippy
```
> [clippy] Fix clippy rename warning

- language/move-binary-format/src/compatibility.rs
- language/move-binary-format/src/unit_tests/compatibility_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/control_flow_tests.rs
- language/move-bytecode-verifier/src/verifier.rs
- language/move-vm/integration-tests/src/tests/nested_loop_tests.rs
- language/move-vm/runtime/src/runtime.rs
- language/tools/move-cli/src/sandbox/utils/mod.rs
This adds a dynamic global flag which if set, lets the compatibility check treat friend functions like private functions. The feature is not on by default because it assumes that modules are compiled and published on package granularity level. On package level, we can assume that each call site of the friend function has been updated to the changed friend function as well.
Yes
NA
> [compatibility] Relax compatibility for friends

- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/function_target_pipeline.rs
- language/move-prover/bytecode/src/verification_analysis.rs
- language/move-prover/tests/sources/functional/recursive_move_fun.move
Recursive Move functions are not currently supported in Move prover.
This is because two passes in the transformation pipeline does not support it:
- borrow analysis does not support recursive functions that returns mutable references (`&mut`), and
- verification analysis does not know whether to mark a recursive function (or a mutually recursive function) inline or verify.
This commit does not add any functionality to support either analysis, but does allow the following situation to pass:
- if a recursive Move function does not return `&mut`, we allow it to pass the borrow analysis as it does not affect the borrow graph.
- Check that all recursive Move functions should be marked with `pragma opaque`. In this way, we essentially bypass the problem of whether to generate a Boogie …
> [move-prover] allow recursive move function

- language/move-model/src/builder/exp_translator.rs
- language/move-model/tests/sources/if_else_ok.exp
- language/move-model/tests/sources/if_else_ok.move
During the process of translation, if an error already happened, i.e., the move function is already considered non-pure, the following-up errors can be misleading. As shown in the test case.
This commit stops showing an error on unable to find the correct spec fun candidate due to type unification failures (which is already messed up when there is a previous error).
Improve UX
Yes
- CI
- A new test case
> [move-model] do not report errors when translating a non-pure fun to spec fun

- Cargo.lock
- language/tools/move-package/Cargo.toml
In the Aptos repo we were alerted by automated security auditing scanning to a potential issue with the `lock_api` dependency: https://nvd.nist.gov/vuln/detail/CVE-2020-35910. This dependency originates eventually from the move package:
```
cargo tree -i lock_api@0.3.4
lock_api v0.3.4
└── parking_lot v0.10.2
└── named-lock v0.1.1
└── move-package v0.1.0 (https://github.com/move-language/move?rev=59265662d0a44ba53b09ba3c4b2248efdf08c622#59265662)
```
This PR addresses this problem by updating all uses uses of `named-lock@0.1.1` to `0.2.0`. This results in an upgrade of `parking_lot` and then `lock_api` accordingly. After making these changes, `cargo tree -i lock_api@0.3.4` returns nothing, it all uses `cargo tree -i lock_api@0.4.6` now.
Yes
```
cargo build
```
Beyond that, I'm not too …
> [move-package] Upgrade named_lock from 0.1.1 to 0.2.0

- language/tools/move-package/src/lib.rs
- language/tools/move-package/src/resolution/resolution_graph.rs
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps/Move.exp
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_address_assigned/Move.exp
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_address_not_assigned_with_dev_assignment/Move.exp
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/Move.exp
- language/tools/move-package/tests/test_sources/compilation/diamond_problem_backflow_resolution/Move.exp
- language/tools/move-package/tests/test_sources/compilation/diamond_problem_no_conflict/Move.exp
- language/tools/move-package/tests/test_sources/compilation/multiple_deps_rename/Move.exp
- language/tools/move-package/tests/test_sources/compilation/multiple_deps_rename_one/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep_assigned_address/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep_renamed/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep_with_scripts/Move.exp
- language/tools/move-package/tests/test_sources/compilation/test_symlinks/Move.exp
- language/tools/move-package/tests/test_sources/parsing/invalid_identifier_package_name/Move.exp
- language/tools/move-package/tests/test_sources/parsing/minimal_manifest/Move.exp
- language/tools/move-package/tests/test_sources/resolution/basic_no_deps/Move.exp
- language/tools/move-package/tests/test_sources/resolution/basic_no_deps_address_assigned/Move.exp
- language/tools/move-package/tests/test_sources/resolution/basic_no_deps_address_not_assigned_with_dev_assignment/Move.exp
- language/tools/move-package/tests/test_sources/resolution/dep_good_digest/Move.exp
- language/tools/move-package/tests/test_sources/resolution/diamond_problem_backflow_resolution/Move.exp
- language/tools/move-package/tests/test_sources/resolution/diamond_problem_no_conflict/Move.exp
- language/tools/move-package/tests/test_sources/resolution/multiple_deps_rename/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_assigned_address/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_multiple_of_same_name/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_reassigned_address/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_unification_across_local_renamings/Move.exp
Currently, the cached packages are never updated, even though they check out the corresponding git repo.  This will now just fetch and reset accordingly to update the local cached version.  Note, this will require a network connection for whenever the compiler is run with a git dependency (though, normally you need it if you don't have it cached).
https://github.com/move-language/move/issues/468
Yes
Tested with the Move CLI, it now properly downloads to the latest state.
> [move-package] Update cached git packages to latest state automatically

- language/move-vm/runtime/src/interpreter.rs
- language/move-vm/runtime/src/loader.rs
- Add paranoid check to protect the VM against a native function that return a number of values inconsistent with its declared return types. The verifier can't help us with this; we are at the mercy of native function implementers
- Remove a redundant wrapper function and have `execute_main` take ownership of the `Interpreter` to ensure that it is used correctly
- Add comments about where operand stack sharing happens
- Remove one out-of-date comment about the create_account bytecode!
> [interpreter] audit operand stack usage

- language/tools/move-package/src/lib.rs
- language/tools/move-package/src/resolution/resolution_graph.rs
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps/Move.exp
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_address_assigned/Move.exp
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_address_not_assigned_with_dev_assignment/Move.exp
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/Move.exp
- language/tools/move-package/tests/test_sources/compilation/diamond_problem_backflow_resolution/Move.exp
- language/tools/move-package/tests/test_sources/compilation/diamond_problem_no_conflict/Move.exp
- language/tools/move-package/tests/test_sources/compilation/multiple_deps_rename/Move.exp
- language/tools/move-package/tests/test_sources/compilation/multiple_deps_rename_one/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep_assigned_address/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep_renamed/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep_with_scripts/Move.exp
- language/tools/move-package/tests/test_sources/compilation/test_symlinks/Move.exp
- language/tools/move-package/tests/test_sources/parsing/invalid_identifier_package_name/Move.exp
- language/tools/move-package/tests/test_sources/parsing/minimal_manifest/Move.exp
- language/tools/move-package/tests/test_sources/resolution/basic_no_deps/Move.exp
- language/tools/move-package/tests/test_sources/resolution/basic_no_deps_address_assigned/Move.exp
- language/tools/move-package/tests/test_sources/resolution/basic_no_deps_address_not_assigned_with_dev_assignment/Move.exp
- language/tools/move-package/tests/test_sources/resolution/dep_good_digest/Move.exp
- language/tools/move-package/tests/test_sources/resolution/diamond_problem_backflow_resolution/Move.exp
- language/tools/move-package/tests/test_sources/resolution/diamond_problem_no_conflict/Move.exp
- language/tools/move-package/tests/test_sources/resolution/multiple_deps_rename/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_assigned_address/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_multiple_of_same_name/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_reassigned_address/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_unification_across_local_renamings/Move.exp
This fixes the issues with the fetch refresher that wasn't doing it correctly.  Now it does properly fetch.
Yes
I've tested manually, I will copy some outputs here soon
> [move-package] Make git fetch dependencies refresh on by default

- language/move-binary-format/src/compatibility.rs
- language/move-binary-format/src/proptest_types/functions.rs
- language/move-bytecode-verifier/src/instruction_consistency.rs
Cherrypick #522 into aptos branch
Verifies range of an instruction, as well as corrects an outdated comment.
> [vm] Fixes

- Cargo.lock
- language/move-core/types/src/language_storage.rs
There's limited value and a lot of wasted resources by leaving this limited to serde's limits. Recursion is dangerous.
> [types] make type tag nesting limited

- language/extensions/async/move-async-vm/src/async_vm.rs
- language/move-binary-format/src/normalized.rs
- language/move-command-line-common/src/types.rs
- language/move-core/types/src/language_storage.rs
- language/move-core/types/src/parser.rs
- language/move-core/types/src/proptest_types.rs
- language/move-core/types/src/value.rs
- language/move-prover/bytecode/src/packed_types_analysis.rs
- language/move-prover/interpreter/src/concrete/ty.rs
- language/move-prover/move-abigen/src/abigen.rs
- language/move-vm/runtime/src/data_cache.rs
- language/move-vm/runtime/src/loader.rs
- language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
- language/tools/move-resource-viewer/src/fat_type.rs
- language/tools/move-resource-viewer/src/lib.rs
- language/tools/read-write-set/dynamic/src/dynamic_analysis.rs
Currently a single TypeTag consumes 96 bytes because of the inlined StructTag (88 bytes), it starts to bloat up with nested TypeTag::Vector(TypeTag).
This commit reduces the size from 96 to 16 bytes, it doesn't fully solve the problem but reduces the impact by 6x.
> Make TypeTag enum use less memory

- language/move-vm/runtime/src/interpreter.rs
- language/move-vm/test-utils/src/gas_schedule.rs
- language/move-vm/types/src/gas.rs
This passes some additional info to the gas meter when calling functions to make gas metering more robust
- Number of locals
- (Natives only) Views into the return values
> [gas] pass more info to the gas meter when calling functions

- language/move-core/types/src/language_storage.rs
- language/move-core/types/src/lib.rs
- language/move-core/types/src/safe_serialize.rs
Cherry picked from #529.
This is an alternative version of what #528 and the previous for limitation of nesting provides, having a significant lower footprint.
This approach installs custom serializers at the recursion points of the `TypeTag` enum. Those serializer use a thread local to track the nesting of the type tag, both for serialization and deserialization.
The usage of a thread local is safe and a common technique to provide extra state for implementations which miss it (e.g. serde). A given thread has a single execution stack and this will always count the depth counter consistently up and down. Because Rust has no exceptions are other exit points, this cannot be corrupted. Possibly, thread locals may cause inefficiency. However, we expect TypeTags to be small (a few …
> [types] limit nesting of types via state

- language/move-core/types/src/parser.rs
Limit parsing of nested type tags in the type parser
> [types] limit parsing of nested TypeTag

- language/move-stdlib/src/natives/debug.rs
- language/move-vm/runtime/src/interpreter.rs
- language/move-vm/test-utils/src/gas_schedule.rs
- language/move-vm/types/src/gas.rs
- language/move-vm/types/src/values/values_impl.rs
This adds some additional callbacks to the gas meter trait and fine tune some existing ones so to allow us to keep track of the VM's memory usage precisely.
> [gas] share even more info with the gas meter

- language/move-vm/runtime/src/interpreter.rs
No longer needed now that `execute_main` takes ownership of the interpreter.
> [move-vm] eliminate use of `std::mem::take`

- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/native_functions.rs
- language/move-vm/runtime/src/session.rs
- language/move-vm/types/src/loaded_data/runtime_types.rs
- Added API that generates a MoveTypeLayout from a loaded Type, but adds all struct tag information
- Exposed new loader API in the native context
- Exposed the function in the session for completeness
- I have some native function code for tests that fully walks a MoveValue, but to do so, I really need the type information for the struct. To get this, I need a MoveTypeLayout that uses MoveStructLayout::WithTypes instead of Runtime
- Happy to put this somewhere other than the loader (the caching of the results is nice but not super important). Maybe @vgao1996 will have some ideas
- Using it on another branch, and will be used extensively (so we will effectively have end-to-end tests for this function).
- But we should probably have tests for this... just a bit hard at the moment as none …
> [natives][loader] New API for fully annotated MoveTypeLayout

- language/tools/move-cli/README.md
Just fixed the wrong case of an address.
Yes.
> fix(move-cli): fix the case for `0x..0f` address in README file

- language/move-compiler/src/naming/fake_natives.rs
The phase in the compiler which maps calls to vector functions to opcodes only catches cases like `std::vector::fun`. If a user has `0x1::vector::fun` (which he should be free to do) no resolution to opcodes happens, and the legacy native functions in the library are called. Those functions, however, should be deactivated as they represent a further surface of concern of security and gas metering.
This PR lets the vector functions resolve to opcodes if either (a) the symbolic address name is `std` (b) or the address resolves to `0x1`.
> [compiler] Resolve 0x1::vector calls to opcodes

- language/move-binary-format/src/file_format.rs
- language/move-binary-format/src/unit_tests/binary_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/code_unit_tests.rs
This is a duplicate of #524. Just to make sure the changes on the aptos branch could be included in upstream as much as possible if the community agrees.
There is an off-by-one error in the assertion on 
`assert!(pc <= u16::max_value() - 2 && (pc as usize) < code.len())`
While the RHS, i.e., `(pc as usize) < code.len()` is correct, the LHS has the off-by-one issue.
The deserializer guarantees that code unit length is at max `u16::MAX`, i.e., `code.len() <= u16::MAX`. Therefore, it is possible to construct a code unit with length `u16::MAX` which is filled by `u16::MAX - 1` `nop` operations and one `ret` operation, as shown in the added test case `test_max_number_of_bytecode`.
In this test case:
- The whole `nop + ret` code unit will be considered as a single basic block and the bytecode …
> [bytecode-verifier] fix an off-by-one error

- language/move-bytecode-verifier/src/absint.rs
- language/move-bytecode-verifier/src/lib.rs
- language/move-bytecode-verifier/src/regression_tests/mod.rs
- language/move-bytecode-verifier/src/regression_tests/reference_analysis.rs
This aborts the abstract interpreter of the bytecode verifier at the first analysis error. Some analyses aren't robust otherwise. Also adds a test case.
> [verifier] Hardening reference analysis

- language/evm/move-to-yul/tests/TestABINative.exp
- language/extensions/async/move-async-vm/tests/sources/AccountStateMachine.exp
- language/move-compiler/src/cfgir/borrows/mod.rs
- language/move-compiler/src/cfgir/translate.rs
- language/move-compiler/src/command_line/compiler.rs
- language/move-compiler/src/expansion/translate.rs
- language/move-compiler/src/hlir/translate.rs
- language/move-compiler/src/naming/translate.rs
- language/move-compiler/src/shared/mod.rs
- language/move-compiler/src/typing/globals.rs
- language/move-compiler/src/typing/translate.rs
- language/move-compiler/transactional-tests/tests/evaluation_order/lazy_assert.exp
- language/tools/move-cli/tests/build_tests/build_with_warnings/Move.toml
- language/tools/move-cli/tests/build_tests/build_with_warnings/args.exp
- language/tools/move-cli/tests/build_tests/build_with_warnings/args.txt
- language/tools/move-cli/tests/build_tests/build_with_warnings/modules/m.move
- language/tools/move-cli/tests/build_tests/build_with_warnings/sources/m.move
- Fix compiler optimizations being erroneously blocked by all diagnostics, not just errors
- Fix internal ICE checks for the compiler's reference safety checks
- @awelc found a bug where optimizations weren't done in the presence of warnings.
- Optimizations are not currently observable in the test suite
> [move-compiler] Fix optimizations blocked by warnings

- language/move-bytecode-verifier/src/absint.rs
- language/move-bytecode-verifier/src/lib.rs
- language/move-bytecode-verifier/src/regression_tests/mod.rs
- language/move-bytecode-verifier/src/regression_tests/reference_analysis.rs
This aborts the abstract interpreter of the bytecode verifier at the first analysis error. Some analyses aren't robust otherwise. Also adds a regression test which caused the discovery of this.
> [verifier] Hardening reference analysis (cherry-pick #553)

- language/move-bytecode-verifier/transactional-tests/tests/type_safety/vector_ops_type_mismatch.exp
- language/move-bytecode-verifier/transactional-tests/tests/type_safety/vector_ops_type_mismatch.mvir
We only have type safety tests for `vec_pack_0` and `vec_unpack_0`
> [tests] add type safety tests for vec_pack_n and vec_unpack_n for n > 0

- Cargo.lock
- Cargo.toml
- devtools/x-lint/src/runner.rs
- language/move-binary-format/Cargo.toml
- language/move-binary-format/src/check_bounds.rs
- language/move-binary-format/src/file_format.rs
- language/move-bytecode-verifier/fuzz/.gitignore
- language/move-bytecode-verifier/fuzz/Cargo.toml
- language/move-bytecode-verifier/fuzz/README.md
- language/move-bytecode-verifier/fuzz/fuzz_targets/code_unit.rs
- language/move-bytecode-verifier/fuzz/fuzz_targets/compiled_module.rs
- language/move-bytecode-verifier/fuzz/fuzz_targets/mixed.rs
- language/move-bytecode-verifier/src/regression_tests/reference_analysis.rs
- language/move-bytecode-verifier/transactional-tests/tests/check_bounds/128_params_and_128_locals.exp
- language/move-bytecode-verifier/transactional-tests/tests/check_bounds/128_params_and_128_locals.mvir
- language/move-bytecode-verifier/transactional-tests/tests/check_bounds/1_param_and_255_locals.exp
- language/move-bytecode-verifier/transactional-tests/tests/check_bounds/1_param_and_255_locals.mvir
- language/move-core/types/Cargo.toml
- language/move-core/types/src/account_address.rs
- language/move-core/types/src/identifier.rs
- language/move-core/types/src/metadata.rs
- x.toml
This adds a fuzzing crate and a few targets for `CompileModule` to the bytecode verifier. The rather rudimentary `cargo-fuzz` is used ([see here](https://rust-fuzz.github.io/book)) as the more sophisticated tools like `honggfuzz` don't work on Apple silicon. Using this (and other fuzzing tools) requires to derive `arbitray::Arbitray` (not to be mistaken with proptests `Arbitrary`) which allows to derive values from bit images, as the fuzzer produces.
This fuzzer infra was capable to find a recent (already fixed) bug in stack balancing in reference analysis, caused by continuing analysis after an error occured. It also discovered (for now) the following new bug: if the number of locals + parameters is larger than 255 certain analysis will go wrong, as `type LocalIndex = u8`. This was …
> [fuzzing] Add fuzzing infra for bytecode verifier + fix bug

- language/move-binary-format/src/normalized.rs
- language/move-core/types/src/vm_status.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/transactional-tests/tests/recursion/runtime_type_many_nodes.exp
- language/move-vm/transactional-tests/tests/recursion/runtime_type_many_nodes.mvir
Restrict the number of allowed type terms in instantiation to 128. This should prevent that malicious code produces OOM attacks via type instantiation.
> [move] Restrict size of type terms

- language/evm/move-to-yul/tests/TestABINative.exp
- language/extensions/async/move-async-vm/tests/sources/AccountStateMachine.exp
- language/move-compiler/src/cfgir/borrows/mod.rs
- language/move-compiler/src/cfgir/translate.rs
- language/move-compiler/src/command_line/compiler.rs
- language/move-compiler/src/expansion/translate.rs
- language/move-compiler/src/hlir/translate.rs
- language/move-compiler/src/naming/translate.rs
- language/move-compiler/src/shared/mod.rs
- language/move-compiler/src/typing/globals.rs
- language/move-compiler/src/typing/translate.rs
- language/move-compiler/transactional-tests/tests/evaluation_order/lazy_assert.exp
- language/tools/move-cli/tests/build_tests/build_with_warnings/Move.toml
- language/tools/move-cli/tests/build_tests/build_with_warnings/args.exp
- language/tools/move-cli/tests/build_tests/build_with_warnings/args.txt
- language/tools/move-cli/tests/build_tests/build_with_warnings/modules/m.move
- language/tools/move-cli/tests/build_tests/build_with_warnings/sources/m.move
* [move-compiler] Fix optimizations blocked by warnings
- Fix compiler optimizations being erroneously blocked by all diagnostics, not just errors
- Fix internal ICE checks for the compiler's reference safety checks
* fixup! [move-compiler] Fix optimizations blocked by warnings
* fixup! fixup! [move-compiler] Fix optimizations blocked by warnings
* fixup! fixup! fixup! [move-compiler] Fix optimizations blocked by warnings
* fixup! fixup! fixup! fixup! [move-compiler] Fix optimizations blocked by warnings
* fixup! fixup! fixup! fixup! fixup! [move-compiler] Fix optimizations blocked by warnings
To cherry pick  #552 to the aptos branch
yes
cargo test
> [move-compiler] Fix optimizations blocked by warnings (cherry pick: #552)

- language/move-bytecode-verifier/src/instantiation_loops.rs
- Fixed bug with instantiation loop checker that filtered before enumerating
- Found this annoying bug when adding some native functions
- I do not think it can be tested without lazy native loading
> [bug fix] Fixed bug with natives in instantiation loop checker

- language/move-core/types/src/vm_status.rs
We added a new error code STORAGE_WRITE_LIMIT_REACHED under the EXECUTION category and realized there's a debug_assert!() that prevents it from being part of a `VmStatus::Error()`. After discussion, it seems reasonable to allow all EXECUTION type of codes there.
> allow all codes under EXECUTION category for VmStatus::Error

- language/move-stdlib/docs/fixed_point32.md
- language/move-stdlib/sources/fixed_point32.move
This seems to be broken by a z3 upgrade. Going to force land because of broken CI.
> [move-prover] Deactivate verification of ceil because it times out

- language/move-prover/tests/sources/functional/opaque_native.move
This demonstrates that some native functions can be defined purely in Move as good as they would be defined in Boogie.
We'd need to re-implement generic axioms in presence of monomoprhization to make this also work for generic functions.
> [prover] Adding a test to validate whether axiomatized natives work

- language/move-prover/bytecode/src/spec_instrumentation.rs
When a quantified expression contains a sub expression with a bound variable, the prover will generate a track_exp_sub for this sub expression where the bound variable becomes free. This PR adds logic to filter out these expressions when generating traces for verification failure. 
close #600 
Yes
> [Move Prover] Prevent generating track_exp_sub for exps with free variables

- language/move-prover/move-docgen/src/docgen.rs
The placeholder produced all modules in the transitive closure of dependencies. We only want to see the target modules here. For example, if this is used to document a package, the index should only contain the modules declared in that package.
> [docgen] Fix `{{move-index}}` placeholder

- .cargo/config
- .github/workflows/ci-pre-land.yml
- Cargo.toml
- scripts/dev_setup.sh
`ld`, the default linker on linux, consumes a lot of memory and does not run in parallel. This PR switches us over to `lld`, which should greatly reduce memory consumption and improve linking speed on machines with many cores. Here's a comparison on a 64-core VM:
- `ld`: 17GB Ram, 48.21s
- `lld`: 4.5GB Ram, 34.40s
The reduction in memory consumption also allows us to switch back to debug build in CI, **cutting the running time from 33m down to 15m (with cache)**.
Note: this does require `lld` to be installed on linux platforms, which is now included in the dev setup script. However existing developers may need to re-run the script or install `lld` manually.
> [build] switch to lld on linux and optimize ci build

- language/extensions/move-table-extension/sources/Table.spec.move
- language/move-model/src/pragmas.rs
- language/move-prover/boogie-backend/src/lib.rs
- language/move-prover/boogie-backend/src/prelude/native.bpl
- language/move-prover/tests/sources/functional/verify_custom_table.exp
- language/move-prover/tests/sources/functional/verify_custom_table.move
- Added two pragmas for the intrinsic table implementation
- map_del_return_key: a delete function that returns not only the value but also the key. `simple_map` needs this because keys are not drop-able there.
- map_add_override_if_exists: an add function that override the value rather than abort when the key already exists. This models the `upsert` functions in the table modules
- Modified the meaning of `map_spec_set` so that the length only increases when a new entry is added.
To add necessary pragmas for table
yes
cargo test
> [Prover]  Extends the intrinsic table implementation by adding more pragmas

- language/tools/move-package/src/lib.rs
- language/tools/move-package/src/resolution/resolution_graph.rs
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps/Move.exp
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_address_assigned/Move.exp
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_address_not_assigned_with_dev_assignment/Move.exp
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/Move.exp
- language/tools/move-package/tests/test_sources/compilation/diamond_problem_backflow_resolution/Move.exp
- language/tools/move-package/tests/test_sources/compilation/diamond_problem_no_conflict/Move.exp
- language/tools/move-package/tests/test_sources/compilation/multiple_deps_rename/Move.exp
- language/tools/move-package/tests/test_sources/compilation/multiple_deps_rename_one/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep_assigned_address/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep_renamed/Move.exp
- language/tools/move-package/tests/test_sources/compilation/one_dep_with_scripts/Move.exp
- language/tools/move-package/tests/test_sources/compilation/test_symlinks/Move.exp
- language/tools/move-package/tests/test_sources/parsing/invalid_identifier_package_name/Move.exp
- language/tools/move-package/tests/test_sources/parsing/minimal_manifest/Move.exp
- language/tools/move-package/tests/test_sources/resolution/basic_no_deps/Move.exp
- language/tools/move-package/tests/test_sources/resolution/basic_no_deps_address_assigned/Move.exp
- language/tools/move-package/tests/test_sources/resolution/basic_no_deps_address_not_assigned_with_dev_assignment/Move.exp
- language/tools/move-package/tests/test_sources/resolution/dep_good_digest/Move.exp
- language/tools/move-package/tests/test_sources/resolution/diamond_problem_backflow_resolution/Move.exp
- language/tools/move-package/tests/test_sources/resolution/diamond_problem_no_conflict/Move.exp
- language/tools/move-package/tests/test_sources/resolution/multiple_deps_rename/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_assigned_address/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_multiple_of_same_name/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_reassigned_address/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_unification_across_local_renamings/Move.exp
This is an improvement on the current behavior of package caching in the Move package manager.  This is not required, but would be great to get in for the CLI caching updates.
I'm just letting this sit until the next time there are cherry picks into the branch
Yes
The previous PR for this change #513
> [move-package] cherry-pick Fix git depencency refresh fetch (#513)

- language/tools/move-package/src/resolution/resolution_graph.rs
- language/tools/move-package/tests/test_sources/resolution/one_dep_unification_across_local_renamings_with_resolution/Move.exp
Spotted that there was no space between "in" and "package" in this error message, because of the newline escape.
Yes.
:eyes:
> [resolution][EASY] Fix missing space in error message

- language/move-compiler/src/cfgir/borrows/mod.rs
- language/move-compiler/tests/move_check/borrows/unused_ref.exp
- language/move-compiler/tests/move_check/borrows/unused_ref.move
- Assert is left over from before the error/warning refactor. It shouldn't be necessary
- Fix a compiler crash
- New test
> [move-compiler][crash fix] Removed unnecessary assert

- language/move-model/src/ty.rs
A Move model `Type` can be converted into a `normalized::Type`, but the logic for doing this previously refused to normalize a type behind a reference.
> [model] allow conversion of model reference types into normalized types

- language/move-stdlib/src/natives/debug.rs
- language/move-vm/runtime/src/interpreter.rs
- language/move-vm/test-utils/src/gas_schedule.rs
- language/move-vm/types/src/gas.rs
- language/move-vm/types/src/values/values_impl.rs
This modifies a few callbacks of the `GasMeter` trait and adds a few more, allowing the client to implement more functionalities (e.g. a memory usage tracker)
(Cherry-picking https://github.com/move-language/move/pull/531 and https://github.com/move-language/move/pull/536.)
> [gas] share more info with the gas meter

- language/move-prover/move-docgen/src/docgen.rs
- language/move-prover/move-docgen/tests/sources/different_visbilities.spec_inline.md
- language/move-prover/move-docgen/tests/sources/different_visbilities.spec_inline_no_fold.md
- language/move-prover/move-docgen/tests/sources/different_visbilities.spec_separate.md
- language/move-prover/move-docgen/tests/sources/root_template.spec_inline.md
- language/move-prover/move-docgen/tests/sources/root_template.spec_inline_no_fold.md
- language/move-prover/move-docgen/tests/sources/root_template.spec_separate.md
- "entry" keyword was missing in the function headers
- this PR displays the keyword "entry" properly
This PR resolves https://github.com/move-language/move/issues/631
To properly display the "entry" keyword in the function headers
yes
cargo test
> [docgen] displays "entry" in the function headers of entry functions

- language/move-analyzer/src/symbols.rs
- language/tools/move-cli/src/base/build.rs
- language/tools/move-cli/src/base/info.rs
- language/tools/move-cli/src/base/test.rs
- language/tools/move-cli/src/sandbox/commands/test.rs
- language/tools/move-cli/tests/build_tests/simple_build_with_docs/args.exp
- language/tools/move-package/src/lib.rs
- language/tools/move-package/src/resolution/resolution_graph.rs
- language/tools/move-package/tests/package_hash_skips_non_move_files.rs
- language/tools/move-package/tests/test_additional_addresses.rs
- language/tools/move-package/tests/test_runner.rs
When building a package whose dependencies are not yet cached and have to be fetched from Git may result in a really long wait before anything gets printed to the console to the point that it appears that the build is hung. This PR adds an extra bit of diagnostics that's printed when fetching (only) remote dependencies.
Yes
> [build] Added additional diagnostics for fetching deps

- language/documentation/tutorial/README.md
`errors` lib was removed in `tutorials/step_4/BasicCoin/sources/BasicCoin.move`  in PR #248 [commit 5f673876](https://github.com/move-language/move/pull/248/commits/5f673876b8bb3966da22bae40e869b52d21eced8), but the related doc in tutorial hasn't. So a modification was made to make the doc and the code consistent.
yes
Only document change. No test plan.
> [Tutorial] fix a minor inconsistency with code in step_4

- language/tools/move-cli/src/base/test.rs
The usage description for `--coverage` flag in `move test --help` was
```
--coverage
Collect coverage information for later use with the various `package coverage`
subcommands
```
I updated the `package coverage` part to `move coverage`
yes
It's a minor doc change. No extra test case needed.
> [move-cli] update description for 'move test --coverage' command

- language/tools/move-bytecode-utils/src/layout.rs
- language/tools/move-cli/src/sandbox/commands/generate.rs
- language/tools/move-cli/tests/sandbox_tests/generate_struct_layout/args.exp
- Remove printing of angle brackets for typenames without generics
- Take a reference to the ModuleResolver instead of requiring ownership
> [bytecode utils] fix a few issues with struct layout generation

- language/move-vm/runtime/src/interpreter.rs
- language/tools/move-unit-test/src/test_reporter.rs
- language/tools/move-unit-test/src/test_runner.rs
- language/tools/move-unit-test/tests/move_unit_test_testsuite.rs
- language/tools/move-unit-test/tests/test_sources/cross_module_aborts.exp
- language/tools/move-unit-test/tests/test_sources/missing_data.evm.exp
- language/tools/move-unit-test/tests/test_sources/missing_data.exp
- language/tools/move-unit-test/tests/test_sources/missing_data.move
- language/tools/move-unit-test/tests/test_sources/unexpected_abort.exp
This does two improvements for UT diagnosis:
- We now capture the stack trace (if according feature flags are enabled) for every interpreter error, not just aborts. The restriction to just aborts seem to be unnecessary.
- We now treat execution failures (arithmetic errors, borrow errors, index out of bounds) as regular errors, not longer as internal VM errors.
Effectively, were we had an output like this before:
```
│ ITE: An unknown error was reported. Location: error[E11001]: test failure
│   ┌─ missing_data.move:6:9
│   │
│ 5 │     fun missing_data() acquires Missing {
│   │         ------------ In this function in 0x1::MissingData
│ 6 │         borrow_global<Missing>(@0x0);
│   │         ^^^^^^^^^^^^^
│
│
│ VMError (if there is one): VMError {
│     major_status: MISSING_DATA,
│ …
```
> [unit tests] Improve DevX of unit tests diagnosis

- Cargo.lock
- language/move-core/types/src/language_storage.rs
- language/move-core/types/src/value.rs
- language/move-stdlib/Cargo.toml
- language/move-stdlib/nursery/sources/debug.move
- language/move-stdlib/src/natives/debug.rs
- language/move-vm/types/src/values/values_impl.rs
- language/tools/move-cli/tests/sandbox_tests/print_values/args.exp
- language/tools/move-cli/tests/sandbox_tests/print_values/args.txt
- language/tools/move-cli/tests/sandbox_tests/print_values/scripts/print_values.move
- language/tools/move-cli/tests/sandbox_tests/print_values/sources/M.move
This **draft** PR implements pretty-printing of Move values via `std::debug::print`, building upon #603 which added support for printing `std::string::String`.
An example of the new `std::debug::print` output:
```
[debug] 0x1::debug::TestStruct {
addr: @0x1,
number: 255,
bytes: 0xc0ffee,
name: "He\"llo",
vec: [
0x1::debug::TestInner {
val: 1,
vec: [ 130, 131 ]
},
0x1::debug::TestInner {
val: 2,
vec: [ 132, 133 ]
}
]
}
```
Note that we print `vector<u8>`'s as hexadecimal strings, since this is likely to be a more useful format for developers to inspect.
Also note that when a `vector<T>` has a complex type, such as `T = vector<S>` or a `T = struct`, we display the vector entries on separate lines, instead of the same line.
**TODOs:**
- <strike>fix `cargo build` warnings due to missing …
> [native functions] adds pretty-printing to `std::debug::print`

- language/move-prover/doc/user/spec-lang.md
1) Add description of `[suspendable]`. (close #477)
2) Mark `invariant pack` and `invariant unpack` as unimplemented. (close #577)
> [move-prover][doc] Modify the specification language document

- language/move-prover/tests/sources/functional/nonlinear_arithm.exp
- language/move-prover/tests/sources/functional/nonlinear_arithm.move
- Disabled the test cases `overflow_u128_mul_4` and `overflow_u128_mul_4_incorrect` in `nonlinear_arithm.move` because they cause timeouts in CI
To fix the timeouts in CI test for Prover
yes
cargo test
> [Prover] Disable the nonlinear test cases that cause timeouts in CI

- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/boogie-backend/src/prelude/prelude.bpl
- language/move-prover/tests/sources/functional/arithm.exp
- language/move-prover/tests/sources/functional/arithm.move
- language/move-prover/tests/sources/functional/cast.exp
- language/move-prover/tests/sources/functional/cast.move
- language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
There were some missing bits in the bytecode translator and in the Boogie prelude file that this PR is attempting to add.
Yes
> [Prover] Added support for new primitive types to arithmetic ops

- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/compositional_analysis.rs
- language/move-prover/bytecode/src/function_target_pipeline.rs
- language/move-prover/tests/sources/functional/recursive_move_fun.move
This PR tries to close #648 by avoiding panics in borrow_analysis and composition_analysis when handling recursive functions.
Yes
cargo test
> [move-prover] Fix the bug on handling recursive functions

- language/move-binary-format/src/deserializer.rs
- language/move-binary-format/src/file_format_common.rs
- language/move-binary-format/src/serializer.rs
- language/move-binary-format/src/unit_tests/deserializer_tests.rs
- language/move-compiler/src/command_line/compiler.rs
- language/move-vm/integration-tests/src/tests/binary_format_version.rs
- language/move-vm/integration-tests/src/tests/mod.rs
- language/move-vm/integration-tests/src/tests/nested_loop_tests.rs
- language/move-vm/runtime/src/config.rs
- language/move-vm/runtime/src/lib.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/move_vm.rs
- language/move-vm/runtime/src/runtime.rs
This adds a new VM config option that would allow one to specify the maximum binary format version acceptable dynamically, making it possible for downstream clients to roll out binary format changes (e.g. https://github.com/move-language/move/pull/547) in a backward compatible way.
**Note: this PR contains multiple small commits and it might be easier to review them one at a time.**
> [vm][binary-format] implements proper versioning for the code deserializer inside the VM

- language/tools/move-bytecode-utils/src/layout.rs
- language/tools/move-cli/src/sandbox/cli.rs
- language/tools/move-cli/src/sandbox/commands/generate.rs
- language/tools/move-cli/tests/sandbox_tests/generate_struct_layout/args.exp
- language/tools/move-cli/tests/sandbox_tests/generate_struct_layout/args.txt
- language/tools/move-cli/tests/sandbox_tests/generate_struct_layout/sources/phantoms.move
One of the promises of generating layout YAML's for Move structs is that we can leverage `serdegen` to autogenerate wrapper types for Move structs in all the languages `serdegen` handles. This PR moves us closer to that.
- Add `separator` option that allows replacing the Move source syntax separators ("::", "<", ">", ",") in type names with a user
-defined string. This is helpful because a name like `0x1::M::T<u64>` is very unlikely to be a valid identifier in any of the langua
ges `serdegen` handles. Setting (e.g.) `separator = __` allows a fully qualified Move type name to be a valid identifier.
- Add an `omit_addresses` option that omits the addresses from a fully qualified Move type name. This is useful in the (common) 
case where you are generating bindings for a package that does …
> [byecode utils] make struct layout generation work with serdegen

- language/extensions/async/move-async-vm/src/async_vm.rs
- language/move-binary-format/src/normalized.rs
- language/move-command-line-common/src/types.rs
- language/move-core/types/src/language_storage.rs
- language/move-core/types/src/parser.rs
- language/move-core/types/src/proptest_types.rs
- language/move-core/types/src/value.rs
- language/move-prover/bytecode/src/packed_types_analysis.rs
- language/move-prover/interpreter/src/concrete/ty.rs
- language/move-prover/move-abigen/src/abigen.rs
- language/move-vm/runtime/src/data_cache.rs
- language/move-vm/runtime/src/loader.rs
- language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
- language/tools/move-resource-viewer/src/fat_type.rs
- language/tools/move-resource-viewer/src/lib.rs
- language/tools/read-write-set/dynamic/src/dynamic_analysis.rs
Cherry-picking https://github.com/move-language/move/pull/525
> Currently a single TypeTag consumes 96 bytes because of the inlined StructTag (88 bytes), it starts to bloat up with nested TypeTag::Vector(TypeTag).
This commit reduces the size from 96 to 16 bytes, it doesn't fully solve the problem but reduces the impact by 6x.
> [core-types] cherry-pick: Make TypeTag enum use less memory

- language/move-binary-format/src/lib.rs
- language/move-bytecode-verifier/src/acquires_list_verifier.rs
- language/move-bytecode-verifier/src/control_flow.rs
- language/move-bytecode-verifier/src/dependencies.rs
- language/move-bytecode-verifier/src/reference_safety/abstract_state.rs
- language/move-bytecode-verifier/src/reference_safety/mod.rs
- language/move-bytecode-verifier/src/type_safety.rs
This introduces new macros `safe_unpack!` and `safe_assert!` which can be used in contexts which have a `PartialVMResult` as a return value. Those macros panic when debug assertions are enabled, but otherwise generate an internal invariant violation error. They are applied where an obvious substitution is possible.
> [bytecode-verifier] Avoid unwraps were possible when in release mode

- language/move-model/src/builder/module_builder.rs
- language/move-prover/bytecode/src/mono_analysis.rs
- language/move-prover/tests/sources/functional/axioms.move
Closes #683. The `is_native` property of spec functions was wrongly set, leading to that natives have beenn actually treated like uninterpreted functions in monomorphization.
> [prover] Fixing bug with generic axioms

- language/extensions/move-table-extension/sources/Table.spec.move
- language/move-model/src/intrinsics.rs
- language/move-model/src/model.rs
A function can be marked as intrinsic in two ways:
Method 1:
```
spec foo {
pragma intrinsic;
}
```
Method 2:
```
spec Table {
pragma intrinsic = map,
map_foo = foo;
}
```
In both ways, `foo` should be considered as intrinsic while the current approach only treats the first one as intrinsic and forces everything declared as a intrinsic function of some struct to be re-marked as intrinsic.
This PR changes this behavior. `foo` will be recognized as intrinsic regardless of how the intrinsic property is declared.
Close #665
Yes
CI
> [move-model] two ways to test is_intrinsic

- language/move-model/src/well_known.rs
- language/move-prover/boogie-backend/src/boogie_helpers.rs
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/boogie-backend/src/prelude/native.bpl
- language/move-prover/boogie-backend/src/prelude/prelude.bpl
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/bytecode/src/mono_analysis.rs
- language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
- language/move-prover/tests/sources/functional/type_reflection.exp
- language/move-prover/tests/sources/functional/type_reflection.move
This PR improves the type reflection modeling in Move Prover/
In this PR, the type info for a type parameter is modeled as a Boogie Datatype:
```
var #0_info: $TypeParamInfo;
// where $TypeParamInfo is defined as:
type {:datatype} $TypeParamInfo;
function {:constructor} $TypeParamBool(): $TypeParamInfo;
function {:constructor} $TypeParamU8(): $TypeParamInfo;
function {:constructor} $TypeParamU16(): $TypeParamInfo;
function {:constructor} $TypeParamU32(): $TypeParamInfo;
function {:constructor} $TypeParamU64(): $TypeParamInfo;
function {:constructor} $TypeParamU128(): $TypeParamInfo;
function {:constructor} $TypeParamU256(): $TypeParamInfo;
function {:constructor} $TypeParamAddress(): $TypeParamInfo;
function {:constructor} $TypeParamSigner(): $TypeParamInfo;
function {:constructor} …
```
> [move-prover] better type info scheme

- language/move-model/src/exp_generator.rs
- language/move-model/src/intrinsics.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/bytecode/src/data_invariant_instrumentation.rs
- language/move-prover/tests/sources/functional/data_invariant_in_map.exp
- language/move-prover/tests/sources/functional/data_invariant_in_map.move
Added the encoding for data invariants via entrypoint assumptions and packref assertions:
```
t: Table<K, V>;
forall k: K :: $Contains(t, k) ==> (data-inv-predicate)($Get(t, k));
```
Close #680 
Yes
A new test case is added
> [move-prover] data invariants for map values

- language/move-prover/boogie-backend/src/prelude/native.bpl
- language/move-prover/boogie-backend/src/prelude/table-array-theory.bpl
- language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
- language/move-prover/tests/sources/functional/table_contais_to_length.move
- language/move-prover/tests/sources/functional/trace.exp
- language/move-prover/tests/sources/regression/map_equality_encoding.move
Similar to vector equality, the map equality encoding should be customized unless the `options.native_equality` is set.
Add an axiom for relating table contains to length
```
axiom forall<K,V> t: Table<K,V> ::
(exists k: V :: Contains(t, k)) ==> Len(t) >= 1;
```
Both commits combined fix #673
Yes
Two new test case ported from #673 are added
> [move-prover] customized encoding for map equality and contains to length relation

- language/move-binary-format/src/binary_views.rs
- language/move-binary-format/src/control_flow_graph.rs
- language/move-binary-format/src/unit_tests/control_flow_graph_tests.rs
- language/move-binary-format/src/unit_tests/mod.rs
When generating a `VMControlFlowGraph`, identify loop heads and back-edges by finding back-edges in the depth-first traversal from the entry block.  This ensures that all the blocks in the CFG that are reachable at runtime are reachable during abstract interpretation.
This is roughly the algorithm proposed for finding widening points in Section 4.1 (Depth-first numbering) of "Efficient chaotic iteration strategies with widenings", Bourdoncle 1993.
Replaces the previous strategy of assuming a backward (in code offset) jump corresponds to a back-edge, which is something the Control Flow verifier was ensuring.  This assumption is no longer required, so this commit also removes references to that dependency.
Yes
Newly introduced unit tests check that a CFG can be generated, even when the …
> [1/2][binary/cfg] Relax backward-jump == loop back-edge requirement

- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/control_flow_tests.rs
- language/move-bytecode-verifier/src/control_flow_v5.rs
Recent changes to the CFG verifier missed the check that bytecode was non-empty and ended with a unconditional branch, for older bytecode versions.  Adding that back.
Test Plan:
New unit tests:
```
move-bytecode-verifier$ cargo nextest -- control_flow_tests
```
> [cfg][BUGFIX] Check for empty code units on bytecode v5 and below.

- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/limit_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
- language/move-bytecode-verifier/src/code_unit_verifier.rs
- language/move-bytecode-verifier/src/limits.rs
- language/move-bytecode-verifier/src/stack_usage_verifier.rs
- language/move-bytecode-verifier/src/verifier.rs
- language/move-core/types/src/vm_status.rs
- language/move-vm/runtime/src/loader.rs
* Add checks for max stack usage during stack balance analysis
* avoid duplicating name_def_map
* Type node bounds
This adds two measurements to limit the number of type nodes:
- in the bytecode verifier, module `limits, we restrict the number of nodes in a `SignatureToken` to 256 (configurable). Since at this point we neither know type instantiations nor struct definitions, we choose some weight factor for structs and type parameters. This measurement is mainly there to prevent and algorithms running out of time or memory which are part of the bytecode verifier.
- in the VM loader, we now not only count the depth of a type term but also the number of nodes in computation of type layouts. This includes type instantiation and struct definitions.
Co-authored-by: Zhou Runtian …
> [vm] Some reliability fixes (cherry-pick #703)

- language/move-core/types/src/u256.rs
- language/move-vm/types/src/values/values_impl.rs
This includes two minor fixes related to u256:
1. It fixes a build error in the fuzzing code
2. It implements Default for u256 so to make it consistent with other primitive integer types. This is also needed by some other downstream tools
> [u256] minor fixes

- language/move-compiler/src/compiled_unit.rs
- language/move-compiler/src/to_bytecode/translate.rs
This is another take at adding information about function attributes (specifically to find out if they are meant for testing) to make it available as part of compilation output. The previous take (https://github.com/move-language/move/pull/693) was aiming to add it in the file format, this one adds the required info into the annotated compiled units instead. I followed @wrwg's suggestions from the previous IR and instead of encoding just the fact if the function is involved in tests, this take encodes all function attributes.
Yes
> [compiler] Added info about function attributes as annotations

- language/move-vm/runtime/src/loader.rs
This fixes a rather subtle bug in the loader implementation. Without adding an extra field to count annotated nodes, initial statement attempting to use the cached data in `struct_gidx_to_fully_annotated_layout` and in `struct_gidx_to_type_layout` could update the node count with the one retrieved from cache  but then NOT return the cached value (as it was cached from a different unannotated/annotated version and as such `struct_info.struct_layout`/`struct_info.annotated_struct_layout` would be, unexpectedly, 'None`). This would lead to spurious (larger) count values.
Yes
> [loader] Fixed a node counting problem

- .github/workflows/ci-pre-land.yml
- language/move-vm/runtime/src/session.rs
- Exposed loaders type_to_type_tag function in the session API
- I am currently manually writing this function, but it is already exposed in the NativeContext. Seems reasonable I hope to also expose it when outside of Move (i.e. where the session is being invoked)
> [session] Expose type_to_type_tag

- language/move-prover/bytecode/src/function_target_pipeline.rs
This commit is the first step in adding a systematic support for
recursive function calls in the Prover.
In this commit, the problem we try to solve is enforcing a deterministic
(and yet, bottom-up) ordering of functions to process.
More formally:
Imagine we construct a call graph `G` where two nodes, `A ---> B` means
`A` calls `B` directly or transitively. By this definition, if we have
both `A ---> B` and `B ---> A` then we know both `A` and `B` belong to
the same recursive call grouh, which forms a strongly-connected
component (SCC) in `G`.
When processing all functions in the bytecode transformation pipeline,
we aim to achieve the following property:
- If `A ---> B` and `B -x-> A` (i.e., `B` does not depends on `A`), we
are sure that `B` gets processed first before `A`
- If `A -x-> B` …
> [move-prover] deterministic ordering of worklist with recursive calls

- language/move-prover/bytecode/src/annotations.rs
- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/function_target_pipeline.rs
- language/move-prover/bytecode/src/global_invariant_analysis.rs
- language/move-prover/bytecode/src/livevar_analysis.rs
- language/move-prover/bytecode/src/packed_types_analysis.rs
- language/move-prover/bytecode/src/read_write_set_analysis.rs
- language/move-prover/bytecode/src/usage_analysis.rs
- language/move-prover/bytecode/src/verification_analysis.rs
- language/move-prover/bytecode/src/verification_analysis_v2.rs
This commit allows the `Annotations` struct which resides in
`FunctionData` to mark whether an annotation has reached a fixedpoint
status in the presence of recursive calls.
The core of change is this:
```diff
pub struct Annotations {
-    map: BTreeMap<TypeId, Data>,
+    map: BTreeMap<TypeId, (Data, bool)>,
}
```
Currently all annotations, when set, are marked as already reached
fixedpoint status. This is consistent with the current assumption of
no-recursive calls.
Subsequent commits will relax this unsound assumption by examining the
annotation structure produced by different passes in the transformation
pipeline.
This commit depends on PR #698. A better way to review this PR is
to just look at the second commit: 7ecd599bd95fbd9ea2fb51ae68949d10c303dd57
More systematic supporting of …
> [move-prover] allow annotations to mark whether a fixedpoint is reached

- language/documentation/book/src/coding-conventions.md
We suggest that error codes use upper camel case + start with an `E` to distinguish them from other constants
> [docs] update coding conventions for error codes

- language/documentation/book/src/integers.md
- language/documentation/book/translations/move-book-zh/src/integers.md
Close #735
Make both mdBook and GitHub correctly render pipe sign (`|`).
Yes
> [move book & move-book-zh] fix pipe sign rendering

- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/tests/sources/functional/old_in_inlined.move
This resolves https://github.com/move-language/move/issues/717 which describes the problem and contains some discussion, but does not include Boogie generated code that explains what's going on so here is an additional explanation.
Consider the following Move code:
```
module prover_bug::old {
fun foo() {
let x = 0;
bar(&mut x);
}
fun bar(y: &mut u64) {
*y = *y + 2;
spec {
assert y > old(y) + 1;
}
}
}
```
The `assert` statement in the inlined spec of the `bar` function is at some point inlined into the Prover bytecode. In particular, this is the bytecode after the loop analysis (11th) pass with the assert inlined in line 5:
```
[variant baseline]
fun old::bar($t0|y: &mut u64) {
var $t1: u64
var $t2: u64
var $t3: u64
0: trace_local[y]($t0)
1: $t1 := read_ref($t0)
2: $t2 := 2
3: $t3 := …
```
> [prover] Fix for incorrect generation of old values

- language/move-core/types/src/language_storage.rs
- language/move-stdlib/src/natives/debug.rs
- language/tools/move-cli/tests/sandbox_tests/print_values/args.exp
- language/tools/move-cli/tests/sandbox_tests/print_values/sources/M.move
`debug::print` special-cases `std::string::String` (utf8 strings), but not `std::ascii::String`. Use the same logic for ascii strings.
> [debug] print `std::ascii::String` as string

- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/limit_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/vec_pack_tests.rs
- language/move-bytecode-verifier/src/limits.rs
- language/move-bytecode-verifier/src/verifier.rs
- language/move-core/types/src/vm_status.rs
- language/move-vm/integration-tests/src/tests/loader_tests.rs
- language/move-vm/runtime/src/loader.rs
This introduces a limit for all definitions in a module: structs, fields and functions.
We have some quadratic algorithm in the loader (fields of a type defined in the module) and possibly more.
This reduces the chances of possible attacks and it is a reasonable limitation to add (in fact a great one in my opinion with open publishing).
Also there is some cleanup where we added some config values that were not `Option` as the others. Making everything `Option`.
Finally there is a fix in the limits check in the verifier to run `verify_type_nodes` for scripts
Yes
Added unit tests
> Limits for defs in a module

- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/bytecode/src/loop_analysis.rs
- language/move-prover/tests/sources/functional/data_invariant_in_loop.move
- language/move-prover/tests/sources/functional/macro_verification.exp
Currently well-formed check is instrumented at Boogie translation step. This commit explicitly instrument the well-formed check right after the havoc bytecode.
This should be semantically equivalent in terms of loop handling, but greatly simplifies data invariant instrumentation as the data invariant instrumentation pass looks for `WellFormed` opcode as hook-up points to instrument the data invariants.
This commit closes #716.
Data invariants in loops
Yes
- CI
- A new test case is added
> [move-prover] explicit well-formed assumption after havoc

- language/move-model/src/ty.rs
- language/move-prover/bytecode/src/mono_analysis.rs
- language/move-prover/tests/sources/regression/mono_on_axiom_spec_type.move
Fixes #700 
Yes
- CI
- test case in #700 is minimized and added as a regression test
> [move-prover] only allow move types when computing type insts for axioms

- language/tools/move-package/src/lib.rs
- language/tools/move-package/src/resolution/mod.rs
- language/tools/move-package/src/resolution/resolution_graph.rs
- language/tools/move-package/src/source_package/manifest_parser.rs
- language/tools/move-package/src/source_package/parsed_manifest.rs
- language/tools/move-package/tests/test_sources/resolution/dep_good_digest/Move.exp
- language/tools/move-package/tests/test_sources/resolution/diamond_problem_backflow_resolution/Move.exp
- language/tools/move-package/tests/test_sources/resolution/diamond_problem_no_conflict/Move.exp
- language/tools/move-package/tests/test_sources/resolution/multiple_deps_rename/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_assigned_address/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_multiple_of_same_name/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_reassigned_address/Move.exp
- language/tools/move-package/tests/test_sources/resolution/one_dep_unification_across_local_renamings/Move.exp
A number of behaviour preserving changes to make it easier to integrate a lock file into the package resolution process.  See [[RFC] Move.lock](https://docs.google.com/document/d/1OV3te-SnpZv2Yxv7uxGQH6NFhE-CdqiCjB66JmYAGKs/edit) for more context.
This can be one of `Local`, `Git` or `Custom`, each containing the relevant information for resolving a dependency of that kind, replacing the previous structure where `Dependency` had optional fields for `git_info` and (custom) `node_info`.
This was motivated by two factors:
- Introducing another variant for dependencies (handled by third party package managers), which will be easier to manage when the type is described by an `enum` rather than struct of optionals.
- A new operation that needs to be implemented on dependencies before they are …
> [1/x][move-package/lock] Preparing for Lock file

- language/move-bytecode-verifier/src/signature.rs
78a9e2b01da9c87af31910bbbcb5eeb4d51c909d was known to be a breaking change, but it was unclear whether it would break real code. Turns out that it does, so preserve the old behavior in older bytecode versions.
> [verifier] add version-gating to type instantiation check

- language/move-compiler/src/typing/translate.rs
- language/move-compiler/tests/move_check/typing/ability_constraint_generic_in_field.exp
- language/move-compiler/tests/move_check/typing/ability_constraint_generic_in_field.move
- language/move-compiler/tests/move_check/typing/phantom_param_struct_decl_invalid.exp
- Fixed a bug where ability constraints where not properly checked for fields containing the structs type parameter
The bug was only present with type parameters, for example `struct S<T: copy> {} struct B { f: S<signer> }` would be rejected prior to this fix 
Fixes #763
- New tests. Looked like we had one written already for this but the output was just incorrect....
> [compiler] Fix instantiation of field types with type parameters

- language/move-prover/bytecode/tests/borrow/function_call.exp
- language/move-prover/bytecode/tests/borrow/hyper_edge.exp
- language/move-prover/bytecode/tests/borrow_strong/mut_ref.exp
- language/move-prover/bytecode/tests/escape_analysis/return_refs_into_vec.exp
- language/move-prover/bytecode/tests/escape_analysis/vec_eq.exp
- language/move-prover/bytecode/tests/from_move/regression_generic_and_native_type.exp
- language/move-prover/bytecode/tests/from_move/vector_instructions.exp
- language/move-prover/bytecode/tests/read_write_set/borrow.exp
- language/move-prover/bytecode/tests/read_write_set/read_vector.exp
- language/move-stdlib/docs/vector.md
- language/move-stdlib/sources/vector.move
- language/move-stdlib/tests/vector_tests.move
We have `vector::remove` (which is very similar), and it's a pain to ask users to handroll this.
> [stdlib] add `vector::insert`

- language/move-vm/types/src/values/value_tests.rs
- language/move-vm/types/src/values/values_impl.rs
This allows move values of type vector<u64> to be easily cast to Vec<u64> in rust using the pop_arg macro.
Yes.
UT test case should be sufficient.
> Allow `vector<u64>` to be cast to `Vec<u64>` in rust with `pop_arg`

- language/move-vm/types/src/values/value_tests.rs
- language/move-vm/types/src/values/values_impl.rs
This allows move values of type `vector<u64>` to be easily cast to `Vec<u64>` in rust using the `pop_arg` macro.
Yes.
UT test case should be sufficient.
> Move vector<u64> easy casting to rust Vec<u64>

- Cargo.lock
- language/move-core/types/src/language_storage.rs
- language/move-core/types/src/lib.rs
- language/move-core/types/src/parser.rs
- language/move-core/types/src/safe_serialize.rs
- language/move-prover/tests/sources/functional/nonlinear_arithm.move
These were the only changes which did not make it into the main branch, so porting them over from the old `aptos` branch.
> Cherry picks TypeTag bounds from old aptos branch

- Cargo.lock
- language/move-core/types/src/language_storage.rs
- language/move-core/types/src/lib.rs
- language/move-core/types/src/parser.rs
- language/move-core/types/src/safe_serialize.rs
- language/move-prover/tests/sources/functional/nonlinear_arithm.move
* [types] make type tag nesting limited
There's limited value and a lot of wasted resources by leaving this limited to serde's limits. Recursion is dangerous.
* [types] limit nesting of types via state (#532)
Cherry picked from #529.
This is an alternative version of what #528 and the previous for limitation of nesting provides, having a significant lower footprint.
This approach installs custom serializers at the recursion points of the `TypeTag` enum. Those serializer use a thread local to track the nesting of the type tag, both for serialization and deserialization.
The usage of a thread local is safe and a common technique to provide extra state for implementations which miss it (e.g. serde). A given thread has a single execution stack and this will always count the depth counter …
> Cherry picks TypeTag bounds from old aptos branch (#791)

- language/move-compiler/src/command_line/compiler.rs
- language/move-compiler/src/diagnostics/codes.rs
- language/move-compiler/src/inlining/mod.rs
- language/move-compiler/src/inlining/translate.rs
- language/move-compiler/src/lib.rs
- language/move-compiler/src/shared/ast_debug.rs
- language/move-compiler/src/typing/translate.rs
- language/move-compiler/tests/move_check/inlining/recursion.exp
- language/move-compiler/tests/move_check/inlining/recursion.move
- language/move-compiler/transactional-tests/tests/inlining/generics.exp
- language/move-compiler/transactional-tests/tests/inlining/generics.move
- language/move-compiler/transactional-tests/tests/inlining/lambda.exp
- language/move-compiler/transactional-tests/tests/inlining/lambda.move
- language/move-compiler/transactional-tests/tests/inlining/simple.exp
- language/move-compiler/transactional-tests/tests/inlining/simple.move
- language/move-prover/tests/sources/functional/bitset.move
- language/move-prover/tests/sources/functional/fixed_point_arithm.exp
- language/move-prover/tests/sources/functional/nonlinear_arithm.move
- language/move-stdlib/docs/fixed_point32.md
- language/move-stdlib/sources/fixed_point32.move
This PR implements the core logic for expanding inlined functions. Expansion is happening as a new phase after typing and before hlir lowering.  The inlining phase is a function `f(&mut typing::ast::Program)`. It will inline functions as they are encountered. When a function with lambda arguments is inlined, those lambdas are further expanded, using basically the same algorithm as for conventional inlining.
There are a few tests added which cover basic behavior. More tests have to be added as the feature evolves, and more type checks have to be added. Specifically, currently inlining can create code which does not pass the bytecode verifier because 'private' calls are inserted at inlining context. This is not captured by the Move compiler, but the bytecode verifier will flag this. (With a …
> [inlining] Expansion of inlined functions

- language/documentation/examples/diem-framework/move-packages/experimental/sources/Vote.move
- language/move-prover/bytecode/src/memory_instrumentation.rs
- language/move-prover/tests/sources/functional/data_invariant_for_mut_ref_arg.exp
- language/move-prover/tests/sources/functional/data_invariant_for_mut_ref_arg.move
- language/move-prover/tests/sources/functional/mut_ref.exp
For functions with `&mut` params `s: S`, the data invariant for `S` will be assumed at function entry (via `Wellformedness` - this is already done) and re-checked on any write-back to this reference --- this is newly added in this commit.
This PR is the opposite of PR #783 which does the opposite, i.e., drop the assumption at the function entry. PR #783 is proposed following the following guideline:
> Data invariants are only checked when the `&mut` borrow ends. During
> the lifetime of the `&mut` reference, the invariant can be temporarily
> violated and hence, assuming data invariants there can lead to
> inconsistency issues.
In theory, both PR's fix are better than the current practice (which is essentially assuming without assertion).
However, as the test result in PR #783 shows, the …
> [move-prover] data invariant assume and assertion for `&mut` params

- language/move-compiler/src/command_line/compiler.rs
- language/move-compiler/src/diagnostics/codes.rs
- language/move-compiler/src/expansion/translate.rs
- language/move-compiler/src/inlining/translate.rs
- language/move-compiler/src/typing/core.rs
- language/move-compiler/tests/move_check/inlining/parameter_borrow.exp
- language/move-compiler/tests/move_check/inlining/parameter_borrow.move
- language/move-compiler/tests/move_check/inlining/recursion.exp
- language/move-compiler/tests/move_check/inlining/recursion.move
- language/move-compiler/transactional-tests/tests/inlining/options.exp
- language/move-compiler/transactional-tests/tests/inlining/options.move
- language/move-model/src/builder/module_builder.rs
- language/move-stdlib/sources/option.move
- language/move-stdlib/sources/string.move
- language/move-stdlib/tests/option_tests.move
This adds `map` and `filter` to `std::option` and make them work e2e, including unit tests in `option_tests`. At this point, we do have inlined functions working across modules and packages.
The PR also explores some conceptual questions around parameter expansion. Right now, we stick to the original simplistic viewpoint that all parameters are replaced directly by the according expression. This effectively implements 'call by expression'. It would be the responsibility (and flexibility!) of the function implementer to use `let` and similar measures to avoid duplicate evaluation of inlined parameters. This also creates a restriction: if somewhere in the code a parameter `p` is used in l-value position than also the passed parameter must be an lvalue. There is a new error message if this …
> [inlining] Fixing bugs and adding first combinators to stdlib

- language/move-bytecode-verifier/src/absint.rs
- language/move-bytecode-verifier/src/locals_safety/mod.rs
- language/move-bytecode-verifier/src/reference_safety/mod.rs
- The associated type for errors is necessary for custom verifier passes using absint
Custom adapter verifier passes struggle when they want to use the same absint infrastructure, but with a custom error type. This adds back the type that was previously there.
- Non functional change. ran tests
> [absint] Bring back associated error type

- language/move-compiler/src/inlining/visitor.rs
- language/move-prover/tests/sources/functional/inline_fun.move
This is a minor fix that allow function local variables used in inline specs (e.g., loop invariants) to be captured in the inline phase and processed in subsequent phases.
Fix minor issue while adopting inline functions into prover
Yes
CI, with a new test case
> [move-compiler] capture variable usages in spec blocks

- language/tools/move-package/src/resolution/mod.rs
- language/tools/move-package/src/source_package/manifest_parser.rs
- language/tools/move-package/src/source_package/parsed_manifest.rs
- language/tools/move-package/tests/test_runner.rs
- language/tools/move-package/tests/test_sources/resolution/package_hooks/Move.exp
- language/tools/move-package/tests/test_sources/resolution/package_hooks/Move.toml
- language/tools/move-package/tests/test_sources/resolution/package_hooks_subdir/Move.exp
- language/tools/move-package/tests/test_sources/resolution/package_hooks_subdir/Move.toml
Proposing a more general handling of the `subdir` field for dependencies, which boils down to:
- Explicitly disallowing the field on `local` dependencies (this will produce an error, where previously it would be silently ignored).
- Enabling its use with custom dependencies.
The second change is not likely to be used directly in `Move.toml` (although it could be), but instead is intended to be used with lock files (which are designed to serialize/deserialize dependencies in a format that can be parsed by the existing `manifest_parser::parse_dependency`), in the context of dependency re-rooting, which already occurs implicitly for `git` dependencies, when:
- `a`, depends on `b`, a git dependency, with subdir `s`, and
- `b`, depends on `c`, a local dependency, with relative path `r`.
From …
> [RFC][2/x][move-package/lock] Extend handling of Dependency subdir

- language/tools/move-cli/tests/build_tests/unbound_dependency/args.evm.exp
- language/tools/move-cli/tests/build_tests/unbound_dependency/args.exp
- language/tools/move-package/src/resolution/mod.rs
- language/tools/move-package/tests/test_sources/parsing/full_manifest/Move.resolved
- language/tools/move-package/tests/test_sources/parsing/full_manifest_with_extra_field/Move.resolved
- language/tools/move-package/tests/test_sources/parsing/invalid_hex_address_in_subst/Move.resolved
- language/tools/move-package/tests/test_sources/parsing/non_identifier_address_name_in_subst/Move.resolved
- language/tools/move-package/tests/test_sources/parsing/unknown_toplevel_field/Move.resolved
Fix the order in which the directory and `Move.toml` are joined together (should be directory and then `Move.toml`, not the other way around as it previously was), and don't drop the context of the underlying error.
Also restructuring the function slightly to be less deeply nested, by using `?`.
```
move/language/tools/move-package$ cargo nextest
```
- #741 
- #745 
- #753
> [4/x][move-package/lock] Fix error message from parse_package_manifest

- language/move-model/src/ast.rs
- language/move-model/src/well_known.rs
- language/move-prover/boogie-backend/src/boogie_helpers.rs
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/bytecode/src/mono_analysis.rs
- language/move-prover/tests/sources/functional/nonlinear_arithm.move
- language/move-prover/tests/sources/functional/type_reflection.exp
- language/move-prover/tests/sources/functional/type_reflection.move
- language/move-prover/tests/sources/functional/type_reflection_ext.move
The majority of the Prover work was firstly introduced when Aptos introduced the `type_info` Move module. Now that the stdlib has a similar module `type_name`, we should bridge the effort here.
This PR is still a bit rough as it is using hardcoded module address / function names to identify the type-reflection schemes. We should come up with more robust / extensible approach later.
NOTE: it is hard to unify them though. `type_info::type_name<T>()` and `type_name::get<T>()` are not equivalent, primarily due to the format of module address:
- in `type_info::type_name()`, the address is `0x1` while
- in `type_name::get()`, the address is `00000000000000000000000000000001`
Fix #803
Yes
CI, new tests added
> [move-prover] model `type_name::get` in stdlib

- language/move-model/src/ast.rs
- language/move-model/src/model.rs
- language/move-prover/boogie-backend/src/boogie_helpers.rs
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/boogie-backend/src/lib.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/bytecode/src/number_operation.rs
- language/move-prover/bytecode/src/number_operation_analysis.rs
- language/move-prover/doc/user/spec-lang.md
- language/move-prover/tests/sources/functional/bitwise_features.move
- language/move-prover/tests/sources/functional/bitwise_operators.move
- language/move-prover/tests/sources/functional/bitwise_table.move
This PR: 1) adds supports for specifying bitwise operations in spec functions; 2) allows bitwise operations for values in tables; and 3) adds descriptions on bitwise operators in the [MSL](https://github.com/move-language/move/blob/main/language/move-prover/doc/user/spec-lang.md) document.
Yes
cargo test
> [Move-prover] Allow bitwise operation in spec functions and tables

- language/move-model/src/ast.rs
- language/move-model/src/builder/module_builder.rs
- language/move-model/src/spec_translator.rs
- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/bytecode/src/stackless_bytecode_generator.rs
- language/move-prover/bytecode/src/usage_analysis.rs
- language/move-prover/tests/sources/functional/global_vars.exp
- language/move-prover/tests/sources/functional/global_vars.move
This PR allows users to update global specification variables in the function body.
Yes
> [Move-prover] Allow global spec vars to be updated in the function body

- devtools/x-lint/src/lib.rs
- language/move-prover/boogie-backend/src/prelude/native.bpl
- language/move-prover/boogie-backend/src/prelude/vector-array-intern-theory.bpl
- language/move-prover/boogie-backend/src/prelude/vector-array-theory.bpl
- language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
- language/move-prover/tests/sources/functional/verify_vector.move
A Boogie model is missing for recently added `vector::insert` function and this PR is attempting to remedy it
Yes
Added a spec for a function using `vector::insert` to the functional tests.
> [prover] Added a Boogie model for vector::insert function

- language/evm/move-to-yul/tests/AccountStateMachine.exp
- language/move-prover/bytecode/src/reaching_def_analysis.rs
- language/move-prover/tests/sources/regression/bug_828.move
This commit contains two changes to the reach-def analysis pass:
- if a local variable `x := a` and later we discover that `a := b` too, then mark that `x` might alias both `a` and `b`. This is done in the intra-procedural abstract interpretation so the def of `x` will be updated (joined) on a later stage.
- if a local variable `x := a` and `a` might take the value of both original and havoc-ed, then mark that `x` is not uniquely aliased.
Both changes prevents copy propogated from `a` to `x`.
Fix #828 
Yes
The test case in #828 is added
> [move-prover] special casing havoc in reach-def annalysis

- README.md
This needs to be enabled by an admin of the Move language discord, but now the invite link is valid.
If one of the Admins could enable via these instructions :) It'll bring visibility to the Discord server, and fix the broken link.
https://shields.io/category/chat
> [README] Fix Discord invite so badge is updated

- language/move-compiler/src/diagnostics/codes.rs
- language/move-compiler/src/inlining/translate.rs
- language/move-compiler/src/inlining/visitor.rs
- language/move-compiler/src/naming/ast.rs
- language/move-compiler/src/to_bytecode/context.rs
- language/move-compiler/src/typing/core.rs
- language/move-compiler/src/typing/globals.rs
- language/move-compiler/src/typing/translate.rs
- language/move-compiler/tests/move_check/inlining/private_call.exp
- language/move-compiler/tests/move_check/inlining/private_call.move
- language/move-compiler/tests/move_check/inlining/resources_invalid.exp
- language/move-compiler/tests/move_check/inlining/resources_invalid.move
- language/move-compiler/tests/move_check/inlining/return.exp
- language/move-compiler/tests/move_check/inlining/return.move
- language/move-compiler/tests/move_check/translated_ir_tests/move/borrow_tests/borrow_global_acquires_invalid_annotation.exp
- language/move-compiler/tests/move_check/translated_ir_tests/move/borrow_tests/borrow_global_acquires_missing_annotation.exp
- language/move-compiler/tests/move_check/translated_ir_tests/move/borrow_tests/imm_borrow_global_requires_acquire.exp
- language/move-compiler/tests/move_check/typing/invalid_type_acquire.exp
- language/move-compiler/tests/move_check/typing/missing_acquire.exp
- language/move-compiler/transactional-tests/tests/inlining/objects.exp
- language/move-compiler/transactional-tests/tests/inlining/objects.move
- language/move-compiler/transactional-tests/tests/inlining/resources.exp
- language/move-compiler/transactional-tests/tests/inlining/resources.move
This PR refines the inline implementation to peform various tests for consistency:
- report an error if `return` is used in the inlined functions (currently not supported)
- report errors if inlining introduces inconsistency in the expansion context (calling private functions, accessing module memory, etc.)
- re-arrange the acquires analysis, allowing inline functions to access memory without decl of `acquires`. Rather, check `acquires` after inlining.
The last step, specifically, also allows to write generic inline functions which deal with memory. This has been excercised in the [objects.move](https://github.com/wrwg/move-lang/blob/lambda2/language/move-compiler/transactional-tests/tests/inlining/objects.move) testcase.
The change in the acquires leads to a different style of acquire …
> [inline functions] Extending consistency checks and enabling memory management

- .github/workflows/ci-pre-land.yml
- language/move-compiler/transactional-tests/tests/inlining/deep_exp.exp
- language/move-compiler/transactional-tests/tests/inlining/deep_exp.move
- language/move-vm/integration-tests/src/tests/leak_tests.rs
The Move compiler, if not compiled in release mode, has large stack usage. The Rust thread default stack size is only 2Mb. Even with relative small programs stack overflow can happen. This PR uses the env variable RUST_MIN_STACK in the CI configuration to up the stack size to 16MB. Users should add a similar value to there shell if they run into stackoverflow problems.
Adds a test which would overflow the stack with default 2mb size.
> [stackoverflow problem] Setting default thread stack size higher in CI

- language/move-core/types/src/vm_status.rs
We will use the `MEMORY_LIMIT_EXCEEDED` status code and define our own sub_status as needed. This prevents incompat with main branch
Yes
N/A
> Revert event limit status code

- language/move-vm/runtime/src/native_functions.rs
Extend native support for verifying a resource exists.
verified here: https://github.com/aptos-labs/aptos-core/pull/6416/commits
> [natives] add support for checking the existence of a resource

- language/move-compiler/src/expansion/ast.rs
- language/move-compiler/src/hlir/ast.rs
- language/move-compiler/src/naming/ast.rs
- language/move-compiler/src/typing/ast.rs
Effect of this commit:
```diff
- spec #0uses <local variables>
+ spec #0 uses <local variables>
```
A small nicety on the way of spec inlining
Yes
CI
> [move-compiler] add a space in spec ast debug dump

- language/move-compiler/src/cfgir/borrows/mod.rs
- language/move-compiler/src/cfgir/cfg.rs
- language/move-compiler/src/cfgir/liveness/mod.rs
- language/move-compiler/src/cfgir/locals/mod.rs
- language/move-compiler/src/cfgir/optimize/constant_fold.rs
- language/move-compiler/src/cfgir/optimize/eliminate_locals.rs
- language/move-compiler/src/compiled_unit.rs
- language/move-compiler/src/hlir/ast.rs
- language/move-compiler/src/hlir/translate.rs
- language/move-compiler/src/inlining/translate.rs
- language/move-compiler/src/inlining/visitor.rs
- language/move-compiler/src/to_bytecode/context.rs
- language/move-compiler/src/to_bytecode/translate.rs
- language/move-compiler/src/typing/ast.rs
- language/move-compiler/src/typing/expand.rs
- language/move-compiler/src/typing/globals.rs
- language/move-compiler/src/typing/infinite_instantiations.rs
- language/move-compiler/src/typing/translate.rs
- language/move-compiler/tests/move_check/inlining/spec_inlining.move
- language/move-model/src/builder/model_builder.rs
- language/move-model/src/builder/module_builder.rs
- language/move-prover/tests/sources/functional/inline_fun.exp
- language/move-prover/tests/sources/functional/inline_fun.move
- language/move-prover/tests/sources/functional/inline_fun_simple.exp
- language/move-prover/tests/sources/functional/inline_fun_simple.move
This PR is an aggregated results of several PRs, including:
#876, #877 and this one.
It involves three changes:
**Change 1: extending the AST representation for `UnannotatedExp_::Spec`**
This PR changes `typing::UnannotatedExp_::Spec` as following:
```diff
- Spec(SpecId, BTreeMap<Var, Type>),
+ Spec(SpecId, Option<SpecIdent>, BTreeMap<Var, (Type, Var)>),
```
Where `SpecIdent` marks the origin of the spec block (before inlining)
```rust
pub struct SpecIdent {
pub module: Option<ModuleIdent_>,  // None means a script
pub function: Symbol,
pub id: SpecId,
}
```
In the new representation:
```rust
Spec(SpecId, Option<SpecIdent>, BTreeMap<Var, (Type, Var)>),
^^^ origin of spec
^^^ name of the original local variable used in spec
^^^ name of the re-mapped local variable
```
This allows …
> [move-prover] limited support for inline spec in prover

- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/bytecode/src/number_operation_analysis.rs
- language/move-prover/tests/sources/functional/bitwise_features.move
This PR 1) adds supports for handling vector::insert function for bitwise operations; 2) fix a bug when handling `let` expression in the spec for `bv` types. 
Yes
`bitwise_features.move` is modified to test the change.
> [Move-prover][Bitwise] Add support for vector::insert & bug fix for handling the let expression in the spec

- language/tools/move-cli/tests/build_tests/unbound_dependency/args.evm.exp
- language/tools/move-cli/tests/build_tests/unbound_dependency/args.exp
- language/tools/move-package/src/lib.rs
- language/tools/move-package/src/resolution/dependency_graph.rs
- language/tools/move-package/src/resolution/lock_file/schema.rs
- language/tools/move-package/src/resolution/mod.rs
- language/tools/move-package/src/resolution/resolution_graph.rs
- language/tools/move-package/src/source_package/manifest_parser.rs
- language/tools/move-package/tests/test_dependency_graph.rs
- language/tools/move-package/tests/test_sources/dep_dev_dep_diamond/Move.locked
- language/tools/move-package/tests/test_sources/dep_good_digest/Move.locked
- language/tools/move-package/tests/test_sources/diamond_problem_no_conflict/Move.locked
- language/tools/move-package/tests/test_sources/multiple_deps_no_rename/Move.locked
- language/tools/move-package/tests/test_sources/nested_deps_git_local/Move.locked
- language/tools/move-package/tests/test_sources/nested_deps_local_local/Move.locked
- language/tools/move-package/tests/test_sources/one_dep/Move.locked
- language/tools/move-package/tests/test_sources/one_dep_bad_digest/Move.locked
- language/tools/move-package/tests/test_sources/parsing_full_manifest/Move.resolved
- language/tools/move-package/tests/test_sources/parsing_full_manifest_with_extra_field/Move.resolved
- language/tools/move-package/tests/test_sources/parsing_invalid_hex_address_in_subst/Move.resolved
- language/tools/move-package/tests/test_sources/parsing_non_identifier_address_name_in_subst/Move.resolved
- language/tools/move-package/tests/test_sources/parsing_unknown_toplevel_field/Move.resolved
The initial design of `DependencyGraph` only allowed for one `addr_subst` and `digest` per package in the transitive dependency graph, but in actuality there can be as many of these as there are dependency edges to that package:
- Different `addr_subst` for different packages `P`, `Q` depending on `R` allows the same address in `R` to appear as different addresses in `P` and `Q`.
- If `R` is a dependency of `P` and a dev-dependency of `Q`, then its source digest may differ between the two.
Fixed by moving the `subst` and `digest` to be edge labels in the graph, rather than node labels.
Note that this also changes the lock file format in the following ways:
- A package's dependencies are now no longer just the name of the dependency, but an inline table containing the name and optionally …
> sui-move: [7/x][move-package/lock] Move addr_subst and digest to dependency edge

- language/tools/move-package/src/resolution/dependency_graph.rs
- language/tools/move-package/tests/test_dependency_graph.rs
Function to return a package's immediate dependencies in the transitive dependency graph, for use by `ResolutionGraph` when resolving renamings and in-scope addresses during resolution
New tests:
```
move/language/tools/move-package$ cargo nextest
```
- #741 
- #745 
- #753 
- #754 
- #759 
- #760 
- #854 
See also: #784 for main.
> sui-move: [8/x][move-package/lock] DependencyGraph::immediate_dependencies

- language/tools/move-package/src/resolution/mod.rs
- language/tools/move-package/src/resolution/resolving_table.rs
- language/tools/move-package/tests/test_resolving_table.rs
Extract the logic for unifying named addresses across address assignments, substitutions and renamings from `ResolvingGraph` into its own class -- `ResolvingTable`.
This is to be used when integrating `DependencyGraph` into `ResolutionGraph`.
New unit tests:
```
move/language/tools/move-package$ cargo nextest
```
- #741 
- #745 
- #753 
- #754 
- #759 
- #760 
- #854 
- #855 
See also: #785 for main.
> sui-move: [9/x][move-package/lock] ResolvingTable

- language/extensions/async/move-async-vm/tests/sources/AccountStateMachine.exp
- language/move-compiler/src/cfgir/ast.rs
- language/move-compiler/src/cfgir/translate.rs
- language/move-compiler/src/expansion/ast.rs
- language/move-compiler/src/expansion/translate.rs
- language/move-compiler/src/hlir/ast.rs
- language/move-compiler/src/hlir/translate.rs
- language/move-compiler/src/naming/ast.rs
- language/move-compiler/src/naming/translate.rs
- language/move-compiler/src/to_bytecode/translate.rs
- language/move-compiler/src/typing/ast.rs
- language/move-compiler/src/typing/translate.rs
- language/move-compiler/transactional-tests/tests/evaluation_order/struct_arguments.exp
- language/testing-infra/transactional-test-runner/tests/vm_test_harness/example.exp
- language/tools/move-cli/tests/build_tests/disassemble_module/Move.toml
- language/tools/move-cli/tests/build_tests/disassemble_module/args.exp
- language/tools/move-cli/tests/build_tests/disassemble_module/args.txt
- language/tools/move-cli/tests/build_tests/disassemble_module/sources/m.move
- language/tools/move-cli/tests/sandbox_tests/module_disassemble/args.exp
- language/tools/move-cli/tests/sandbox_tests/package_basics/args.exp
- language/tools/move-cli/tests/sandbox_tests/verify_native_functions_in_multi_module_publish/args.exp
- language/tools/move-cli/tests/sandbox_tests/verify_native_functions_in_publish/args.exp
- The definition tables in the CompiledModule were populated via the alphanumeric ordering
- This might be unexpected as other constructs, namely fields, do not do this.
- This fix sorts the definitions based on the source file declaration order
- new test and updated tests
> [sanity fix] Declaration order of structs/constants/functions used for definition tables

- language/move-core/types/src/account_address.rs
- language/move-core/types/src/gas_algebra.rs
- language/move-core/types/src/identifier.rs
- language/move-core/types/src/language_storage.rs
- language/move-core/types/src/unit_tests/identifier_test.rs
- language/move-core/types/src/unit_tests/language_storage_test.rs
- language/move-vm/types/src/values/values_impl.rs
We need some way of deterministically sizing types for gas metering.
For now we're okay handrolling but will use macros to ensure structs are properly sized.
Yes
Unit tests
> Add abstract gas sizing for StructTag, TypeTag, Value

- language/move-model/src/pragmas.rs
- language/move-prover/boogie-backend/src/lib.rs
- language/move-prover/boogie-backend/src/prelude/native.bpl
- language/move-prover/boogie-backend/src/prelude/table-array-theory.bpl
- language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
- language/move-prover/tests/sources/functional/verify_custom_table.exp
- language/move-prover/tests/sources/functional/verify_custom_table.move
- language/move-stdlib/docs/fixed_point32.md
- language/move-stdlib/sources/fixed_point32.move
This commit addresses two issues:
1. Added a new intrinsic spec function `spec_map_new` to allow the following native spec function to be emulated: `spec native fun spec_new<K, V>(): Table<K, V>;` This funciton will return an empty table on the spec side.
2. While testing the newly added intrinsic funciton, several issues are discovered.
- One issue fixed in this commit is the equality encoding of the `table` intrinsic, evident by the fact that the newly added test `create_and_insert_fail2` will pass the verification which it really should not.
The table equality check is now formulated in a manner symmetric to both tables (the previous formulate seems to be biased to one table, although I don't claim that I fully understand the difference).
- Another issue not fixed in this commit is …
> [move-prover] table intrinsic: bug fix and new intrinsic function

- language/move-vm/test-utils/src/gas_schedule.rs
- language/tools/move-cli/src/base/test.rs
- language/tools/move-unit-test/src/lib.rs
- language/tools/move-unit-test/src/test_reporter.rs
Adds a flag argument to `--statistics` that will allow you to specify if you want the statistics reported in CSV format. 
`Option<Option<String>>` was chosen to support previous usage of `--statistics` as a flag. So `move test --statistics` behaves just as it did before this PR, and `move test --statistics csv` will dump the test statistics in CSV format.
> [move-unit-test] Support CSV output from `--statistics`

- Cargo.lock
- language/move-compiler/src/command_line/compiler.rs
- language/move-compiler/src/interface_generator.rs
- language/move-prover/boogie-backend/Cargo.toml
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/tools/move-cli/tests/build_tests/build_with_bytecode/B/Move.toml
- language/tools/move-cli/tests/build_tests/build_with_bytecode/B/sources/Bar.move
- language/tools/move-cli/tests/build_tests/build_with_bytecode/C/Move.toml
- language/tools/move-cli/tests/build_tests/build_with_bytecode/C/sources/Foo.move
- language/tools/move-cli/tests/build_tests/build_with_bytecode/Move.toml
- language/tools/move-cli/tests/build_tests/build_with_bytecode/args.exp
- language/tools/move-cli/tests/build_tests/build_with_bytecode/args.txt
- language/tools/move-cli/tests/build_tests/build_with_bytecode/sources/A.move
- language/tools/move-package/src/compilation/build_plan.rs
- language/tools/move-package/src/compilation/compiled_package.rs
- language/tools/move-package/src/compilation/model_builder.rs
- language/tools/move-package/src/resolution/resolution_graph.rs
Re-enable the feature to use bytecode as dependencies when compiling Move programs.
Yes
Add later
> [Move-package] Enable bytecode as dependencies

- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/tests/sources/functional/bitwise_features.move
This PR: 1) fix bugs on generating temp variables and trace expressions in Boogie and 2) add specs in the test `bitwise_features` to illustrate combination of bitwise operations and loop invariants, which could also be used for specifying the `features` module.
cargo test in the `move-prover`
> [Move-prover][Bitwise] Bug fix & add new specs to the prover test

- language/move-compiler/src/to_bytecode/canonicalize_handles.rs
- language/move-compiler/src/to_bytecode/mod.rs
- language/move-compiler/src/to_bytecode/translate.rs
- language/tools/move-cli/src/base/disassemble.rs
- language/tools/move-cli/tests/build_tests/canonicalize_module/Move.toml
- language/tools/move-cli/tests/build_tests/canonicalize_module/args.exp
- language/tools/move-cli/tests/build_tests/canonicalize_module/args.txt
- language/tools/move-cli/tests/build_tests/canonicalize_module/sources/m.move
- language/tools/move-cli/tests/build_tests/canonicalize_script/Move.toml
- language/tools/move-cli/tests/build_tests/canonicalize_script/args.exp
- language/tools/move-cli/tests/build_tests/canonicalize_script/args.txt
- language/tools/move-cli/tests/build_tests/canonicalize_script/sources/m.move
Add a pass to the compiler, immediately after conversion from IR to bytecode, to re-order module handles to guarantee a stable ordering.
New tests for canonical order:
```
$ cargo nextest -- canonicalize_
```
> [compiler] Enforce a canonical order for module handles

- language/move-prover/boogie-backend/src/lib.rs
- language/move-prover/boogie-backend/src/options.rs
- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/clean_and_optimize.rs
This PR contains three changes:
- Refactored the native inst filter on Boogie template rendering, especially,
this is to enable instantiations of two (or more) type parameters to pass
to the template rendering engine.
- More coherent and natural flow of assigning the correct borrow edge,
especially when encountering custom borrow primitives.
- Do not clean and optimize intrinsic borrow primitives.
Code consistency and coherence
Yes
CI
> [move-prover] improve the way custom natives are handled in the workflow

- language/move-prover/boogie-backend/src/lib.rs
- language/move-prover/boogie-backend/src/options.rs
- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/clean_and_optimize.rs
This is to cherry-pick #909 which was landed on main. This is to further add prover support on the storage model.
> [cherry-pick][move-prover] better support for custom natives

- language/move-core/types/src/language_storage.rs
- language/move-stdlib/tests/type_name_tests.move
Previously, a type instantiation w/ >1 type parameters was printed without a separator (e.g., `S<u64bool>` instead of `S<u64,bool>`for `S<T1,T2>` instantiated with `u64` and `bool`). This PR adds a comma separator and a test.
>  [printing] fix bug in StructTag::struct_to_canonical_string

- language/move-core/types/src/vm_status.rs
This adds a few status codes that can be used by downstream clients to represent errors caused transactions exceeding certain resource limits.
> [status code] add EXECUTION_LIMIT_REACHED, IO_LIMIT_REACHED and STORAGE_LIMIT_REACHED

- language/move-core/types/src/language_storage.rs
- language/move-stdlib/tests/type_name_tests.move
Previously, a type instantiation w/ >1 type parameters was printed without a comma separator (e.g., `S<u64bool>` instead of `S<u64,bool>`for `S<T1,T2>` instantiated with `u64` and `bool`). This PR adds a comma separator and a test.
(reported in https://github.com/move-language/move/issues/916)
Adding Aptos folks as reviewers to advise on whether this fix is ok as-is or creates a breaking change that should be managed.
> [printing] fix bug in StructTag::struct_to_canonical_string

- language/tools/move-package/src/compilation/build_plan.rs
- language/tools/move-package/src/compilation/compiled_package.rs
- language/tools/move-package/src/compilation/model_builder.rs
- language/tools/move-package/src/resolution/resolution_graph.rs
This PR 1) restrict searching bytecode within the `build` folder; and 2) fix an error message.
> [Move-package] Restrict searching bytecode within the build folder

- language/tools/move-package/src/compilation/build_plan.rs
- language/tools/move-package/src/compilation/model_builder.rs
- language/tools/move-package/src/resolution/resolution_graph.rs
Cherry-pick #922, which is a small fix from #906 to only search bytecode within the build folder.
> [Move-package][Cherry-pick] Restrict searching bytecode within the build folder

- language/tools/move-bytecode-utils/src/module_cache.rs
- language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
This allows us to use GetModule with less boilerplate in some other places where it's needed--needed to unblock some testing in the `sui` repo.
> [chore] implement GetModule for all ModuleResolvers

- language/move-binary-format/src/errors.rs
- language/move-core/types/src/unit_tests/vm_status_test.rs
- language/move-core/types/src/vm_status.rs
- language/tools/move-cli/src/sandbox/utils/mod.rs
This makes the internal status message of VM errors available in `VMStatus` and accessible by adapters. The purpose is to allow adapters to show more detail of errors like they appear e.g. during bytecode verification. These errors happen more often in practice as anticipated, mainly because uses operate with different versions of networks and tools, e.g. deploying code to some chain where it is not deserializable, or using wrong dependencies on disk which do not match those on the network. Currently, the errors produced by the system are as unspecific as 'LINKER_ERROR'.
> [vm errors] Propagate status message to adapters

- language/move-binary-format/src/errors.rs
- language/move-core/types/src/unit_tests/vm_status_test.rs
- language/move-core/types/src/vm_status.rs
- language/tools/move-cli/src/sandbox/utils/mod.rs
I want to revert move-language/move#936 and then later rollforward in a separate commit so I can include just https://github.com/move-language/move/commit/d75b49649146fffc7619f076506f1bda8b40d1bd without also including the status message change in the aptos repo.
> Revert "[vm errors] Propagate status message to adapters"

- language/move-binary-format/src/errors.rs
- language/move-core/types/src/unit_tests/vm_status_test.rs
- language/move-core/types/src/vm_status.rs
- language/tools/move-cli/src/sandbox/utils/mod.rs
Reverts move-language/move#949
Let's wait until we cleanly make it through the branch cut before adding in new features :pray:
> Revert "Rollforward "[vm errors] Propagate status message to adapters""

- language/extensions/move-table-extension/src/lib.rs
- language/move-vm/runtime/src/native_functions.rs
This fixes two issues:
1. `NativeContext::exists_at` should not have flattened the nested options. 
2. The table extension does not waive the base fee even when the resource being loaded is already in the cache.
> [gas] fix NativeContext::exists_at & introduce new gas parameter to fix buggy gas formula in the table extension

- language/move-prover/boogie-backend/src/bytecode_translator.rs
A type parameter that has the key-ability can have a memory space. This PR makes Prover declare the memory variables for type parameters in the generated boogie file.
To declare the memory variables for type parameters
yes
cargo test
> [Prover] Declare the memory variables for type parameters in the generated boogie file

- language/move-prover/boogie-backend/src/bytecode_translator.rs
A type parameter that has the key-ability can have a memory space. This PR makes Prover declare the memory variables for type parameters in the generated boogie file.
To declare the memory variables for type parameters
yes
cargo test
> [Cherry-Pick][Prover] Declare the memory variables for type parameters in the generated boogie file

- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/limit_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/vec_pack_tests.rs
- language/move-bytecode-verifier/src/limits.rs
- language/move-bytecode-verifier/src/verifier.rs
- language/move-core/types/src/vm_status.rs
- language/move-stdlib/src/natives/vector.rs
- language/move-stdlib/tests/move_unit_test.rs
- language/move-stdlib/tests/vector_tests.move
- language/move-vm/runtime/src/config.rs
- language/move-vm/runtime/src/interpreter.rs
- language/move-vm/runtime/src/native_functions.rs
- language/move-vm/types/src/values/values_impl.rs
Add `VMRuntimeLimitsConfig` which exposes `vector_len_max` and allows for bounding vec len at runtime. 
Add verifier check to ensure constant vector sizes limit.
Yes
push_back tests of limit at and above
> add VMRuntimeLimitsConfig and vector len limit

- language/move-prover/src/lib.rs
The reporting logic here attempted to suppress warnings in dependencies, but this was a bit too aggressive and ended up suppressing everything. Changing the logic to report all warnings, particularly given that this is an experimental analysis + the "report all" configuration is needed to reproduce the results from the robust safety paper.
> [prover] fix reporting for escape analysis

- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/binary_samples.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/large_type_test.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/locals.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/many_back_edges.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/mod.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/reference_safety_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
- language/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/vec_pack_tests.rs
- language/move-bytecode-verifier/src/verifier.rs
- language/move-vm/runtime/src/config.rs
- language/testing-infra/transactional-test-runner/src/vm_test_harness.rs
This aligns the default of the metering config to be unbounded, like with other constraints. Addresses https://github.com/aptos-labs/aptos-core/issues/7040
> [bytecode verifier] Relax metering during tests

- language/move-vm/integration-tests/src/tests/loader_tests.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/move_vm.rs
- language/move-vm/runtime/src/runtime.rs
- language/move-vm/runtime/src/session.rs
Separates verification, which blesses `CompiledModule`s from loading which caches `Module`s:
- Renames the existing cache as `loaded_modules`.
- Moves `CompiledModule` out of `Module` and into its own cache -- `compiled_modules` -- populated during verification (which now no longer populates `loaded_modules`).
- `ModuleCache::insert` now recursively adds `Module`s, `Function`s, and `Struct`s (ensuring dependency modules are loaded first), assuming the all dependencies have been verified (failing otherwise).
- Public APIs into the loader that previously returned `Arc<Module>` now also return a `Arc<CompiledModule>`.
This change is motivated by the fact that in the presence of package upgrades, a single `CompiledModule` can end up being stamped out as multiple `Module`s
```
move$ rm -rf …
```
> [loader] Cache CompiledModule separately from Module

- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/move_vm.rs
(Sui-specific) The way packages are republished/upgraded does not require loader invalidation, so this part of the loader can also now be removed.
```
cargo nextest
```
> [loader] Remove invalidation feature

- language/move-core/types/src/vm_status.rs
This cherry-picks two recent status code changes we made on the aptos branch to main.
- The first one adds 3 new status codes (`EXECUTION_LIMIT_REACHED`, `IO_LIMIT_REACHED` & `STORAGE_LIMIT_REACHED`)
- I'm aware that these are somewhat specific to our use case, but the problem already exists and dates back to the Diem legacies. A proper refactoring is needed to address this problem, but that will require quite some work & consideration, especially to ensure backward compatibility.
- The second one adds some reserved status codes for each category. This is just to ensure a slightly out-of-date binary can still deserialize a newer status code. When a new code gets added, it shall replace the next one reserved.
> [status code] cherry-picking the recent status code changes

- language/move-vm/runtime/src/interpreter.rs
- language/move-vm/test-utils/src/gas_schedule.rs
- language/move-vm/types/src/gas.rs
- language/move-vm/types/src/values/values_impl.rs
This PR makes a few minor improvements to the gas metering system to support more complex use cases such as control flow reconstruction or gas profiling.
- It adds a helper function `SimpleInstruction::to_opcode`
- `load_resource` now passes address & type to the client
- The branch instruction callbacks now pass the target offset to the client
- The iterator arguments in the `GasMeter` callbacks now have the `Clone` bound, allowing clients to go over the items multiple times
The changes have been split into individual commits to make them easy to review.
> [gas] add Clone bounds to iterators

- language/move-vm/integration-tests/src/tests/loader_tests.rs
- language/move-vm/integration-tests/src/tests/relinking_tests_b_v1.move
- language/move-vm/integration-tests/src/tests/relinking_tests_c_v0.move
- language/move-vm/integration-tests/src/tests/relinking_tests_c_v1.move
- language/move-vm/runtime/src/loader.rs
Store loaded structs in a `BinaryCache` rather than a vector so that we can look them up by their fully qualified runtime ID and name.  This enables us to canonicalize the global struct index we output for a given struct even if it appears as a definition in multiple modules which can happen due to relinking).
For now, the canonical identity of a package references its **runtime ID**, not its defining ID.  This will change in an upcoming PR.
This also simplifies struct resolution by name (which can use this cache directly rather than going via the loaded module cache, which requires access to a link context) and type loading which does not need a special code path for loading types during a module load anymore.
There is some additional complexity in the `reset` operation that must happen …
> [loader] Canonicalize type identity across relinked modules

- language/tools/move-package/src/lib.rs
- language/tools/move-package/src/resolution/dependency_graph.rs
- language/tools/move-package/src/resolution/lock_file/mod.rs
- language/tools/move-package/tests/test_dependency_graph.rs
- language/tools/move-package/tests/test_lock_file.rs
Previously, temporary lock files were always stored in a sub-directory of the package root because `LockFile` assumed that the `build` directory was always there, while the lock file itself could be committed elsewhere.
But the location of `/build/` is controlled by
`BuildConfig::install_dir` so we should heed that as well when finding where to store the temporary lock file.
Existing tests:
```
cargo nextest
```
> [lock] BuildConfig::install_dir configures temporary lock file directory

- Cargo.lock
- language/move-core/types/src/resolver.rs
- language/move-vm/integration-tests/Cargo.toml
- language/move-vm/integration-tests/src/tests/loader_tests.rs
- language/move-vm/integration-tests/src/tests/relinking_tests_c_v2.move
- language/move-vm/runtime/src/data_cache.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/types/src/data_store.rs
- language/move-vm/types/src/loaded_data/runtime_types.rs
Add a new API to `LinkageResolver` to translate the fully-qualified name of a struct (including its runtime ID) to the defining ID (the ID of the package in storage that first defined the struct).
Use this API to store the defining ID as well as the runtime ID in the loaded `StructType`. (Note: This results in a situation where you can load a type from a type tag, get the type tag for that type and have that operation not be the identity, because it has translated the struct's runtime package ID to its defining package ID).
New loader unit tests:
```
$ cargo nextest -- loader_tests::relink_defining_module
```
> [loader] "defining module" support

- language/move-model/src/model.rs
- language/move-model/src/pragmas.rs
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/bytecode/src/loop_analysis.rs
- language/move-prover/tests/sources/functional/loop_unroll.exp
- language/move-prover/tests/sources/functional/loop_unroll.move
We now support both function-level and module-level
```
pragma unroll = <depth-limit>;
```
The effect of specifying this pragma is:
- if a loop is in the function/module and has loop invariants, this pragma has no effect. The loop will still be verified against loop invariants.
- if a loop is in the function/module and has no loop invariants, if the loop has a spec block with `invariant [unroll = K] true;`, unroll the loop `K` times.
- if a loop is in the function/module and has no loop invariants, and has no per-loop unrolling instruction, use the pramga's count to unroll the loop.
The effect of this pragma is illustrated in the `loop_unroll.move` test case.
More coarse-grained (and user-friendly) loop unrolling annotation
Yes
CI
> [move-prover] add the unroll pragma

- language/extensions/async/move-async-vm/src/async_vm.rs
- language/extensions/async/move-async-vm/tests/testsuite.rs
- language/move-core/types/src/resolver.rs
- language/move-vm/integration-tests/src/tests/bad_storage_tests.rs
- language/move-vm/integration-tests/src/tests/exec_func_effects_tests.rs
- language/move-vm/integration-tests/src/tests/instantiation_tests.rs
- language/move-vm/integration-tests/src/tests/loader_tests.rs
- language/move-vm/integration-tests/src/tests/mutated_accounts_tests.rs
- language/move-vm/runtime/src/data_cache.rs
- language/move-vm/runtime/src/move_vm.rs
- language/move-vm/runtime/src/runtime.rs
- language/move-vm/runtime/src/session.rs
- language/testing-infra/transactional-test-runner/src/vm_test_harness.rs
- language/tools/move-cli/src/sandbox/commands/publish.rs
- language/tools/move-cli/src/sandbox/commands/run.rs
- language/tools/move-unit-test/src/test_runner.rs
Rather than accepting `MoveResolver` by reference accept it by value, but provide generic implementations for references of types that implement the traits.  Also expose a reference to it on `Session` and return it by value on `finish`.
This allows for the creation of resolvers that hold state that is scoped to the session, internally to themselves, rather than relying on that state's lifetime being maintained externally.
```
$ cargo nextest
```
> [session] Accept MoveResolver by value

- language/move-model/src/ast.rs
- language/move-model/src/builder/exp_translator.rs
- language/move-model/src/builder/module_builder.rs
- language/move-model/src/exp_rewriter.rs
- language/move-model/src/lib.rs
- language/move-model/src/model.rs
- language/move-model/src/options.rs
- language/move-model/tests/sources/compile_via_model/simple.exp
- language/move-model/tests/sources/compile_via_model/simple.move
- language/move-model/tests/testsuite.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/interpreter/src/concrete/evaluator.rs
- language/move-prover/tools/spec-flatten/src/ast_print.rs
This is a very first step to enable the move model to process Move functions from source (and not just bytecode), and thus act as a compiler.
In this initial approach, the old Move compiler is run together with the new one. This allows us to continue to have a `CompiledModule` in the `GlobalEnv`. Untangling the model from compiled module is a larger refactoring which we can factor out in different PRs.
A new model builder option `compile_via_model` is added. If set, the body of function definitions will be piped through the model's exp builder to translate expansion AST into model AST, which is now stored in the model and accessible via `FunctionEnv::get_def()`. The model AST has been extended to handle new imperative expression constructs, but the translator has not yet been extended to …
> [model-compiler] Enabling basic type checking of Move functions

- language/move-binary-format/src/file_format.rs
- language/move-vm/integration-tests/src/tests/function_arg_tests.rs
- language/move-vm/integration-tests/src/tests/instantiation_tests.rs
- language/move-vm/integration-tests/src/tests/return_value_tests.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/runtime.rs
- language/move-vm/runtime/src/session.rs
- language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
- language/testing-infra/test-generation/src/lib.rs
- language/testing-infra/transactional-test-runner/src/vm_test_harness.rs
- language/tools/move-cli/src/sandbox/commands/run.rs
Session and the runtime now expects type parameters to be loaded outside function execution, so no longer accepts them as `TypeTag`s but as `Type`s.
This helps us integrate generics into package upgrades by allowing a type parameter to be loaded into a `Type` in its own link context.
```
$ env SOLC_EXE=... cargo nextest --no-fail-fast
```
> [session] Accept Type Parameters by Type, not Tag

- language/move-bytecode-verifier/src/absint.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/session.rs
This operation loads the struct type information.  It differs from `load_type` which, when loading a generic struct type, will also instantiate type parameters.  Having this separate entry into the loader allows us to implement type loading support in the presence of package upgrades from the adapter layer.
```
$ env SOLC=... cargo nextest --no-fail-fast
```
> [session] Expose struct loading

- language/move-binary-format/src/compatibility.rs
- language/move-binary-format/src/normalized.rs
- language/move-binary-format/src/unit_tests/compatibility_tests.rs
- language/tools/move-cli/src/sandbox/utils/mod.rs
Adds a new flag `check_private_entry_linking` that when true checks the private entry function signatures cannot change. E.g.,
If we had
```
entry fun fn() { }
```
and
```
entry fun fn(_x: u64) { }
```
These would be compatible if `check_private_entry_linking` was set to `false` but ruled incompatible if `check_private_entry_linking` was set to `true`.
> [move-binary-format] Support changing of signatures for private entry functions

- language/documentation/tutorial/step_5/BasicCoin/sources/BasicCoin.move
Fix constant warning in compilation:
INCLUDING DEPENDENCY MoveStdlib
BUILDING BasicCoin
warning[W10007]: potential issue with attribute value
┌─ ./sources/BasicCoin.move:94:24
│
94 │     #[expected_failure(abort_code = 2)] // Can specify an abort code
│                        ^^^^^^^^^^   - Replace value with constant from expected module or add `location=...` attribute.
│                        │             
│                        WARNING: passes for an abort from any module.
Fix warnings in compilation time.
YES
TESTED
> Update BasicCoin.move to fix constant warning in compilation

- language/move-stdlib/nursery/tests/event_tests.move
- language/move-stdlib/tests/bcs_tests.move
- language/move-vm/runtime/src/config.rs
- language/move-vm/runtime/src/interpreter.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/transactional-tests/tests/recursion/runtime_layout_deeply_nested.exp
- language/move-vm/transactional-tests/tests/recursion/runtime_layout_deeply_nested.mvir
- language/move-vm/types/src/loaded_data/runtime_types.rs
Cherry-pick the patch from Sui and Aptos to bound the maximal depth of a Move values at runtime. 
Resolves #1059
> [bug fix] Cherry pick bounding runtime value depth for Move values

- language/move-compiler/src/cfgir/absint.rs
continue in while loop causes an unexpected error.
Cherry-pick: MystenLabs/sui#13349
Bugfix: move-language#1068
> [move-compiler] Fixed abstract interpreter bug with continue statement

- language/move-binary-format/src/file_format.rs
The stack transition part of CastU64 is miswritten. It should be u64_value rather than u8_value.
Yes
> [language] Fix the doc of CastU64
